.github/pull_request_template.md
<details>
otherwise).
packages.
</details>
Fix pull request template by closing the `</details>` HTML tag.
It was missing and thus making the full PR collapsable.
=> all: fix pull request template

.gitbook.yaml, .gitignore, README.md
<details>
otherwise).
packages.
</details>
Update the README to be a slightly better introduction to the project. Also adds `.gitbook.yaml` for Gitbook to point to our `./docs` directory.
=> docs: update readme and configure gitbook

core/src/main/java/org/stellar/anchor/paymentservice/PaymentService.java, payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/CirclePaymentService.java, payment-circle/src/test/kotlin/org/stellar/anchor/paymentservice/circle/CirclePaymentServiceTest.kt
<details>
otherwise).
packages.
</details>
Adjusts the `PaymentService` interface based on a discussion offline with @marcelosalloum.
=> paymentservice: Cleanup PaymentService Interface

build.gradle.kts, config-spring-property/build.gradle.kts, core/build.gradle.kts, docs/CONTRIBUTING.md, docs/publishing.md, payment-circle/build.gradle.kts, platform/build.gradle.kts, settings.gradle.kts
<details>
otherwise).
packages.
</details>
Add `publish` task that is configured to publish to MavenCentral.
This is to automate the MavenCentral publication to minimize human errors.
Pending verification by the SonaType OSSRH team.
=> Add publish to maven central task

.gitignore, build.gradle.kts, core/build.gradle.kts, docs/anchor-platform.md, platform/build.gradle.kts, platform/src/main/java/org/stellar/anchor/server/ConfigManagementConfig.java, platform/src/main/java/org/stellar/anchor/server/PaymentConfig.java, platform/src/main/java/org/stellar/anchor/server/SepConfig.java, platform/src/main/java/org/stellar/anchor/server/configurator/PropertiesReader.java, platform/src/test/kotlin/org/stellar/anchor/server/configurator/ConfiguratorTest.kt, platform/src/test/kotlin/org/stellar/anchor/server/configurator/SpringBootConfiguratorTest.kt, platform/src/test/resources/test-anchor-config.yaml
<details>
otherwise).
packages.
</details>
The yaml file can be read from one of the three sources:
* file system
* classpath
* url, such as http, https
It is possible that the yaml file exist outside the local file system.
When doing unit testing, the test yaml file is in `resources` folder which can be read from the classpath.
=> platform: Support reading yaml file from file system, classpath, and url

anchor-integration-netty/build.gradle.kts, anchor-integration-netty/src/main/java/org/stellar/anchor/integration/customer/NettyCustomerIntegration.java, config-spring-property/src/main/java/org/stellar/anchor/server/config/PropertySep12Config.java, core/src/main/java/org/stellar/anchor/config/Sep12Config.java, platform/example.anchor-config.yaml, platform/src/main/resources/default-config.yaml, platform/src/test/resources/test-anchor-config.yaml, settings.gradle.kts
This is a for-your-information PR. I think we don't have to review the details. If you are ok, we can merge to `develop-sep12`.
=> Scaffold NettyCustomerIntegration class and the subproject

docs/payment-circle.md, payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/Readme.md, payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/config/CirclePaymentConfig.java
<details>
otherwise).
packages.
</details>
Add documentation on how to use CirclePaymentService.
We're implementing just a subset of Circle features and submitting it to a more restricted interface so we need to set the definitions somewhere so users know how to configure and use it.
=> payment-circle: add documentation for the CirclePaymentService

core/src/main/java/org/stellar/anchor/integration/customer/CustomerIntegration.java, core/src/main/java/org/stellar/anchor/sep24/Sep24TransactionStore.java, payment-circle/src/test/kotlin/org/stellar/anchor/paymentservice/circle/CirclePaymentServiceTest.kt
There are a couple of warnings related to @throws and unused parameters. They are fixed.
Also commented out an indeterministic circlepayment test failure. 
<details>
otherwise).
packages.
</details>
=> Fixed @throws warnings and a unstable circlepayment test

core/src/main/java/org/stellar/anchor/dto/sep38/GetPricesResponse.java, core/src/main/java/org/stellar/anchor/dto/sep38/InfoResponse.java, core/src/main/java/org/stellar/anchor/sep38/Sep38Service.java, core/src/test/kotlin/org/stellar/anchor/sep38/MockRateIntegration.kt, core/src/test/kotlin/org/stellar/anchor/sep38/Sep38ServiceTest.kt, payment-circle/src/test/kotlin/org/stellar/anchor/paymentservice/circle/CirclePaymentServiceTest.kt
<details>
otherwise).
packages.
</details>
Implement SEP-38 [`GET /prices`](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0038.md#get-prices) endpoint.
Closes #77.
=> core: implement SEP-38 `GET /prices` endpoint

core/src/main/java/org/stellar/anchor/dto/sep38/GetPriceResponse.java, core/src/main/java/org/stellar/anchor/sep38/Sep38Service.java, core/src/test/kotlin/org/stellar/anchor/sep38/Sep38ServiceTest.kt, platform/src/main/java/org/stellar/anchor/platform/controller/Sep38Controller.java
<details>
otherwise).
packages.
</details>
Implement SEP-38 [`GET /price`](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0038.md#get-price) endpoint.
Closes #78.
=> core: implement SEP-38 `GET /price` endpoint

docs/payment-circle.md
<details>
otherwise).
packages.
</details>
Add information about Circle fees.
Closes #90.
=> docs: add information about Circle fees

platform/src/main/java/org/stellar/anchor/platform/controller/Sep12Controller.java, platform/src/main/kotlin/org/stellar/anchor/platform/Sep12Client.kt
closes #133 
<details>
otherwise).
packages.
</details>
Fixed issue 133: PUT /customer should return 202
Bug fix.
N/A
=> platform: PUT /customer should return 202

Makefile
add Makefile for docker builds
=> add Makefile for docker builds

core/src/main/java/org/stellar/anchor/model/Sep38Quote.java, core/src/main/java/org/stellar/anchor/model/Sep38QuoteBuilder.java, core/src/main/java/org/stellar/anchor/sep38/Sep38QuoteStore.java, core/src/main/java/org/stellar/anchor/sep38/Sep38Service.java, core/src/test/java/org/stellar/anchor/sep38/PojoSep38Quote.java, core/src/test/kotlin/org/stellar/anchor/sep38/Sep38ServiceTest.kt, data-spring-jdbc/src/main/java/org/stellar/anchor/server/data/JdbcSep38Quote.java, data-spring-jdbc/src/main/java/org/stellar/anchor/server/data/JdbcSep38QuoteRepo.java, data-spring-jdbc/src/main/java/org/stellar/anchor/server/data/JdbcSep38QuoteStore.java, platform/src/main/java/org/stellar/anchor/platform/AnchorPlatformServer.java, platform/src/main/java/org/stellar/anchor/platform/SepConfig.java
<details>
otherwise).
packages.
</details>
Storing quote in the platform database when handling `POST /quote` requests.
Closes #81.
=> core, platform, data-spring-jdbc: storing quote in the platform database handling `POST /quote` requests

core/src/main/java/org/stellar/anchor/sep38/Sep38Service.java, core/src/test/kotlin/org/stellar/anchor/sep38/Sep38ServiceTest.kt, platform/src/main/java/org/stellar/anchor/platform/controller/Sep38Controller.java, platform/src/main/kotlin/org/stellar/anchor/platform/Sep38Client.kt, platform/src/main/kotlin/org/stellar/anchor/platform/Sep38Tests.kt, platform/src/test/kotlin/org/stellar/anchor/platform/AnchorPlatformIntegrationTest.kt
<details>
otherwise).
packages.
</details>
Implement the logic to retrieve a quote by ID, for `GET {SEP-38}/quote/:id`
Closes #80.
=> code, platform: implement the logic to retrieve a quote by ID, for `GET {SEP-38}/quote/:id`

payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/util/CircleDateFormatter.java, payment-circle/src/test/kotlin/org/stellar/anchor/paymentservice/circle/CirclePaymentServiceTest.kt, payment-circle/src/test/kotlin/org/stellar/anchor/paymentservice/circle/util/CircleDateFormatterTest.kt
<details>
otherwise).
packages.
</details>
Fix issue caused by SimpleDateFormat not being thread-safe.
Fixes #112
=> payment-circle: fix issue caused by SimpleDateFormat not being thread safe

core/src/main/java/org/stellar/anchor/dto/sep38/InfoResponse.java
#closes #152
<details>
otherwise).
packages.
</details>
Check if sep38 is enabled in the `/info` endpoing
N/A
N/A
=> core: Issue #152 Check if sep38 is enabled in the `/info` endpoing

config-spring-property/src/main/java/org/stellar/anchor/server/config/PropertySep31Config.java, core/build.gradle.kts, core/src/main/java/org/stellar/anchor/asset/AssetInfo.java, core/src/main/java/org/stellar/anchor/config/Sep31Config.java, core/src/main/java/org/stellar/anchor/dto/sep31/Sep31InfoResponse.java, core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java, core/src/main/java/org/stellar/anchor/util/PropertyUtil.java, core/src/test/kotlin/org/stellar/anchor/util/PropertyUtilTest.java, platform/example.anchor-config.yaml, platform/src/main/java/org/stellar/anchor/platform/ConfigManagementConfig.java, platform/src/main/java/org/stellar/anchor/platform/SepConfig.java, platform/src/main/java/org/stellar/anchor/platform/controller/Sep31Controller.java, platform/src/main/kotlin/org/stellar/anchor/platform/Sep31Client.kt, platform/src/main/kotlin/org/stellar/anchor/platform/Sep31Tests.kt, platform/src/main/kotlin/org/stellar/anchor/platform/Sep38Client.kt, platform/src/main/kotlin/org/stellar/anchor/platform/Sep38Tests.kt, platform/src/main/kotlin/org/stellar/anchor/platform/SepClient.kt, platform/src/main/resources/assets-test.json, platform/src/main/resources/org/stellar/anchor/platform/SepClient.kt, platform/src/test/resources/test_assets.json
<details>
otherwise).
packages.
</details>
Implement the Sep31 `/info` endpoint.
=> sep31: /info endpoint

core/src/main/java/org/stellar/anchor/dto/sep31/Sep31GetTransactionResponse.java, core/src/main/java/org/stellar/anchor/dto/sep31/Sep31PatchTransactionRequest.java, core/src/main/java/org/stellar/anchor/dto/sep31/Sep31PostTransactionRequest.java, core/src/main/java/org/stellar/anchor/dto/sep31/Sep31PostTransactionResponse.java, core/src/main/java/org/stellar/anchor/model/Sep31Transaction.java, core/src/main/java/org/stellar/anchor/model/Sep31TransactionBuilder.java, core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java, core/src/main/java/org/stellar/anchor/sep31/Sep31TransactionStore.java, core/src/main/java/org/stellar/anchor/util/PropertyUtil.java, data-spring-jdbc/build.gradle.kts, data-spring-jdbc/src/main/java/org/stellar/anchor/server/data/DataJpaTestApplication.java, data-spring-jdbc/src/main/java/org/stellar/anchor/server/data/JdbcSep31RefundPayment.java, data-spring-jdbc/src/main/java/org/stellar/anchor/server/data/JdbcSep31Refunds.java, data-spring-jdbc/src/main/java/org/stellar/anchor/server/data/JdbcSep31Transaction.java, data-spring-jdbc/src/main/java/org/stellar/anchor/server/data/JdbcSep31TransactionRepo.java, data-spring-jdbc/src/main/java/org/stellar/anchor/server/data/JdbcSep31TransactionStore.java, data-spring-jdbc/src/main/java/org/stellar/anchor/server/data/JdbcSep38QuoteStore.java, data-spring-jdbc/src/test/kotlin/org/stellar/anchor/server/data/JdbcSep31TransactionTest.kt, platform/build.gradle.kts, platform/src/test/resources/test-anchor-config.yaml
closes #161
<details>
otherwise).
packages.
</details>
Sep31 transaction JPA persistence with minimal unit tests
Part of sep31 implementation.
N/A
=> Sep31 transaction JPA persistence with minimal unit tests

core/src/main/java/org/stellar/anchor/sep38/Sep38Service.java, core/src/test/kotlin/org/stellar/anchor/sep38/Sep38ServiceTest.kt, platform/example.anchor-config.yaml, platform/src/main/java/org/stellar/anchor/platform/controller/GlobalControllerExceptionHandler.java, platform/src/main/resources/default-config.yaml, platform/src/test/resources/test-anchor-config.yaml, settings.gradle.kts
<details>
otherwise).
packages.
</details>
Update code of `platform` and `anchor-reference-server` so the SEP-38 implementation becomes compliant with the validation tool https://github.com/stellar/stellar-anchor-tests.
As part of #116.
I'll add a GH Action to execute the validation tool https://github.com/stellar/stellar-anchor-tests against this project in the next PR.
=> all: Update code of `platform` and `anchor-reference-server` so the SEP-38 implementation becomes compliant with the validation tool

Dockerfile
This PR adds wget and net-tools to container image for temporary introspection 
Will remove wget and net-tools once testing is complete.
=> add wget and net-tools tempoarily for testing

core/src/main/java/org/stellar/anchor/asset/AssetInfo.java, core/src/main/java/org/stellar/anchor/sep31/Sep31TransactionStore.java, core/src/main/java/org/stellar/anchor/util/Log.java, data-spring-jdbc/src/main/java/org/stellar/anchor/server/data/JdbcSep31TransactionRepo.java, data-spring-jdbc/src/main/java/org/stellar/anchor/server/data/JdbcSep31TransactionStore.java, data-spring-jdbc/src/main/java/org/stellar/anchor/server/data/StellarAccountPageToken.java, data-spring-jdbc/src/main/java/org/stellar/anchor/server/data/StellarAccountPageTokenRepo.java, platform/src/main/java/org/stellar/anchor/platform/AnchorPlatformServer.java, platform/src/main/java/org/stellar/anchor/platform/ConfigManagementConfig.java, platform/src/main/java/org/stellar/anchor/platform/IntegrationConfig.java, platform/src/main/java/org/stellar/anchor/platform/PaymentConfig.java, platform/src/main/java/org/stellar/anchor/platform/callback/RestCustomerIntegration.java, platform/src/main/java/org/stellar/anchor/platform/callback/RestFeeIntegration.java, platform/src/main/java/org/stellar/anchor/platform/callback/RestRateIntegration.java, platform/src/main/java/org/stellar/anchor/platform/paymentobserver/MemoryPageTokenStore.java, platform/src/main/java/org/stellar/anchor/platform/paymentobserver/PageTokenStore.java, platform/src/main/java/org/stellar/anchor/platform/paymentobserver/PaymentListener.java, platform/src/main/java/org/stellar/anchor/platform/paymentobserver/StellarPaymentObserver.java, platform/src/main/java/org/stellar/anchor/platform/paymentobserver/StellarTransaction.java, platform/src/main/java/org/stellar/anchor/platform/paymentobserver/TransactionEvent.java, platform/src/main/java/org/stellar/anchor/platform/service/JdbcPageTokenStore.java, platform/src/main/java/org/stellar/anchor/platform/service/PaymentOperationToEventListener.java, platform/src/main/resources/assets-test.json, platform/src/test/kotlin/org/stellar/anchor/platform/RestRateIntegrationTest.kt
<details>
otherwise).
packages.
</details>
Implement payment observer. 
N/A.
1. Events will be triggered when the event API is ready.
2. There are protected fields in Java Stellar SDK. We need to submit PRs to make those fields accessible (by getters) to validate and populate event fields. 
3. TransactionEvent class is mocked before the Event API PR is merged.
=> platform: Payment observer implementation

.github/workflows/build_and_test.yml, anchor-reference-server/src/main/java/org/stellar/anchor/reference/model/Quote.java, anchor-reference-server/src/main/java/org/stellar/anchor/reference/service/RateService.java, anchor-reference-server/src/test/kotlin/org/stellar/anchor/server/AnchorReferenceServerIntegrationTest.kt, core/src/main/java/org/stellar/anchor/integration/rate/GetRateRequest.java, core/src/main/java/org/stellar/anchor/sep38/Sep38Service.java, core/src/test/kotlin/org/stellar/anchor/sep38/Sep38ServiceTest.kt, platform-apis/src/main/java/org/stellar/platform/apis/callbacks/requests/GetRateRequest.java, platform/src/test/kotlin/org/stellar/anchor/platform/RestRateIntegrationTest.kt
<details>
otherwise).
packages.
</details>
Update rates model of the callback API to match the latest version.
Also, implement method to get rate by ID in the reference server.
Close #181
=> anchor-reference-server: update rates model of the callback API to match the latest version

platform/src/main/resources/log4j2.yaml
<details>
otherwise).
packages.
</details>
Reduce logging level of `org.apache`, `org.hibernate`, and `com.zaxxer` to WARN.
Reduce the excessive logging. 
N/A
=> platform: Reduce AnchorPlatformServer logging level

anchor-reference-server/src/main/java/org/stellar/anchor/reference/AnchorReferenceServer.java, anchor-reference-server/src/main/java/org/stellar/anchor/reference/controller/FeeController.java, core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java, core/src/main/java/org/stellar/anchor/sep31/Sep31TransactionStore.java, data-spring-jdbc/src/main/java/org/stellar/anchor/server/data/JdbcSep31TransactionStore.java, platform/src/main/java/org/stellar/anchor/platform/controller/Sep31Controller.java, platform/src/main/java/org/stellar/anchor/platform/paymentobserver/ObservedPayment.java, platform/src/main/java/org/stellar/anchor/platform/service/PaymentOperationToEventListener.java, platform/src/test/kotlin/org/stellar/anchor/platform/service/PaymentOperationToEventListenerTest.kt
<details>
otherwise).
packages.
</details>
Add unit tests for the payment observer to make sure the behavior is as expected.
We didn't have any tests in place, which made the code a bit unsafe. After adding the tests I also identified a few errors and fixed them.
=> Stellar observer: add unit tests and fixes

core/src/main/java/org/stellar/anchor/sep10/JwtService.java, core/src/test/kotlin/org/stellar/anchor/sep10/JwtServiceTest.kt
<details>
otherwise).
packages.
</details>
Added signature algorithm validation.
This is to avoid the security vulnerability https://www.oracle.com/security-alerts/cpuapr2022.html
We should make sure the signature is accepted only when it is signed by H256. 
N/A
=> core: Add signature algorithm validation

.github/workflows/build_and_test.yml
<details>
otherwise).
packages.
</details>
Make sure the SEP tests are executed not only in the PRs but also the main branch after merged.
We had an incident where we didn't make the necessary changes to stellar/kube and that could have been detected earlier if we had SEP tests in the main branch.
Make it required to pass the SEP tests before merging a PR.
=> tests: make sure SEP tests are being executed in the main branch as well

anchor-reference-server/src/main/java/org/stellar/anchor/reference/controller/Sep24InteractiveController.java, core/src/main/java/org/stellar/anchor/asset/AssetInfo.java, core/src/main/java/org/stellar/anchor/config/Sep24Config.java, integration-tests/src/test/resources/test-anchor-config.yaml, platform/example.anchor-config.yaml, platform/src/main/java/org/stellar/anchor/platform/ConfigManagementConfig.java, platform/src/main/java/org/stellar/anchor/platform/SepConfig.java, platform/src/main/java/org/stellar/anchor/platform/config/PropertyKafkaConfig.java, platform/src/main/java/org/stellar/anchor/platform/config/PropertySep24Config.java, platform/src/main/java/org/stellar/anchor/platform/config/PropertySqsConfig.java, platform/src/main/java/org/stellar/anchor/platform/controller/Sep24Controller.java, platform/src/main/resources/assets-test.json, platform/src/main/resources/default-config.yaml, platform/src/main/resources/sep1/stellar-wks.toml, platform/src/test/resources/test-anchor-config.yaml
<details>
otherwise).
packages.
</details>
This PR added SEP-24 skeleton. 
To re-activate the SEP-24 development for MGI.
1. Transaction query filters are not implemented correctly.
2. `completed_at` field of `Transaction` is not handled gracefully.
=> Added SEP-24 skeleton

anchor-reference-server/src/main/java/org/stellar/anchor/reference/controller/Sep24InteractiveController.java, core/src/main/java/org/stellar/anchor/asset/AssetInfo.java, core/src/main/java/org/stellar/anchor/config/CirclePaymentObserverConfig.java, core/src/main/java/org/stellar/anchor/event/models/Customers.java, core/src/main/java/org/stellar/anchor/event/models/StellarTransaction.java, core/src/main/java/org/stellar/anchor/event/models/TransactionEvent.java, core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java, core/src/main/java/org/stellar/anchor/util/Log.java, core/src/main/java/org/stellar/anchor/util/MemoHelper.java, integration-tests/src/test/resources/test-anchor-config.yaml, platform/build.gradle.kts, platform/example.anchor-config.yaml, platform/src/main/java/org/stellar/anchor/platform/PaymentConfig.java, platform/src/main/java/org/stellar/anchor/platform/SepConfig.java, platform/src/main/java/org/stellar/anchor/platform/config/PropertyCirclePaymentObserverConfig.java, platform/src/main/java/org/stellar/anchor/platform/config/PropertyKafkaConfig.java, platform/src/main/java/org/stellar/anchor/platform/config/PropertySqsConfig.java, platform/src/main/java/org/stellar/anchor/platform/controller/CirclePaymentObserverController.java, platform/src/main/java/org/stellar/anchor/platform/controller/Sep24Controller.java, platform/src/main/java/org/stellar/anchor/platform/paymentobserver/CirclePaymentObserverService.java, platform/src/main/java/org/stellar/anchor/platform/paymentobserver/ObservedPayment.java, platform/src/main/java/org/stellar/anchor/platform/paymentobserver/Readme.md, platform/src/main/java/org/stellar/anchor/platform/paymentobserver/StellarPaymentObserver.java, platform/src/main/java/org/stellar/anchor/platform/service/PaymentOperationToEventListener.java, platform/src/main/resources/default-config.yaml, platform/src/test/kotlin/org/stellar/anchor/platform/paymentobserver/CirclePaymentObserverServiceTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/service/PaymentOperationToEventListenerTest.kt, platform/src/test/resources/test-anchor-config.yaml
<details>
otherwise).
packages.
</details>
Finish Circle Payment Observer:
* Add the necessary configurations
* Add tests
* Trigger the event
* Update the `PaymentOperationToEventListener` code to include the Circle information.
Close #97
=> circle-payments-observer: add tests and trigger event

core/src/main/java/org/stellar/anchor/util/MemoHelper.java, integration-tests/src/main/kotlin/org/stellar/anchor/platform/Sep24Client.kt, integration-tests/src/main/kotlin/org/stellar/anchor/platform/Sep31Client.kt, integration-tests/src/main/kotlin/org/stellar/anchor/platform/SepClient.kt, integration-tests/src/test/kotlin/org/stellar/anchor/platform/AnchorPlatformIntegrationTest.kt, integration-tests/src/test/kotlin/org/stellar/anchor/platform/Sep24Tests.kt, integration-tests/src/test/kotlin/org/stellar/anchor/platform/Sep31Tests.kt, integration-tests/src/test/kotlin/org/stellar/anchor/platform/SepTestSuite.kt, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep24RefundPayment.java, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep24Transaction.java, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep31Transaction.java, platform/src/main/java/org/stellar/anchor/platform/data/SepTransaction.java, platform/src/main/java/org/stellar/anchor/platform/service/TransactionService.java, platform/src/main/resources/sep1/stellar-wks.toml
<details>
otherwise).
packages.
</details>
Added SEP-24 integration happy path tests without refund. 
We are switching to MGI development and pause the SEP-24 refund development for a couple of days.
Need to add refund integration tests.
=> all: SEP-24 integration tests (happy path only without refund)

core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java, core/src/main/java/org/stellar/anchor/util/MemoHelper.java, core/src/test/kotlin/org/stellar/anchor/sep31/Sep31ServiceTest.kt, platform/src/main/resources/anchor-config-defaults.yaml
Closes #236 
<details>
otherwise).
packages.
</details>
This PR simplifies SEP-31 calculation according to i[ssue#236.](https://github.com/stellar/java-stellar-anchor-sdk/issues/236) 
See [issue#236](https://github.com/stellar/java-stellar-anchor-sdk/issues/236)
N/A
=> core: Added simplified SEP-31 calculation

docs/deployment-examples/example-k8s/anchor-platform-dev/anchor-config.yaml, docs/deployment-examples/example-k8s/anchor-platform-dev/readme.md, docs/deployment-examples/example-k8s/anchor-platform-dev/reference-server-config-map.yaml, docs/deployment-examples/example-k8s/anchor-platform-dev/reference-server-deployment.yaml, docs/deployment-examples/example-k8s/anchor-platform-dev/reference-server-ingress.yaml, docs/deployment-examples/example-k8s/anchor-platform-dev/reference-server-service.yaml, docs/deployment-examples/example-k8s/anchor-platform-dev/sep-server-config-map.yaml, docs/deployment-examples/example-k8s/anchor-platform-dev/sep-server-deployment.yaml, docs/deployment-examples/example-k8s/anchor-platform-dev/sep-server-ingress.yaml, docs/deployment-examples/example-k8s/anchor-platform-dev/sep-server-service.yaml, docs/deployment-examples/example-k8s/anchor-platform-dev/zookeeper-kafka-deployment.yaml
Adding anchor-platform-dev K8 manifest created by Stephen as examples.
=> add anchor-playtform-dev k8 manifests to docs

core/src/main/java/org/stellar/anchor/asset/JsonAssetService.java, core/src/main/java/org/stellar/anchor/sep10/Sep10Service.java, core/src/main/java/org/stellar/anchor/util/Log.java, core/src/test/kotlin/org/stellar/anchor/util/LogTest.kt
<details>
otherwise).
packages.
</details>
Removed Bean format logging.
Code cleanup.
Use gson ExclusionStrategy to avoid send sensitive information to log stream.
N/A
N/A
=> core: Make logging implementation more consistent.

anchor-reference-server/src/main/java/org/stellar/anchor/reference/AnchorReferenceConfig.java, anchor-reference-server/src/main/java/org/stellar/anchor/reference/client/PlatformApiClient.java, anchor-reference-server/src/main/java/org/stellar/anchor/reference/controller/HealthController.java, anchor-reference-server/src/main/java/org/stellar/anchor/reference/event/KafkaListener.java, anchor-reference-server/src/main/java/org/stellar/anchor/reference/service/HealthCheckService.java, api-schema/src/main/java/org/stellar/anchor/api/platform/HealthCheckStatus.java, core/src/main/java/org/stellar/anchor/healthcheck/HealthCheckProcessor.java, core/src/main/java/org/stellar/anchor/healthcheck/HealthCheckable.java, integration-tests/src/main/kotlin/org/stellar/anchor/platform/ReferenceServerClient.kt, integration-tests/src/main/kotlin/org/stellar/anchor/platform/SepClient.kt, integration-tests/src/test/kotlin/org/stellar/anchor/platform/AnchorPlatformIntegrationTest.kt, integration-tests/src/test/kotlin/org/stellar/anchor/platform/PlatformTests.kt, integration-tests/src/test/kotlin/org/stellar/anchor/platform/ReferenceServerTests.kt, integration-tests/src/test/kotlin/org/stellar/anchor/platform/Sep31Tests.kt, integration-tests/src/test/kotlin/org/stellar/anchor/platform/SepTestSuite.kt, platform/src/main/java/org/stellar/anchor/platform/paymentobserver/StellarPaymentObserver.java
<details>
otherwise).
packages.
</details>
Add/fix reference server health check and integration test.
N/A
Only KafkaListener is checked. We should add SQS checks.
=> all: Add/fix reference server health check and integration test.

docs/Anchor Integration/Callbacks API.yml, docs/Anchor Integration/Events Schema.yml, docs/Anchor Integration/Platform API.yml, docs/Anchor Integration/Readme.md, docs/SEP-31/sep31-happypath.txt
<details>
otherwise).
packages.
</details>
Bring documentation from the stellar/stellar-anchor-platform repository.
So we maintain all documentation in a single repo, which is easier to maintain.
This is the first step for #288.
=> docs: bring documentation from the stellar/stellar-anchor-platform repository

end-to-end-tests/end_to_end_tests.py
<details>
otherwise).
packages.
</details>
Fix end-to-end tests.
SEP-31 flow was wrong because we were not creating a sender client. This started to break recently.
Also, SEP-38 now requires a `"context"` field.
=> tests: fix end-to-end-tests

build.gradle.kts, core/src/main/java/org/stellar/anchor/sep24/Sep24Helper.java, core/src/main/java/org/stellar/anchor/sep24/Sep24RefundPayment.java, core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java, core/src/main/java/org/stellar/anchor/sep24/Sep24Transaction.java, core/src/main/java/org/stellar/anchor/sep24/Sep24TransactionBuilder.java, core/src/main/java/org/stellar/anchor/util/Log.java, core/src/test/java/org/stellar/anchor/sep24/PojoSep24Transaction.java, core/src/test/kotlin/org/stellar/anchor/model/Sep24TransactionTest.kt, core/src/test/kotlin/org/stellar/anchor/sep24/Sep24ServiceTest.kt, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep24Transaction.java, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep24TransactionRepo.java, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep24TransactionStore.java
1. Renamed `stellarAccount` to `sep10Account`
2. Renamed `stellarAccountMemo` to `sep10AccountMemo`
3. Renamed `receivingAnchorAccount` to `withdrawAnchorAccount`
4. Removed un-related fields from MGI implementation.
5. Added field comments
<details>
otherwise).
packages.
</details>
Refactor and clean up SEP-24 fields
Some of the fields are confusing. Rename, remove, and comment the fields.
N/A
=> core: Refactor/clean up SEP24 fields and add field comments

core/src/main/java/org/stellar/anchor/sep12/Sep12Service.java, core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java, core/src/test/kotlin/org/stellar/anchor/sep31/Sep31ServiceTest.kt
<details>
otherwise).
packages.
</details>
Add customer type to sender/receiver validation methods and delete calls.
Customer type should be specified for these calls, as specified in SEP12.
This is meant to be a short term-solution to resolve integration issues. TODOs have been added to address long term concerns (eg, choosing the first customer type in the sender/receiver map)
=> core: Add customer type to sender/receiver validation methods and delete calls.

anchor-reference-server/src/main/java/org/stellar/anchor/reference/model/Customer.java, anchor-reference-server/src/main/java/org/stellar/anchor/reference/service/CustomerService.java, api-schema/src/main/java/org/stellar/anchor/api/callback/PutCustomerRequest.java, api-schema/src/main/java/org/stellar/anchor/api/sep/sep12/Sep12PutCustomerRequest.java, integration-tests/src/test/kotlin/org/stellar/anchor/platform/Sep12Tests.kt
<details>
otherwise).
packages.
</details>
Add `clabe_number` support to anchor platform.
`clabe_number` in SEP-09 is not currently supported
=> SEP-09: Add clabe_number support to anchor platform

docs/03 - Implementing the Anchor Server/Communication/Callbacks API.yml
<details>
otherwise).
packages.
</details>
Design a callback API endpoint so the Platform can call the Anchor backend for a unique `stellar_address:memo` pair, where the stellar_addres must be the address of an existing account in the Stellar network.
*Request:*
```
GET {callbackAPI}/unique_address
```
*Response:*
```json
{
"unique_address": {
"stellar_address": "string",
"memo": "string"
}
}
```
Here's an example of how this flow would work, considering a scenario where the Receiving Anchor would create the unique `stellar_account:memo` pairs in Circle:
```mermaid
sequenceDiagram
title: SEP-31 Transaction Flow with "{callbackAPI}/unique_address"
participant Stellar …
```
=> callbackApi: design endpoint to be called for a unique `stellar_address:memo` pair

docs/03 - Implementing the Anchor Server/Communication/Callbacks API.yml
Added memo_type to the `/unique_address` field.
<details>
otherwise).
packages.
</details>
=> doc: Added memo_type to the `/unique_address` field.

helm-charts/sep-service/templates/configmap.yaml
This PR updates helm chart with changes for common-previews reflected in 
https://github.com/stellar/kube/pull/1013
=> add anchor-callback to helm chart

core/src/main/java/org/stellar/anchor/filter/ApiKeyFilter.java, core/src/main/java/org/stellar/anchor/filter/JwtTokenFilter.java, core/src/main/java/org/stellar/anchor/util/UrlValidationUtil.java, platform/src/main/java/org/stellar/anchor/platform/ConfigManagementConfig.java, platform/src/main/java/org/stellar/anchor/platform/callback/PlatformIntegrationHelper.java, platform/src/main/java/org/stellar/anchor/platform/config/PropertyAppConfig.java, platform/src/main/java/org/stellar/anchor/platform/config/PropertyCircleConfig.java, platform/src/main/java/org/stellar/anchor/platform/config/PropertyCirclePaymentObserverConfig.java, platform/src/main/java/org/stellar/anchor/platform/config/PropertyEventConfig.java, platform/src/main/java/org/stellar/anchor/platform/config/PropertySep10Config.java, platform/src/main/java/org/stellar/anchor/platform/config/PropertySep12Config.java, platform/src/main/java/org/stellar/anchor/platform/config/PropertySep38Config.java, platform/src/main/java/org/stellar/anchor/platform/config/PropertySqsConfig.java, platform/src/test/kotlin/org/stellar/anchor/platform/config/EventConfigTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/config/Sep12ConfigTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/config/Sep1ConfigTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/config/Sep31ConfigTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/config/Sep38ConfigTest.kt
<details>
otherwise).
packages.
</details>
Add extra logs.
Also, a lot of auto-formatting lines 🤷.
To improve debugging.
=> improvement: add extra logs

docs/resources/deployment-examples/example-fargate/example_config/anchor_config.yaml, helm-charts/sep-service/example_values.yaml, helm-charts/sep-service/templates/configmap.yaml, integration-tests/src/test/resources/integration-test.anchor-config.yaml, platform/src/main/resources/anchor-docker-compose-config.yaml
<details>
otherwise).
packages.
</details>
=> helm: issue-455: Add uniqueAddressIntegrationEndPoint to helm chart

helm-charts/sep-service/templates/configmap.yaml
=> preview-assets

anchor-reference-server/src/main/resources/anchor-reference-server.yaml, docs/resources/deployment-examples/example-k8s/anchor-platform-dev/reference-server-config-map.yaml, docs/resources/deployment-examples/example-k8s/anchor-platform-dev/sep-server-config-map.yaml, helm-charts/sep-service/Chart.yaml
…ibution wallet consistent with the assets.json
<details>
otherwise).
packages.
</details>
Add `distributionWallet` to reference server and make the default value of the `distributionWallet` consistent with the `assets-test.json`
N/A
N/A
=> issue-457: Update distributionWallet fields. 

anchor-reference-server/src/main/java/org/stellar/anchor/reference/controller/UniqueAddressController.java, anchor-reference-server/src/main/java/org/stellar/anchor/reference/service/UniqueAddressService.java, core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java, core/src/main/java/org/stellar/anchor/util/MemoHelper.java, core/src/main/java/org/stellar/anchor/util/StringHelper.java, platform/src/main/resources/assets-test.json, platform/src/test/kotlin/org/stellar/anchor/sep31/Sep31DepositInfoGeneratorTest.kt
<details>
otherwise).
packages.
</details>
Fix empty memo cause complaints in the SEP tests
Bug fixing.
More test cases should be added to make sure the AP can handle the response without throwing internal errors.
=> core: Fix empty memo cause complaints in the SEP tests

build.gradle.kts, core/build.gradle.kts, gradle/libs.versions.toml, service-runner/build.gradle.kts
<details>
otherwise).
packages.
</details>
Fix the issue of skipping tests in `core` and `service-runner` subproject. 
N/A
N/A
=> core/service-runner: Fix the tests skipping problem (core and service-runner)

build.gradle.kts, platform/build.gradle.kts
<details>
otherwise).
packages.
</details>
Add missing AWS IAM dependency.
The refactor from 3ddb1818 missed including the AWS IAM library in the gradle build, which removed the ability of connecting with a database using AWS IAM.
=> hotfix: add missing AWS IAM dependency

anchor-reference-server/src/main/java/org/stellar/anchor/reference/controller/Sep24InteractiveController.java, core/src/main/java/org/stellar/anchor/auth/JwtService.java, platform/src/main/java/org/stellar/anchor/platform/controller/CirclePaymentObserverController.java, platform/src/main/java/org/stellar/anchor/platform/payment/observer/circle/CirclePaymentObserverService.java, platform/src/test/kotlin/org/stellar/anchor/platform/payment/observer/CirclePaymentObserverServiceTest.kt
<details>
otherwise).
packages.
</details>
1. Fix  JWT Signature Verification Bypass
2. Fix the Cross-site Scripting
3. Fix the Servier Side Request Forgery
N/A
Medium and low risks are not fixed.
=> risk: Fix high-risk vulnerabilities reported by Snyk

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
<details>
otherwise).
packages.
</details>
Add default issue templates for bug reports, feature requests and some useful links.
To influence the community to share the relevant information we'll need to investigate bugs and evaluate feature requests.
=> Feature: add default issue templates for bug reports, feature requests and some useful links

.github/workflows/basic_tests.yml, .github/workflows/release.yml, .github/workflows/release_develop.yml, .github/workflows/release_edge_builds.yml, .github/workflows/release_release.yml, build.gradle.kts, core/build.gradle.kts
<details>
otherwise).
packages.
</details>
Configure CI for the Gitflow release process. Currently, we're only handling Docker releases. Here's how it will work:
* [`.github/workflows/basic_tests.yml`](https://github.com/stellar/java-stellar-anchor-sdk/blob/5e1f90378fa87561c645089adb9143afbadd22df/.github/workflows/basic_tests.yml)
* **When is it executed?**
* On every PR
* When code is merged into `develop`, `release/**` or `main`.
* **What it does?**
* Checks if the code is formatted.
* Runs the unit tests.
* Runs the embedded integration tests.
* Tests the SEP endpoints with the node tool [stellar/stellar-anchor-tests](https://github.com/stellar/stellar-anchor-tests)
* …
=> Feature: configure CI for the Gitflow release process

.github/ISSUE_TEMPLATE/release_a_new_version.md, .github/workflows/basic_tests.yml, .github/workflows/release_release.yml, CHANGELOG.md, build.gradle.kts
<details>
otherwise).
packages.
</details>
Release version `1.1.0`.
Addresses #550.
=> Release 1.1.0 to develop

.github/workflows/basic_tests.yml, .github/workflows/branch_develop.yml, .github/workflows/branch_release.yml, .github/workflows/published.yml
<details>
otherwise).
packages.
</details>
Execute the CI when we merge something into the `main` branch.
To make sure the main branch is being fully tested, at least as much as the develop branch.
=> Feature: execute the CI when we merge something into the `main` branch

CHANGELOG.md, build.gradle.kts, helm-charts/sep-service/Chart.yaml
<details>
otherwise).
packages.
</details>
Update helm chart version to 0.3.88.
It had not been updated when we made the Stellar Observer into a separate service in https://github.com/stellar/java-stellar-anchor-sdk/pull/546/files#diff-78b9c67cf91b015c1ed14485867e595e1ba056a8e28563c2d037c8fe073a7893.
=> Hotfix: update helm chart version to 0.3.88

.github/workflows/basic_tests.yml, .github/workflows/branch_develop.yml, .github/workflows/branch_release.yml, .github/workflows/codeql_analysis.yml, .github/workflows/end_to_end_tests.yml, .github/workflows/published.yml
<details>
otherwise).
packages.
</details>
1. Document the description of the workflows if it does not seem obvious.
2. Add workflow_dispatch trigger so that we may run the workflow from GH UI.
Improve the documents.
The `Run Workflow` button won't show up until it is merged to the `develop` branch.
=> added workflow_dispatch

build.gradle.kts
<details>
otherwise).
packages.
</details>
Start logging test results.
To have better visibility when something goes wrong.
=> Feature: log test results

platform/src/main/java/org/stellar/anchor/platform/service/TransactionService.java, platform/src/test/kotlin/org/stellar/anchor/platform/service/TransactionServiceTest.kt
<details>
otherwise).
packages.
</details>
Add refund status to TransactionService. 
Bug fixes.
N/A
=> platform: Allow refund status to patch transaction

.github/ISSUE_TEMPLATE/release_a_new_version.md
<details>
otherwise).
packages.
</details>
Update the action after merging the release to main
Make the library publication more clear. 
N/A
=> release: Update the action after merging the release to `main` branch

CHANGELOG.md, build.gradle.kts, core/src/test/kotlin/org/stellar/anchor/sep10/Sep10ServiceTest.kt, core/src/test/kotlin/org/stellar/anchor/sep31/Sep31TransactionTest.kt, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep31RefundPayment.java, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep31Refunds.java, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep31Transaction.java, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep31TransactionStore.java, platform/src/test/kotlin/org/stellar/anchor/platform/data/JdbcSep31TransactionTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/service/TransactionServiceTest.kt
<details>
otherwise).
packages.
</details>
Merge release 1.2.1 to `main`
=> Release 1.2.1 merge to Main

CHANGELOG.md, build.gradle.kts, core/src/test/kotlin/org/stellar/anchor/sep10/Sep10ServiceTest.kt, core/src/test/kotlin/org/stellar/anchor/sep31/Sep31TransactionTest.kt, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep31RefundPayment.java, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep31Refunds.java, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep31Transaction.java, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep31TransactionStore.java, platform/src/test/kotlin/org/stellar/anchor/platform/data/JdbcSep31TransactionTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/service/TransactionServiceTest.kt
<details>
otherwise).
packages.
</details>
Merge release-1.2.1 to `develop`
N/A
N/A
=> Merge release-1.2.1 to `develop`

CHANGELOG.md, build.gradle.kts
<details>
otherwise).
packages.
</details>
Increased version from 1.2.1 to 1.2.2
Release preparation.
=> Increase version to 1.2.2

integration-tests/src/test/kotlin/org/stellar/anchor/platform/AnchorPlatformIntegrationTest.kt, integration-tests/src/test/kotlin/org/stellar/anchor/platform/ApiKeyAuthIntegrationTest.kt, integration-tests/src/test/kotlin/org/stellar/anchor/platform/SepTestSuite.kt, platform/src/main/java/org/stellar/anchor/platform/AnchorPlatformServer.java, platform/src/main/java/org/stellar/anchor/platform/ConfigManagementBeans.java, platform/src/main/java/org/stellar/anchor/platform/StellarObservingServer.java, platform/src/main/java/org/stellar/anchor/platform/config/PropertyAssetsConfig.java, platform/src/main/java/org/stellar/anchor/platform/configurator/ConfigManager.java, platform/src/main/java/org/stellar/anchor/platform/configurator/ObserverConfigManager.java, platform/src/main/java/org/stellar/anchor/platform/configurator/SepConfigManager.java, platform/src/main/java/org/stellar/anchor/platform/service/PropertyAssetsService.java, platform/src/main/resources/config/anchor-config-default-values.yaml, platform/src/main/resources/config/anchor-config-schema-v1.yaml, platform/src/test/kotlin/org/stellar/anchor/platform/configurator/ConfigManagerTest.kt, service-runner/src/main/java/org/stellar/anchor/platform/ServiceRunner.java
<details>
otherwise).
packages.
</details>
Clean up and simplify the way the Spring application are started.
Simplify the metrics port assignment. 
N/A
N/A
=> Clean up spring boot application startups

core/src/main/java/org/stellar/anchor/sep1/Sep1Service.java, core/src/test/kotlin/org/stellar/anchor/sep1/Sep1ServiceTest.kt, platform/src/main/java/org/stellar/anchor/platform/SepServiceBeans.java
<details>
otherwise).
packages.
</details>
Add Sep1Service tests
Better test coverage.
N/A
=> Add Sep1Service tests

core/src/main/java/org/stellar/anchor/sep1/Sep1Service.java, core/src/test/kotlin/org/stellar/anchor/sep1/Sep1ServiceTest.kt, docs/01 - Running & Configuring the Application/A - Running & Configuring the Application.md, platform/src/main/java/org/stellar/anchor/platform/AnchorPlatformServer.java
<details>
otherwise).
packages.
</details>
Fix the invalid JSON format in the readme file
N/A
N/A
=> Fix the invalid JSON format in the readme file

build.gradle.kts, core/src/test/kotlin/org/stellar/anchor/sep31/Sep31HelperTest.kt, core/src/test/kotlin/org/stellar/anchor/sep31/Sep31ServiceTest.kt, core/src/test/kotlin/org/stellar/anchor/sep38/Sep38ServiceTest.kt, gradle/libs.versions.toml, integration-tests/build.gradle.kts, integration-tests/src/main/kotlin/org/stellar/anchor/platform/SepClient.kt, integration-tests/src/test/kotlin/org/stellar/anchor/platform/AnchorPlatformIntegrationTest.kt, integration-tests/src/test/kotlin/org/stellar/anchor/platform/ApiKeyAuthIntegrationTest.kt, integration-tests/src/test/kotlin/org/stellar/anchor/platform/RestFeeIntegrationTest.kt, integration-tests/src/test/kotlin/org/stellar/anchor/platform/RestRateIntegrationTest.kt, platform/build.gradle.kts, platform/src/test/kotlin/org/stellar/anchor/Sep1ServiceTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/PaymentObserverBeansTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/callback/RestCustomerIntegrationTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/config/Sep1ConfigTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/data/JdbcSep31TransactionTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/service/TransactionServiceTest.kt
<details>
otherwise).
packages.
</details>
The following dependencies have some vulnerabilities and should be updated:
- h2database 1.4.200 → 2.1.214
- kotlin 1.6.20 → 1.7.20
- postgresql 42.4.1 → 42.5.0
- log4j and log4j-template-json 2.17.1 → 2.19.0
- jackson-dataformat-yaml 2.13.2 → 2.14.0
- spring-beans → org.springframework:spring-beans:5.3.20
- tomcat-embed-core: → org.apache.tomcat.embed:tomcat-embed-core: 9.0.63
- kotlin-scripting-jvm → org.jetbrains.kotlin:kotlin-scripting-jvm: 1.7.20
- spring-context → org.springframework:spring-context:5.3.20
- netty-common → io.netty:netty-common:4.1.77.Final
- aws-java-sdk-s3 → com.amazonaws:aws-java-sdk-core:1.12.342
- …
=> Upgraded library versions to avoid security vulnerability

anchor-reference-server/src/main/resources/anchor-reference-server-docker-compose-config.yaml, docker-compose.yaml, platform/src/main/resources/anchor-docker-compose-config.yaml
<details>
otherwise).
packages.
</details>
Fix root docker-compose file and related configs
N/A
Removed host.docker.internal from configs as was not be able to run platform with host in that format in configs (setting extra_hosts in compose didn't help)
=> Fix root compose and adjust configs

.github/workflows/end_to_end_tests.yml
<details>
otherwise).
packages.
</details>
Temporarily disable the broken e2e tests in the GH workflow until we have resource to fix it. 
To accelerate the development process until we have more resources.
=> Temporarily disable the e2e tests in the GH workflow

build.gradle.kts, scripts/pre-commit.sh
<details>
otherwise).
packages.
</details>
Fixed the Git hook `pre-commit.sh` script 
The script causes CONFLICTs when there are existing stash history.
N/A
=> Fix pre-commit git hook

api-schema/src/main/java/org/stellar/anchor/api/sep/sep24/TransactionResponse.java, core/src/main/java/org/stellar/anchor/sep24/Sep24Helper.java, core/src/test/kotlin/org/stellar/anchor/api/sep/sep24/Sep24DtoTests.kt
<details>
otherwise).
packages.
</details>
Fixed transaction response for SEP-24
Fields were set to empty strings unnecessarily
Should be merged after https://github.com/stellar/stellar-anchor-tests/pull/106
=> [ANCHOR-115] Fix SEP-24 schema

core/src/main/java/org/stellar/anchor/util/StringHelper.java, platform/src/main/java/org/stellar/anchor/platform/utils/RequestResponseMessage.java
<details>
otherwise).
packages.
</details>
Sanitize the request string written to log.
It can be dangerous if a malicious user supplies malformed string containing script code, new lines, etc, depending on how the log file is processed. 
N/A
=> all: [ANCHOR-21] Sanitize the request message to avoid scripting vulnerability

core/src/main/java/org/stellar/anchor/sep24/MoreInfoUrlConstructor.java, core/src/main/java/org/stellar/anchor/sep24/Sep24Helper.java, core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java, core/src/test/kotlin/org/stellar/anchor/sep24/Sep24ServiceTest.kt, platform/src/main/java/org/stellar/anchor/platform/component/sep/SepBeans.java, platform/src/main/java/org/stellar/anchor/platform/config/PropertySep24Config.java, platform/src/main/java/org/stellar/anchor/platform/service/SimpleInteractiveUrlConstructor.java, platform/src/main/java/org/stellar/anchor/platform/service/SimpleMoreInfoUrlConstructor.java, platform/src/main/resources/config/anchor-config-default-values.yaml, platform/src/main/resources/config/anchor-config-schema-v1.yaml, platform/src/test/kotlin/org/stellar/anchor/platform/config/Sep24ConfigTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/service/SimpleMoreInfoUrlConstructorTest.kt
<details>
otherwise).
packages.
</details>
- Add `more_info_url` configuration
- `MoreInfoUrlConstructor` and `SimpleMoreInfoUrlConstructor` classes
- Add Sep24Config validation tests
SEP-24 MVP.
N/A
=> all: [ANCHOR-121] Add more_info_url configuration and construction classes

api-schema/src/main/java/org/stellar/anchor/api/sep/sep24/TransactionResponse.java
<details>
otherwise).
packages.
</details>
[TODO or N/A]
=> [ANCHOR-116] Fix SEP-24 schema

anchor-reference-server/src/main/java/org/stellar/anchor/reference/event/AnchorEventProcessor.java, api-schema/src/main/java/org/stellar/anchor/api/sep/SepTransactionStatus.java, core/src/main/java/org/stellar/anchor/event/models/TransactionEvent.java, core/src/main/java/org/stellar/anchor/sep24/Sep24Helper.java, core/src/main/java/org/stellar/anchor/sep31/Sep31Helper.java, core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java, core/src/main/java/org/stellar/anchor/util/SepHelper.java, core/src/test/kotlin/org/stellar/anchor/sep31/Sep31ServiceTest.kt, core/src/test/kotlin/org/stellar/anchor/sep31/Sep31TransactionTest.kt, integration-tests/src/test/kotlin/org/stellar/anchor/platform/Sep31Tests.kt, platform/src/main/java/org/stellar/anchor/platform/service/MetricEmitterService.java, platform/src/main/java/org/stellar/anchor/platform/service/PaymentOperationToEventListener.java, platform/src/main/java/org/stellar/anchor/platform/service/TransactionService.java, platform/src/test/kotlin/org/stellar/anchor/platform/service/PaymentOperationToEventListenerTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/service/TransactionServiceTest.kt
<details>
otherwise).
packages.
</details>
Merge `class TransactionEvent.Status` with `class SepTransactionStatus`
These two classes are duplicates.
N/A
=> all: [ANCHOR-140] Merge TransactionEvent.Status with SepTransactionStatus

helm-charts/sep-service/example_values.yaml, helm-charts/sep-service/templates/configmap.yaml, helm-charts/sep-service/templates/deployment.yaml
This PR enables add custom labels to the deployment and the containers for sep service and payment observer service. it also enables the ability to define java options in values file for the helm chart to be included when the jar is executed.
=> custom labels and remove observer ingress

docs/03 - Implementing the Anchor Server/Communication/schemas.yml
<details>
otherwise).
packages.
</details>
1. Revise the PatchTransaction with the Transaction as the payload.
2. Add `sep` fields to the `Event` schema.
3. Add `sell_amount` and `buy_amount` to the `Quote` schema.
The patch endpoint is limited to some of the fields. This PR converts the `PATCH /transactions` endpoint to become omnipotent so that other AP components such as the observer may update the transactions without directly accessing the database. 
N/A
=> docs: Revised the PatchTransaction with the Transaction as the payload and minor changes to the Event and Quote schemas

CHANGELOG.md, build.gradle.kts
<details>
otherwise).
packages.
</details>
Increased version to 1.2.4
Release preparation
N/A
=> Bump version to 1.2.4

.gitignore, core/src/main/java/org/stellar/anchor/model/Sep24Transaction.java, core/src/main/java/org/stellar/anchor/model/Sep24TransactionBuilder.java, core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java, core/src/test/java/org/stellar/anchor/sep24/PojoSep24Transaction.java, data-spring-jdbc/src/main/java/org/stellar/anchor/server/data/JdbcSep24Transaction.java
<details>
otherwise).
packages.
</details>
Ports #730 to the `core-release-1.0` branch
MoneyGram uses the core release 1.0 branch instead of main.
N/A
=> SEP-24: add support for `refund_memo` withdraw request parameters

core/src/main/java/org/stellar/anchor/sep12/Sep12Service.java, core/src/test/kotlin/org/stellar/anchor/sep12/Sep12ServiceTest.kt, platform/src/main/java/org/stellar/anchor/platform/component/sep/SepBeans.java
<details>
otherwise).
packages.
</details>
Cherry-pick changes from #734
N/A
=> Update DETELE endpoint

CHANGELOG.md, build.gradle.kts
<details>
otherwise).
packages.
</details>
Increased version to 1.2.5
Release preparation
[TODO or N/A]
=> Version bump to 1.2.5

core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java, core/src/test/kotlin/org/stellar/anchor/sep24/Sep24ServiceTest.kt, platform/src/main/java/org/stellar/anchor/platform/controller/sep/Sep24Controller.java
<details>
otherwise).
packages.
</details>
Make account field optional in SEP24 withdraw and deposit
To reflect the SEP-24 change.
N/A
=> Make account field optional in SEP24 withdraw and deposit

.github/workflows/branch_develop.yml
<details>
otherwise).
packages.
</details>
[TODO or N/A]
=> Disable the test requirements for dockerhub push

CHANGELOG.md, build.gradle.kts, platform/src/main/resources/db/migration/V6__add_bank_account_type.sql
<details>
otherwise).
packages.
</details>
Bump version to 1.2.6
Release preparation (1.2.6)
N/A
=> Bump version to 1.2.6

CHANGELOG.md, anchor-reference-server/src/main/java/org/stellar/anchor/reference/model/Customer.java, anchor-reference-server/src/main/java/org/stellar/anchor/reference/service/CustomerService.java, api-schema/src/main/java/org/stellar/anchor/api/callback/PutCustomerRequest.java, api-schema/src/main/java/org/stellar/anchor/api/sep/sep12/Sep12PutCustomerRequest.java, build.gradle.kts, core/src/main/java/org/stellar/anchor/sep9/Sep9Fields.java, docs/03 - Implementing the Anchor Server/Communication/schemas.yml, end-to-end-tests/end_to_end_tests.py, integration-tests/src/test/kotlin/org/stellar/anchor/platform/AnchorPlatformIntegrationTest.kt, integration-tests/src/test/kotlin/org/stellar/anchor/platform/Sep12Tests.kt, integration-tests/src/test/kotlin/org/stellar/anchor/platform/Sep24Tests.kt, platform/src/main/resources/db/migration/V6__add_bank_account_type.sql, platform/src/test/resources/stellar-anchor-tests-sep-config.json
<details>
otherwise).
packages.
</details>
Cherry pick from release-1.2.6
This is to port the changes in `1.2.x` to `2.0.x`.
N/A
=> [ANCHOR-180] Cherry pick from release-1.2.6

core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java, core/src/main/java/org/stellar/anchor/sep24/Sep24Transaction.java, core/src/main/java/org/stellar/anchor/sep24/Sep24TransactionBuilder.java, core/src/test/java/org/stellar/anchor/sep24/PojoSep24Transaction.java, core/src/test/kotlin/org/stellar/anchor/auth/Sep10JwtTest.kt, core/src/test/kotlin/org/stellar/anchor/sep24/Sep24ServiceTest.kt, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep24Transaction.java
<details>
otherwise).
packages.
</details>
Add sep10AccountMemo in Sep24Service 
Bug fix
N/A
=> [ANCHOR-178] Add sep10AccountMemo in Sep24Service

Makefile, integration-tests/docker-compose-configs/anchor-platform-sep24-withdrawal/docker-compose-config.override.yaml, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep31Transaction.java, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSepTransaction.java, platform/src/main/java/org/stellar/anchor/platform/service/TransactionService.java, platform/src/main/resources/db/migration/V6__add_bank_account_type.sql, platform/src/main/resources/db/migration/V6__sep24_field_updates.sql
- generate db migration file
- add docker-compose sep24 e2e tests
=> [ANCHOR-148] Generate db migration file and add docker-compose sep24 e2e tests

anchor-reference-server/src/main/java/org/stellar/anchor/reference/event/AnchorEventProcessor.java, api-schema/src/main/java/org/stellar/anchor/api/platform/PlatformTransactionData.java, docs/03 - Implementing the Anchor Server/Communication/schemas.yml, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep24Transaction.java, platform/src/main/java/org/stellar/anchor/platform/service/TransactionService.java, platform/src/main/java/org/stellar/anchor/platform/utils/TransactionHelper.java, platform/src/main/resources/db/migration/V6__sep24_field_updates.sql, platform/src/test/kotlin/org/stellar/anchor/platform/service/TransactionServiceTest.kt
<details>
otherwise).
packages.
</details>
Change kycVerified to boolean and updated the `schemas.yml`
Bug fixes.
N/A
=> [ANCHOR-179] Change kycVerified to boolean and updated the schemas.yml

docker-compose/sep24/docker-compose.yaml, docker-compose/sep31/docker-compose.yaml, platform/src/main/resources/db/migration/V6__sep24_field_updates.sql
<details>
otherwise).
packages.
</details>
Fix database migration file of kyc_verified field
Bug fix
N/A
=> Fix database migration file of kyc_verified field

api-schema/src/main/java/org/stellar/anchor/api/platform/PlatformTransactionData.java, gradle/libs.versions.toml, integration-tests/src/test/resources/integration-test.anchor-config.yaml, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep24Transaction.java, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep31Transaction.java, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep38Quote.java, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSepTransaction.java, platform/src/main/java/org/stellar/anchor/platform/data/PaymentObservingAccount.java, platform/src/main/resources/db/migration/V6__sep24_field_updates.sql, platform/src/test/kotlin/org/stellar/anchor/platform/service/SimpleInteractiveUrlConstructorTest.kt
<details>
otherwise).
packages.
</details>
Fix sep10account_memo database field and lock the database column names.
Bug fixes.
N/A
=> [ANCHOR-183] Fix sep10account_memo database field and lock the database column names

CHANGELOG.md, build.gradle.kts, platform/src/main/java/org/stellar/anchor/platform/payment/observer/stellar/StellarPaymentObserver.java, platform/src/main/resources/anchor-config-defaults.yaml
<details>
otherwise).
packages.
</details>
Add database backoff timer to reconnect to database when the connection is lost
To improve the AP stability.
N/A
=> [ANCHOR-159] Add database backoff timer to reconnect to database when the connection is lost

.github/workflows/wf_pull_request.yml, .github/workflows/wf_release_created_or_updated.yml
<details>
otherwise).
packages.
</details>
Fix the release workflow
=> Fix the release workflow

CHANGELOG.md, anchor-reference-server/src/main/java/org/stellar/anchor/reference/controller/Sep24InteractiveController.java, build.gradle.kts
<details>
otherwise).
packages.
</details>
Change version to `2.0.0-preview-1`.
N/A
N/A
=> Change version to 2.0.0-preview-1

.github/workflows/wf_release_created_or_updated.yml
<details>
otherwise).
packages.
</details>
- Fix the release workflow that was failing
- Updated the docker login and docker build/push actions to avoid deprecation warnings.
- Add version checks to avoid accidental push of docker images.
- Avoid accidental push of docker images.
- Fix failing workflow.
N/A
=> [ANCHOR-192] Update the release workflow to publish to dockerhub with version checks

.run/v1.2 - Business  Server.run.xml, .run/v1.2 - Observer.run.xml, .run/v1.2 - Platform Server.run.xml, core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java
<details>
otherwise).
packages.
</details>
- [ANCHOR-193] Fix the bug where the result of deposit information not saved in database in SEP31
- Added IntelliJ `Run Configurations` for debugging version 1.2
Bug fix.
N/A
[ANCHOR-193]: https://stellarorg.atlassian.net/browse/ANCHOR-193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANCHOR-193] Fix the bug where the result of deposit information not saved in database in SEP31

.run/v1.2 - Business  Server.run.xml, .run/v1.2 - Observer.run.xml, .run/v1.2 - Platform Server.run.xml, CHANGELOG.md, build.gradle.kts, core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java
<details>
otherwise).
packages.
</details>
Fix the SEP-31 transaction not saved to database when deposit info is updated
Bug fix
N/A
=> Release 1.2.8

platform/src/main/java/org/stellar/anchor/platform/observer/stellar/StellarPaymentObserver.java, platform/src/main/java/org/stellar/anchor/platform/service/PaymentOperationToEventListener.java
<details>
otherwise).
packages.
</details>
Cherry pick the commit that implements the database backoff timer to improve the stability when the database connection is list
Improve the stability of the stellar payment observer
N/A
=> [ANCHOR-209] Cherry pick the database backoff timer to improve the stability when the database connection is list

kotlin-reference-server/src/main/kotlin/org/stellar/reference/sep24/DepositService.kt, platform/src/main/java/org/stellar/anchor/platform/service/TransactionService.java
<details>
otherwise).
packages.
</details>
* Add memo validation for PATCH
* On reference server set operation id instead of transaction id as the payment id
[TODO or N/A]
=> Small fixes

scripts/pre-commit.sh
<details>
otherwise).
packages.
</details>
Update git hook
You can't commit not formatted code anymore
[TODO or N/A]
=> [ANCHOR-223] Update git hook

integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/Sep24End2EndTests.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/plugins/Sep24TestRoute.kt
<details>
otherwise).
packages.
</details>
SEP-24 Withdrawal end-2-end tests.
Preparation for `2.0.0-rc1`
N/A
=> [ANCHOR-228] SEP-24 withdrawal e2e tests

build.gradle.kts
<details>
otherwise).
packages.
</details>
Change version label to 2.0.0-rc1
Release preparation.
N/A
=> Change version label to 2.0.0-rc1

CHANGELOG.md, platform/src/main/java/org/stellar/anchor/platform/service/TransactionService.java
<details>
otherwise).
packages.
</details>
Release 1.2.11
N/A
=> Release 1.2.11

build.gradle.kts
<details>
otherwise).
packages.
</details>
Fix version in Gradle from `2.0.0-rc-1` to `2.0.0-rc1`.
The CI requires the version `2.0.0-rc1` to match the release tag: `release-2.0.0-rc1`.
N/A
=> [Hotfix] Fix version in Gradle to `2.0.0-rc1`

build.gradle.kts
<details>
otherwise).
packages.
</details>
Change Gradle version label to 2.0.0-rc.1 
To be compliant with SemVer. https://semver.org/spec/v2.0.0-rc.1.html
N/A
=> Change Gradle version label to 2.0.0-rc.1

CHANGELOG.md, build.gradle.kts, core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java, core/src/test/kotlin/org/stellar/anchor/sep31/Sep31ServiceTest.kt
<details>
otherwise).
packages.
</details>
Don't set amount_out for indicative quote
Per request
N/A
=> [ANCHOR-240] Don't set amount_out for indicative quote

CHANGELOG.md, core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java, core/src/test/kotlin/org/stellar/anchor/sep31/Sep31ServiceTest.kt, platform/src/main/java/org/stellar/anchor/platform/service/TransactionService.java
<details>
otherwise).
packages.
</details>
Forward 1.2.10 and 1.2.11 changes
[TODO or N/A]
=> Forward 1.2.10, 1.2.11 and 1.2.12 changes

CHANGELOG.md, build.gradle.kts
<details>
otherwise).
packages.
</details>
Merge release-2.0.0-rc1 to develop
Release process
=> Merge release-2.0.0-rc1 to develop

platform/src/main/resources/config/anchor-config-default-values.yaml
<details>
otherwise).
packages.
</details>
Fix the comments of more_info_url and interactive_url
The comment was incorrect.
=> Fix the comments of more_info_url and interactive_url

.github/workflows/wf_release_created_or_updated.yml
<details>
otherwise).
packages.
</details>
Remove release prefix
Remove release prefix
[TODO or N/A]
=> Remove release prefix

.run/RunSEP24NoFrontend.run.xml, core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java, gradle/libs.versions.toml, integration-tests/build.gradle.kts, integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/Sep24End2EndTests.kt, service-runner/src/main/kotlin/org/stellar/anchor/platform/run_profiles/RunSEP24NoFrontend.kt
<details>
otherwise).
packages.
</details>
Support SEP asset format in the find transaction (`/transactions` endpoint) + add integration test
To offer better support
N/A
=> [ANCHOR-253] Support SEP asset format in find transactions + add tests

.run/Run - All Servers - no Docker.run.xml, .run/Run - All Servers - with Docker.run.xml
<details>
otherwise).
packages.
</details>
Fix IDEA run profile
With docker was not running with docker
[TODO or N/A]
=> Fix run profile

integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/Sep24End2EndTests.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/data/Data.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/jwt/Decoder.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/plugins/Sep24Route.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/plugins/Sep24TestRoute.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/sep24/DepositService.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/sep24/WithdrawalService.kt, platform/src/main/java/org/stellar/anchor/platform/service/TransactionService.java
<details>
otherwise).
packages.
</details>
Add amount validations in patch transactions
We need to validate if the asset is valid before it commits the transaction
=> [ANCHOR-161] Validate assets

core/src/main/java/org/stellar/anchor/config/SecretConfig.java, platform/src/main/java/org/stellar/anchor/platform/config/FireblocksConfig.java, platform/src/main/java/org/stellar/anchor/platform/config/PropertySecretConfig.java, platform/src/main/resources/config/anchor-config-default-values.yaml, platform/src/main/resources/config/anchor-config-schema-v1.yaml, platform/src/test/kotlin/org/stellar/anchor/platform/config/FireblocksConfigTest.kt
<details>
otherwise).
packages.
</details>
Add Fireblocks config
So we can enabled/disable Fireblocks custody service, configure Fireblocks client
N/A
=> platform: SDFSOF-17: Define Anchor template config for FB integration

kotlin-reference-server/src/main/kotlin/org/stellar/reference/plugins/Sep24Route.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/plugins/Sep24TestRoute.kt, platform/src/main/java/org/stellar/anchor/platform/CustodyServer.java, platform/src/main/java/org/stellar/anchor/platform/component/custody/ConfigBeans.java, platform/src/main/java/org/stellar/anchor/platform/configurator/CustodyConfigManager.java, platform/src/main/java/org/stellar/anchor/platform/configurator/SecretManager.java, platform/src/main/java/org/stellar/anchor/platform/service/TransactionService.java, platform/src/main/resources/config/anchor-config-default-values.yaml, platform/src/main/resources/config/anchor-config-schema-v1.yaml, service-runner/src/main/java/org/stellar/anchor/platform/ServiceRunner.java
<details>
otherwise).
packages.
</details>
Update Service Runner to start Custody server
So we can start Custody server component by passing appropriate Java command-line argument
N/A
=> platform: SDFSOF-20: Update runner for Custody component

platform/src/main/java/org/stellar/anchor/platform/CustodyServer.java, platform/src/main/java/org/stellar/anchor/platform/component/custody/FireblocksBeans.java, platform/src/main/java/org/stellar/anchor/platform/config/FireblocksConfig.java, platform/src/main/java/org/stellar/anchor/platform/job/FireblocksTransactionsReconciliationJob.java, platform/src/main/java/org/stellar/anchor/platform/job/ReconcileFireblocksTransactionsJob.java, platform/src/main/resources/config/anchor-config-default-values.yaml, platform/src/main/resources/config/anchor-config-schema-v1.yaml, platform/src/test/kotlin/org/stellar/anchor/platform/config/FireblocksConfigTest.kt
<details>
otherwise).
packages.
</details>
Added placeholder for transactions reconciliation scheduled job and corresponding property in yaml file to define cron expression
Transactions reconciliation scheduled job will be used to keep in sync transaction data in DB and Fireblocks
[N/A]
=> platform: SFFSOF-21: Implement cron job scheduler for FB updates

service-runner/src/main/java/org/stellar/anchor/platform/ServiceRunner.java
<details>
otherwise).
packages.
</details>
Pass empty env map to Kotlin Reference Server in Service Runner
So Kotlin Reference Server doesn't fail due to null env map
N/A
=> service-runner: SDFSOF-20: Investigate and create basic Fireblocks client

anchor-reference-server/src/main/java/org/stellar/anchor/reference/event/AnchorEventProcessor.java, api-schema/src/main/java/org/stellar/anchor/api/platform/PlatformTransactionData.java, kotlin-reference-server/src/main/kotlin/org/stellar/reference/data/Data.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/plugins/Sep24Route.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/plugins/Sep24TestRoute.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/sep24/DepositService.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/sep24/WithdrawalService.kt, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep24Transaction.java, platform/src/main/java/org/stellar/anchor/platform/service/PaymentOperationToEventListener.java, platform/src/main/java/org/stellar/anchor/platform/service/TransactionService.java, platform/src/main/java/org/stellar/anchor/platform/utils/TransactionHelper.java, platform/src/main/resources/db/migration/V6__sep24_field_updates.sql, platform/src/test/kotlin/org/stellar/anchor/platform/service/TransactionServiceTest.kt
<details>
otherwise).
packages.
</details>
1. Remove kycVerified 
2. Update transferReceivedAt only for SEP-31
3. Remove custodialTransactionId
1. Not used 
2. Was only used by SEP-31
3. Not used
N/A
=> Cleanup transaction schema

platform/src/main/java/org/stellar/anchor/platform/service/TransactionService.java, platform/src/test/kotlin/org/stellar/anchor/platform/service/TransactionServiceTest.kt, platform/src/test/resources/test_assets.json
<details>
otherwise).
packages.
</details>
Add significant decimal validation for PATCH
To prevent invalid updates
N/A
=> Validate significant decimals

core/src/main/java/org/stellar/anchor/config/SecretConfig.java, platform/src/main/java/org/stellar/anchor/platform/CustodyServer.java, platform/src/main/java/org/stellar/anchor/platform/component/custody/ConfigBeans.java, platform/src/main/java/org/stellar/anchor/platform/component/custody/FireblocksBeans.java, platform/src/main/java/org/stellar/anchor/platform/config/CustodySecretConfig.java, platform/src/main/java/org/stellar/anchor/platform/config/FireblocksConfig.java, platform/src/main/java/org/stellar/anchor/platform/config/PropertyCustodySecretConfig.java, platform/src/main/java/org/stellar/anchor/platform/config/PropertySecretConfig.java, platform/src/main/java/org/stellar/anchor/platform/configurator/SecretManager.java, platform/src/main/java/org/stellar/anchor/platform/custody/service/FireblocksEventsService.java, platform/src/main/java/org/stellar/anchor/platform/utils/RSAUtil.java, platform/src/main/resources/config/anchor-config-default-values.yaml, platform/src/test/kotlin/org/stellar/anchor/platform/config/FireblocksConfigTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/custody/service/FireblocksEventsServiceTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/util/RSAUtilTest.kt, service-runner/src/main/java/org/stellar/anchor/platform/ServiceRunner.java
<details>
otherwise).
packages.
</details>
Refactor code and fix issues after PR review
So we can merge our changes to main softserve_develop branch
[TODO or N/A]
=> platform: Refactor code and fix issues after PR review

kotlin-reference-server/src/main/kotlin/org/stellar/reference/plugins/Sep24Route.kt, service-runner/src/main/java/org/stellar/anchor/platform/ServiceRunner.java
<details>
otherwise).
packages.
</details>
Revert removal of stellar asset prefix for deposit and withdrawal
Fix was created only for development purposes
[TODO or N/A]
=> kotlin-reference-server: Revert removal of stellar asset prefix for deposit and withdrawal

platform/src/main/java/org/stellar/anchor/platform/component/custody/ConfigBeans.java, platform/src/main/java/org/stellar/anchor/platform/config/FireblocksConfig.java, platform/src/main/java/org/stellar/anchor/platform/custody/service/FireblocksEventsService.java, platform/src/test/kotlin/org/stellar/anchor/platform/custody/service/FireblocksEventsServiceTest.kt
<details>
otherwise).
packages.
</details>
Fix PR comments
So we can merge our changes to main softserve_develop branch
[TODO or N/A]
=> platform: Fix PR comment

api-schema/src/main/java/org/stellar/anchor/api/platform/TransactionsSeps.java, core/src/main/java/org/stellar/anchor/apiclient/PlatformApiClient.java
<details>
otherwise).
packages.
</details>
[TODO or N/A]
=> Rename SEP query param values

CHANGELOG.md, core/src/main/java/org/stellar/anchor/util/SepHelper.java, platform/src/main/java/org/stellar/anchor/platform/service/TransactionService.java
<details>
otherwise).
packages.
</details>
[ANCHOR-273] Forward changes from #871 
[TODO or N/A]
[ANCHOR-273]: https://stellarorg.atlassian.net/browse/ANCHOR-273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Allow zero fees [develop]

anchor-reference-server/src/main/java/org/stellar/anchor/reference/model/Quote.java, anchor-reference-server/src/main/java/org/stellar/anchor/reference/service/RateService.java, api-schema/src/main/java/org/stellar/anchor/api/callback/GetRateRequest.java, api-schema/src/main/java/org/stellar/anchor/api/callback/GetRateResponse.java, core/src/main/java/org/stellar/anchor/sep38/Sep38Service.java, core/src/test/kotlin/org/stellar/anchor/asset/DefaultAssetServiceTest.kt, core/src/test/kotlin/org/stellar/anchor/sep38/Sep38ServiceTest.kt, core/src/test/resources/test_assets.json, core/src/test/resources/test_assets.yaml, integration-tests/src/test/kotlin/org/stellar/anchor/platform/ApiKeyAuthIntegrationTest.kt, integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/CallbackApiTests.kt, integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/Sep31Tests.kt, platform/src/main/java/org/stellar/anchor/platform/callback/RestRateIntegration.java, service-runner/src/main/resources/config/assets.yaml
<details>
otherwise).
packages.
</details>
Update `/rate` callback according to https://github.com/stellar/stellar-docs/pull/136
Improve UX
Rounding logic is not finalized yet
=> [ANCHOR-269] Update GET /rate callback

core/src/main/java/org/stellar/anchor/util/StringHelper.java
<details>
otherwise).
packages.
</details>
Remove the encoding from requests logs
Make the log better to read
N/A
=> [ANCHOR-262] Fix: print log without encoding

CHANGELOG.md, core/build.gradle.kts, core/src/main/java/org/stellar/anchor/dto/sep24/TransactionResponse.java, core/src/main/java/org/stellar/anchor/sep10/JwtService.java, core/src/main/java/org/stellar/anchor/sep10/JwtToken.java, core/src/main/java/org/stellar/anchor/sep10/Sep10Service.java, core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java, core/src/test/kotlin/org/stellar/anchor/filter/Sep10TokenFilterTest.kt, core/src/test/kotlin/org/stellar/anchor/sep10/JwtServiceTest.kt, core/src/test/kotlin/org/stellar/anchor/sep24/Sep24ServiceTest.kt, gradle/wrapper/gradle-wrapper.properties
<details>
otherwise).
packages.
</details>
[TODO or N/A]
=> Add new field to the JWT token

core/src/main/java/org/stellar/anchor/config/CustodyConfig.java, core/src/main/java/org/stellar/anchor/custody/CustodyService.java, core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java, core/src/test/kotlin/org/stellar/anchor/sep31/Sep31ServiceTest.kt, platform/src/main/java/org/stellar/anchor/platform/component/custody/CustodyBeans.java, platform/src/main/java/org/stellar/anchor/platform/component/custody/FireblocksBeans.java, platform/src/main/java/org/stellar/anchor/platform/component/sep/CustodyApiBeans.java, platform/src/main/java/org/stellar/anchor/platform/component/sep/PlatformApiBeans.java, platform/src/main/java/org/stellar/anchor/platform/component/sep/SepBeans.java, platform/src/main/java/org/stellar/anchor/platform/component/share/SharedConfigBeans.java, platform/src/main/java/org/stellar/anchor/platform/config/CustodyApiConfig.java, platform/src/main/java/org/stellar/anchor/platform/config/HttpClientConfig.java, platform/src/main/java/org/stellar/anchor/platform/config/PropertyCustodyConfig.java, platform/src/main/java/org/stellar/anchor/platform/service/CustodyServiceImpl.java, platform/src/main/java/org/stellar/anchor/platform/service/TransactionService.java, platform/src/main/resources/config/anchor-config-default-values.yaml, platform/src/main/resources/config/anchor-config-schema-v1.yaml, platform/src/test/kotlin/org/stellar/anchor/platform/config/CustodyConfigTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/service/CustodyServiceTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/service/TransactionServiceTest.kt, platform/src/test/kotlin/org/stellar/anchor/sep31/Sep31DepositInfoGeneratorTest.kt
<details>
otherwise).
packages.
</details>
Fix PR comments
So we can merge our changes to main softserve_develop branch
[TODO or N/A]
=> platform: Fix PR comments

build.gradle.kts
<details>
otherwise).
packages.
</details>
Fix the pre-commit register Gradle task that fails on Windows
Bug fix
=> Fix the pre-commit register Gradle task that fails on Windows

build.gradle.kts
<details>
otherwise).
packages.
</details>
Update version to 2.0.0
Release 2.0.0 preparation.
=> Update version to 2.0.0

build.gradle.kts
<details>
Merge release 2.0.0 to `develop` branch.
=> Merge release 2.0.0 to develop branch

platform/src/main/java/org/stellar/anchor/platform/component/custody/FireblocksBeans.java, platform/src/main/java/org/stellar/anchor/platform/custody/CustodyPaymentService.java, platform/src/main/java/org/stellar/anchor/platform/custody/CustodyTransactionService.java, platform/src/main/java/org/stellar/anchor/platform/custody/fireblocks/FireblocksPaymentService.java, platform/src/main/java/org/stellar/anchor/platform/job/FireblocksTransactionsReconciliationJob.java, platform/src/test/kotlin/org/stellar/anchor/platform/custody/CustodyTransactionServiceTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/job/FireblocksTransactionsReconciliationJobTest.kt
<details>
otherwise).
packages.
</details>
Made getTransactionById and getTransactionsByTimeRange methods of CustodyPaymentService generic
CustodyPaymentService should be generic and sholdn't depend on custody implementation
=> custody-server: SDFSOF-25: Refactoring

core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java, core/src/main/java/org/stellar/anchor/util/SepHelper.java, integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/Sep24Tests.kt, integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/Sep31Tests.kt, service-runner/src/main/resources/config/assets.yaml
<details>
otherwise).
packages.
</details>
Check for assets min and max before validate request's amount limits
To avoid NPE when assets min and max are not set
N/A
=> [ANCHOR-263] Fix: check for asset min and max amount

core/build.gradle.kts, core/src/main/java/org/stellar/anchor/sep10/JwtToken.java, core/src/test/kotlin/org/stellar/anchor/sep10/JwtServiceTest.kt
<details>
otherwise).
packages.
</details>
[ANCHOR-284] Quickfix of requestedAccount not properly set
[TODO or N/A]
[ANCHOR-284]: https://stellarorg.atlassian.net/browse/ANCHOR-284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Mgi quickfix

docs/00 - Stellar Anchor Platform.md
<details>
otherwise).
packages.
</details>
Merge release/2.0.1 back to develop
=> Merge release/2.0.1 back to develop

core/src/main/java/org/stellar/anchor/sep38/Sep38Service.java
<details>
otherwise).
packages.
</details>
fix npe
fix npe
n/a
=> Fix NPE where the country code isn't specified in the sellAsset of Sep38Service

.github/ISSUE_TEMPLATE/release-a-new-version.md
<details>
otherwise).
packages.
</details>
Revised release-a-new-version.md to the Gitflow workflow.
Refer to: https://stellarfoundation.slack.com/archives/C02TPN2H65N/p1686605671225359
=> Revise release-a-new-version.md to the Gitflow workflow

build.gradle.kts, core/src/main/java/org/stellar/anchor/sep10/Sep10Service.java, docs/00 - Stellar Anchor Platform.md
<details>
otherwise).
packages.
</details>
Changes SEP-10 JWT token issuer from `web_auth_domain` to `https://web_auth_domain/auth`
Fixes issuer being set to web auth domain. In specification it must be a proper URL.  
N/A
=> Fix SEP-10 JWT issuer

platform/src/main/java/org/stellar/anchor/platform/service/SimpleInteractiveUrlConstructor.java, platform/src/test/kotlin/org/stellar/anchor/platform/service/SimpleInteractiveUrlConstructorTest.kt
<details>
otherwise).
packages.
</details>
Fix missing type field of the PutCustomerRequest in SEP-24 post transactions. 
Please also refer to: https://github.com/stellar/stellar-docs/pull/165#discussion_r1231301534
Bug fixes.
=> [ANCHOR-341] Fix missing type field of the PutCustomerRequest in SEP-24 post transactions

core/src/main/java/org/stellar/anchor/sep10/Sep10Service.java
* Fix webauth domain being an issuer
* Update version
<details>
otherwise).
packages.
</details>
Forward 2.0.2
Make branches up to date
N/A
=> [Forward to develop] v2.0.2

platform/src/main/java/org/stellar/anchor/platform/controller/platform/PlatformHealthController.java
<details>
otherwise).
packages.
</details>
Add platform health controller
Missing health endpoint on platform server
N/A
=> Add platform health controller

build.gradle.kts, docs/00 - Stellar Anchor Platform.md
<details>
otherwise).
packages.
</details>
Update version to 2.1.1
Prepare release of 2.1.1
N/A
=> Update version to 2.1.1

build.gradle.kts, docs/00 - Stellar Anchor Platform.md, platform/src/main/java/org/stellar/anchor/platform/controller/platform/PlatformHealthController.java
<details>
otherwise).
packages.
</details>
Release/2.1.1 -> main
Release/2.1.1 -> main
N/A
=> Release/2.1.1 -> main

build.gradle.kts, docs/00 - Stellar Anchor Platform.md, platform/src/main/java/org/stellar/anchor/platform/controller/platform/PlatformHealthController.java
<details>
otherwise).
packages.
</details>
Release/2.1.1 -> develop
Release/2.1.1 -> develop
N/A
=> Release/2.1.1 -> develop

api-schema/src/main/java/org/stellar/anchor/api/exception/RpcException.java, api-schema/src/main/java/org/stellar/anchor/api/exception/rpc/InternalErrorException.java, api-schema/src/main/java/org/stellar/anchor/api/exception/rpc/InvalidParamsException.java, api-schema/src/main/java/org/stellar/anchor/api/exception/rpc/InvalidRequestException.java, api-schema/src/main/java/org/stellar/anchor/api/exception/rpc/MethodNotFoundException.java, api-schema/src/main/java/org/stellar/anchor/api/rpc/RpcErrorCode.java, api-schema/src/main/java/org/stellar/anchor/api/rpc/RpcRequest.java, api-schema/src/main/java/org/stellar/anchor/api/rpc/RpcResponse.java, core/src/main/java/org/stellar/anchor/apiclient/PlatformApiClient.java, integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/PlatformApiTests.kt, platform/src/main/java/org/stellar/anchor/platform/component/platform/PlatformServerBeans.java, platform/src/main/java/org/stellar/anchor/platform/controller/platform/ActionController.java, platform/src/main/java/org/stellar/anchor/platform/service/ActionService.java, platform/src/main/java/org/stellar/anchor/platform/utils/RpcUtil.java, platform/src/test/kotlin/org/stellar/anchor/platform/service/ActionServiceTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/util/RpcUtilTest.kt
<details>
otherwise).
packages.
</details>
Implementation of endpoint for handling RPC calls with request validation and error handling
This endpoint will handle RPC calls that should replace PATCH /transactions REST endpoint
[TODO or N/A]
=> SDFSOF-63 - Added implementation of endpoint for handling RPC calls with corresponding request validation and basic error handling

integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/CustodyApiTests.kt, integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/SepHealthTests.kt, integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/StellarObserverTests.kt, platform/src/main/java/org/stellar/anchor/platform/action/NotifyRefundInitiatedHandler.java, platform/src/main/java/org/stellar/anchor/platform/action/NotifyRefundSentHandler.java, platform/src/test/kotlin/org/stellar/anchor/platform/action/NotifyRefundInitiatedHandlerTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/action/NotifyRefundSentHandlerTest.kt
<details>
otherwise).
packages.
</details>
Fixed issues with notify_refund_sent for cases when refund is missing, contains same/different id. Allow 0 for fee
[TODO or N/A]
=> SDFSOF-64 - Fixed issues with notify_refund_sent for cases when refund is missing, contains same/different id. Allow 0 for fee

api-schema/src/main/java/org/stellar/anchor/api/callback/SendEventRequest.java, api-schema/src/main/java/org/stellar/anchor/api/callback/SendEventResponse.java, core/src/main/java/org/stellar/anchor/apiclient/BaseApiClient.java, core/src/main/java/org/stellar/anchor/apiclient/CallbackApiClient.java, core/src/main/java/org/stellar/anchor/apiclient/PlatformApiClient.java, core/src/main/java/org/stellar/anchor/config/Sep10Config.java, core/src/main/java/org/stellar/anchor/event/EventService.java, core/src/main/java/org/stellar/anchor/sep10/Sep10Service.java, core/src/test/kotlin/org/stellar/anchor/sep10/Sep10ServiceTest.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/plugins/EventRoute.kt, platform/src/main/java/org/stellar/anchor/platform/component/sep/SepBeans.java, platform/src/main/java/org/stellar/anchor/platform/config/ClientsConfig.java, platform/src/main/java/org/stellar/anchor/platform/config/PropertySep10Config.java, platform/src/main/resources/config/anchor-config-default-values.yaml, platform/src/main/resources/config/anchor-config-schema-v1.yaml, platform/src/test/kotlin/org/stellar/anchor/platform/config/Sep10ConfigTest.kt
<details>
otherwise).
packages.
</details>
Migrate SEP-10 to use clients configuration 
Feature implementation
=> [ANCHOR-369] Migrate SEP-10 to use clients configuration

api-schema/src/main/java/org/stellar/anchor/api/rpc/action/ActionMethod.java, api-schema/src/main/java/org/stellar/anchor/api/rpc/action/NotifyOffchainFundsPendingRequest.java, platform/src/main/java/org/stellar/anchor/platform/action/NotifyOffchainFundsPendingHandler.java, platform/src/main/java/org/stellar/anchor/platform/action/NotifyOffchainFundsSentHandler.java, platform/src/test/kotlin/org/stellar/anchor/platform/action/NotifyOffchainFundsPendingHandlerTest.kt
<details>
otherwise).
packages.
</details>
`notify_offchain_fuds_pending` action
We should have additional intermediate action between `pending_anchor` and `completed`
[TODO or N/A]
=> SDFSOF-107: Implement notify_offchain_fuds_pending

integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/PlatformApiTests.kt, platform/src/main/java/org/stellar/anchor/platform/action/NotifyInteractiveFlowCompletedHandler.java, platform/src/main/java/org/stellar/anchor/platform/action/RequestOffchainFundsHandler.java, platform/src/main/java/org/stellar/anchor/platform/action/RequestOnchainFundsHandler.java, platform/src/main/java/org/stellar/anchor/platform/utils/AssetValidationUtils.java, platform/src/test/kotlin/org/stellar/anchor/platform/action/NotifyInteractiveFlowCompletedHandlerTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/action/RequestOffchainFundsHandlerTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/action/RequestOnchainFundsHandlerTest.kt
<details>
otherwise).
packages.
</details>
Added validation for assets in actions
We should validate stellar/non-stellar assets for amount_in/amount_out/amount_fee
[TODO or N/A]
=> SDFSOF-119: Add validation of onchain and offchain asset

core/src/main/java/org/stellar/anchor/config/AppConfig.java, core/src/test/kotlin/org/stellar/anchor/TestConstants.kt, core/src/test/kotlin/org/stellar/anchor/sep10/Sep10ServiceTest.kt, core/src/test/kotlin/org/stellar/anchor/sep24/Sep24ServiceTest.kt, core/src/test/kotlin/org/stellar/anchor/sep31/Sep31ServiceTest.kt, core/src/test/kotlin/org/stellar/anchor/util/LogTest.kt, platform/src/main/java/org/stellar/anchor/platform/config/PropertyAppConfig.java, platform/src/main/resources/config/anchor-config-default-values.yaml, platform/src/main/resources/config/anchor-config-schema-v1.yaml, platform/src/test/kotlin/org/stellar/anchor/platform/config/AppConfigTest.kt
<details>
otherwise).
packages.
</details>
- Remove `network_pass_phrase`
- Refactor the `metrics` section
- Add `management_server_port` to `platform_server`, `event_processor`, and `payment_observer`
- Review and clean up the configuration comments.
=> [ANCHOR-371] Refactor the metrics configuration and the comments of the configuration file.

CHANGELOG.md, build.gradle.kts
<details>
otherwise).
packages.
</details>
Release 1.2.16
Fixes Kafka serialization bug. 
N/A
=> Release 1.2.16

core/src/main/java/org/stellar/anchor/custody/CustodyService.java, core/src/main/java/org/stellar/anchor/sep31/Sep31Refunds.java, platform/src/main/java/org/stellar/anchor/platform/action/DoStellarRefundHandler.java, platform/src/main/java/org/stellar/anchor/platform/action/NotifyRefundSentHandler.java, platform/src/main/java/org/stellar/anchor/platform/action/NotifyTransactionErrorHandler.java, platform/src/main/java/org/stellar/anchor/platform/action/NotifyTransactionExpiredHandler.java, platform/src/main/java/org/stellar/anchor/platform/action/NotifyTransactionRecoveryHandler.java, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep31RefundPayment.java, platform/src/main/java/org/stellar/anchor/platform/service/CustodyServiceImpl.java, platform/src/test/kotlin/org/stellar/anchor/platform/action/DoStellarRefundHandlerTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/action/NotifyRefundInitiatedHandlerTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/action/NotifyRefundSentHandlerTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/action/NotifyTransactionErrorHandlerTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/action/NotifyTransactionExpiredHandlerTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/action/NotifyTransactionRecoveryHandlerTest.kt
<details>
otherwise).
packages.
</details>
Updated actions to handle sep31 refunds and error handling
Replace PATCH /transactions used for SEP-31 flow
[TODO or N/A]
=> SDFSOF-92 - Updated actions to handle sep31 refunds and error handling

core/build.gradle.kts, core/src/main/java/org/stellar/anchor/sep10/Sep10Service.java
<details>
otherwise).
packages.
</details>
[TODO or N/A]
=> Improve logs for SEP10Service

platform/src/main/java/org/stellar/anchor/platform/config/ClientsConfig.java, platform/src/main/java/org/stellar/anchor/platform/service/SimpleInteractiveUrlConstructor.java, platform/src/main/resources/config/anchor-config-default-values.yaml, platform/src/test/kotlin/org/stellar/anchor/platform/configurator/ConfigManagerTest.kt, platform/src/test/resources/config/test_anchor_config.yaml, platform/src/test/resources/config/test_anchor_config_missing_version.yaml, service-runner/src/main/resources/profiles/sep24/config.env
<details>
otherwise).
packages.
</details>
- Add a unit test for ConfigManager that reads a config file successfully
- Add a unit test for ConfigManager that reads a config file without a version throws an exception.
A more friendly validation will be appreciated than an exception
=> [Anchor-407] Add unit tests for ConfigManager that reads a config file

build.gradle.kts, core/src/main/java/org/stellar/anchor/sep1/Sep1Service.java, core/src/main/java/org/stellar/anchor/util/NetUtil.java, core/src/main/java/org/stellar/anchor/util/Sep1Helper.java, core/src/test/kotlin/org/stellar/anchor/util/NetUtilTest.kt, docs/00 - Stellar Anchor Platform.md, platform/src/main/java/org/stellar/anchor/platform/config/PropertySep1Config.java, platform/src/main/java/org/stellar/anchor/platform/controller/sep/Sep1Controller.java, platform/src/test/kotlin/org/stellar/anchor/Sep1ServiceTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/LogAppenderTest.kt, service-runner/src/main/kotlin/org/stellar/anchor/platform/TestProfileRunner.kt
This PR backmerges
[[ANCHOR-403](https://stellarorg.atlassian.net/browse/ANCHOR-403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ) Prevent SSRF through SEP-1 TOML redirect (](https://github.com/stellar/java-stellar-anchor-sdk/commit/574e8c7bdaf4d91fb45c91d4076c514cedaa1f7c)https://github.com/stellar/java-stellar-anchor-sdk/pull/1043[)](https://github.com/stellar/java-stellar-anchor-sdk/commit/574e8c7bdaf4d91fb45c91d4076c514cedaa1f7c)
@[reecexlm](https://github.com/stellar/java-stellar-anchor-sdk/commits?author=reecexlm)
reecexlm committed 4 days ago
Commits on Aug 11, 2023
[ANCHOR-403 Obfuscate Exception in Sep1Helper instead of NetUtil (](https://github.com/stellar/java-stellar-anchor-sdk/commit/973f0de715834ff05ebdd67e7d59315374e67026)https: …
=> Anchor 403 backmerge to develop

.github/pull_request_template.md
Add default testing gradlew test to the Testing section
Improvement to speed up the PR creation.
NA
=> Add default testing `gradlew test` to the Testing section

platform/src/main/java/org/stellar/anchor/platform/utils/RequestLoggerFilter.java, platform/src/test/kotlin/org/stellar/anchor/platform/utils/RequestLoggerFilterTest.kt
Refactored the test to stabilize the test. 
=> [ANCHOR-410] Refactored the RequestLoggingFilterTest to stabilize the Gradle test

platform/src/main/java/org/stellar/anchor/platform/utils/RequestLoggerFilter.java, platform/src/test/kotlin/org/stellar/anchor/platform/utils/RequestLoggerFilterTest.kt
Sync `softserve-develop` with `develop`
To keep `softserve-develop` branch up to date
NA
=> Softserve develop sync

build.gradle.kts, docs/README.md
=> Release 2.2.2

CHANGELOG.md, build.gradle.kts
=> Release 1.2.17

platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep31TransactionRepo.java
Add @Param to the status function parameter to fix the Spring database error.
```
[java.lang.IllegalArgumentException:Either use @Param on all parameters except Pageable and Sort typed once, or none at all](https://stackoverflow.com/questions/43489490/java-lang-illegalargumentexceptioneither-use-param-on-all-parameters-except-pa)
```
=> [ANCHOR-440] Add @Param to the status function parameter

core/src/main/java/org/stellar/anchor/sep38/Sep38Service.java, platform/src/main/java/org/stellar/anchor/platform/controller/Sep38Controller.java
…es endpoints
Add `client_id` to callback API fee endpoint for SEP38 /price and /prices endpoints
Bug fix.
=> Add `client_id` to callback API fee endpoint for SEP38 /price and /prices endpoints

core/src/main/java/org/stellar/anchor/sep38/Sep38Service.java, platform/src/main/java/org/stellar/anchor/platform/controller/Sep38Controller.java
Reverts stellar/java-stellar-anchor-sdk#1108
=> Revert "Add `client_id` to callback API fee endpoint for SEP38 /price and /prices endpoints"

api-schema/src/main/java/org/stellar/anchor/api/sep/AssetInfo.java, api-schema/src/main/java/org/stellar/anchor/api/sep/sep6/GetWithdrawRequest.java, api-schema/src/main/java/org/stellar/anchor/api/sep/sep6/GetWithdrawResponse.java, api-schema/src/main/java/org/stellar/anchor/api/sep/sep6/Sep6Transaction.java, core/src/main/java/org/stellar/anchor/asset/AssetServiceValidator.java, core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java, core/src/main/java/org/stellar/anchor/sep6/Sep6Service.java, core/src/main/java/org/stellar/anchor/sep6/Sep6TransactionStore.java, core/src/main/java/org/stellar/anchor/util/TransactionHelper.java, core/src/test/kotlin/org/stellar/anchor/sep6/Sep6ServiceTest.kt, integration-tests/src/main/kotlin/org/stellar/anchor/platform/Sep6Client.kt, integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/Sep6End2EndTest.kt, integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/Sep6Tests.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/processor/Sep6EventProcessor.kt, platform/src/main/java/org/stellar/anchor/platform/component/observer/PaymentObserverBeans.java, platform/src/main/java/org/stellar/anchor/platform/component/sep/SepBeans.java, platform/src/main/java/org/stellar/anchor/platform/controller/sep/Sep6Controller.java, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep24Transaction.java, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep6Transaction.java, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep6TransactionRepo.java, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep6TransactionStore.java, platform/src/main/java/org/stellar/anchor/platform/service/PaymentOperationToEventListener.java, platform/src/main/java/org/stellar/anchor/platform/service/TransactionService.java, platform/src/test/kotlin/org/stellar/anchor/platform/service/PaymentOperationToEventListenerTest.kt
This PR implements the GET `/withdraw` endpoint and the reference server implementation so that the E2E tests pass. It also includes minor refactoring to the payment observer.
SEP-6 implementation.
N/A
=> [ANCHOR-356] SEP-6: Implement withdraw

docs/diagrams/sep6/withdraw.md
This adds a diagram illustrating the withdraw flow in an Anchor Platform deployment.
[Rendered](https://github.com/philipliu/java-stellar-anchor-sdk/blob/feature/sep-6-withdraw-diagram/docs/diagrams/sep6/withdraw.md)
Knowledge sharing.
N/A
N/A
=> SEP-6: Add withdraw diagram

anchor-reference-server/build.gradle.kts, core/build.gradle.kts, integration-tests/build.gradle.kts, platform/build.gradle.kts
=> Replace Java Stellar SDK thin JAR with uber JAR

anchor-reference-server/build.gradle.kts, build.gradle.kts, docs/README.md, integration-tests/build.gradle.kts, kotlin-reference-server/build.gradle.kts, platform/build.gradle.kts, wallet-reference-server/build.gradle.kts
Replace Java Stellar SDK thin JAR with uber JAR.
For release `2.2.4`
=> Release 2.2.4 - Replace Java Stellar SDK thin JAR with uber JAR

api-schema/src/main/java/org/stellar/anchor/api/sep/sep6/InfoResponse.java, core/src/main/java/org/stellar/anchor/sep6/Sep6Service.java, core/src/test/kotlin/org/stellar/anchor/sep6/Sep6ServiceTest.kt
This fixes the response returned by GET `/info`.
This was discovered after enabling the SEP-6 test suite in `stellar-anchor-tests`.
- `stellar-anchor-tests`
N/A
=> [ANCHOR-353] SEP-6: Fix info response

anchor-reference-server/build.gradle.kts, build.gradle.kts, docs/README.md, integration-tests/build.gradle.kts, kotlin-reference-server/build.gradle.kts, platform/build.gradle.kts, wallet-reference-server/build.gradle.kts
Reverts stellar/java-stellar-anchor-sdk#1122
=> Revert "Release 2.2.4 - Replace Java Stellar SDK thin JAR with uber JAR"

.github/workflows/sub_gradle_test_and_build.yml, .github/workflows/wf_pull_request.yml
Choose PR action runner: `ubuntu-latest-16-cores`.
Improve the PR CI speed. If this causes GH instance issue, we will revert.
=> Choose PR action runner: ubuntu-latest-16-cores.

core/src/main/java/org/stellar/anchor/util/MemoHelper.java, core/src/test/kotlin/org/stellar/anchor/util/MemoHelperTest.kt
[ANCHOR-490] Add MEMO_RETURN support 
Bug fix
- TODO: replace with any additional test steps
[ANCHOR-490]: https://stellarorg.atlassian.net/browse/ANCHOR-490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANCHOR-490] Add MEMO_RETURN support

core/src/main/java/org/stellar/anchor/sep10/ISep10Service.java, core/src/main/java/org/stellar/anchor/sep10/Sep10Service.java, core/src/test/kotlin/org/stellar/anchor/sep10/Sep10ServiceTest.kt
- Restructure Sep1 service functions for extensibility and customizability.
Core SDK release.
=> [ANCHOR-498] Restructure Sep10Service functions for extensibility and customizability

.github/pull_request_template.md
Change PR template to account for documentation changes
=> Update PR template to account for documentation

build.gradle.kts, docs/README.md
Merge `release/2.4.0` into `develop`
Git flow
N/A
N/A
=> [Chore] Merge `release/2.4.0` into `develop`

essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/PlatformApiTests.kt
This adds tests for the SEP-6 flows.
Reviewing test coverage for SEP-6.
N/A
N/A
=> [ANCHOR-354] Add SEP-6 RPC flow tests

build.gradle.kts, docs/README.md
Bumps the version numbers to 2.5.0.
2.5.0 release
=> Merge `release/2.5.0` into `develop`

build.gradle.kts, docs/README.md, platform/src/main/java/org/stellar/anchor/platform/component/sep/SepBeans.java
This merges `main` into `develop`
Git flow
N/A
N/A
=> [Chore] Merge 2.5.1 to develop

core/build.gradle.kts, core/src/main/java/org/stellar/anchor/sep10/JwtToken.java, core/src/main/java/org/stellar/anchor/sep10/Sep10Service.java, core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java, payment-circle/build.gradle.kts, payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/StellarReconciliation.java, payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/model/CirclePayout.java, payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/model/CircleTransfer.java, payment-circle/src/test/kotlin/org/stellar/anchor/paymentservice/circle/CirclePaymentServiceTest.kt, platform/build.gradle.kts, settings.gradle.kts
Bump java SDK version in legacy 1.0
Using the latest Java SDK
N/A
N/A
=> [PARTNER-218] Bump java SDK version in legacy 1.0

build.gradle.kts, platform/src/main/java/org/stellar/anchor/platform/payment/observer/stellar/StellarPaymentObserver.java
Increase stream reconnect timeout and silence reconnect exception
=> Increase restart timeout

service-runner/src/main/java/org/stellar/anchor/platform/ServiceRunner.java, service-runner/src/main/kotlin/org/stellar/anchor/platform/TestProfileRunner.kt
Add log for running servers
Moving the duplicate log in TestProfileRunner to ServiceRunner
- build -> java -jar service-runner/build/libs/anchor-platform-runner-*.jar -a
=> [ANCHOR-528] Add log for running servers

build.gradle.kts, docs/README.md, service-runner/src/main/resources/version-info.properties
Merge release/2.6.1 to develop
Gitflow
=> [CHORE] Merge release/2.6.1 to develop

.github/ISSUE_TEMPLATE/release-a-new-version.md
Fix the new release issue template typo
Improvement
=> [CHORE] Fix the new release issue template typo

core/build.gradle.kts, core/src/main/java/org/stellar/anchor/sep10/Sep10Service.java
Improve error messages on toml read exception 
Requested by the partner
N/A
N/A
N/A
=> [Legacy 1.0] PARTNER-296: Improve toml read error message

helm-charts/reference-server/templates/configmap.yaml, helm-charts/reference-server/templates/deployment.yaml, helm-charts/reference-server/values.yaml, helm-charts/sep-service/templates/eventprocessor-deployment.yaml, helm-charts/sep-service/templates/sepserver-deployment.yaml, helm-charts/sep-service/values.yaml
This parameterizes the URLs in the reference server config.
These need to be parameterized for deployment.
- Testing with demo wallet
N/A
N/A
=> [ANCHOR-605] Move some config into values file

api-schema/src/main/java/org/stellar/anchor/api/callback/PutCustomerRequest.java, api-schema/src/main/java/org/stellar/anchor/api/sep/sep12/ProvidedField.java, api-schema/src/main/java/org/stellar/anchor/api/sep/sep12/ProvidedFieldStatus.java, api-schema/src/main/java/org/stellar/anchor/api/sep/sep12/Sep12PutCustomerRequest.java, core/src/main/java/org/stellar/anchor/sep10/Sep10Helper.java, core/src/test/kotlin/org/stellar/anchor/sep12/Sep12ServiceTest.kt, essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/EventProcessingTests.kt, essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/Sep12Tests.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/callbacks/customer/CustomerService.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/model/Customer.kt, platform/src/main/java/org/stellar/anchor/platform/config/PropertySep10Config.java, platform/src/main/resources/config/anchor-config-default-values.yaml, platform/src/main/resources/config/anchor-config-schema-v1.yaml, platform/src/main/resources/example.anchor-config.yaml, platform/src/test/kotlin/org/stellar/anchor/platform/config/Sep10ConfigTest.kt, service-runner/build.gradle.kts, service-runner/src/main/resources/profiles/host-docker-internal/config.env
- hardcode the verification fields
- fix some tests
=> [ANCHOR-582] Add verification fields to sep12

platform/src/main/java/org/stellar/anchor/platform/rpc/RequestOnchainFundsHandler.java, platform/src/test/kotlin/org/stellar/anchor/platform/rpc/RequestOnchainFundsHandlerTest.kt
Improve error message
Current error message doesn't explain misconfiguration
N/A
N/A
N/A
=> Improve error message

platform/src/main/java/org/stellar/anchor/platform/utils/RequestLoggerFilter.java
Add access log at INFO level to capture ip address
- screenshot:
=> [ANCHOR-623] Add access log to capture ip address

.github/workflows/sub_codeql_analysis.yml
- Updated workflow file for running code scanning through CodeQL on pull requests and pushes to develop branch.
- CodeQL scanning wasn't working correctly
=> update CodeQL config

docs/01 - Contributing/E - Github Workflows.md
Update README to access the workflow test results
Improve the documentation.
N/A
N/A
=> [CHORE] Update README to access the workflow test results

core/src/main/java/org/stellar/anchor/util/MetricConstants.java
This fixes the metric name.
N/A
N/A
N/A
=> Fix SEP-31 transaction created metric

api-schema/src/main/java/org/stellar/anchor/api/callback/GetCustomerRequest.java, api-schema/src/main/java/org/stellar/anchor/api/callback/PutCustomerRequest.java, api-schema/src/main/java/org/stellar/anchor/api/sep/sep12/Sep12GetCustomerRequest.java, api-schema/src/main/java/org/stellar/anchor/api/sep/sep12/Sep12PutCustomerRequest.java, extended-tests/src/test/kotlin/org/stellar/anchor/platform/extendedtest/custody/CustodyApiTests.kt, extended-tests/src/test/kotlin/org/stellar/anchor/platform/extendedtest/custody/PlatformApiCustodyTests.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/callbacks/customer/CustomerService.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/dao/TransactionKYCRepository.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/dao/TransactionKYCs.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/di/ServiceContainer.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/model/TransactionKYC.kt, service-runner/src/main/resources/common/docker-compose.yaml, service-runner/src/main/resources/docker-compose-test.yaml, service-runner/src/main/resources/docker-compose.yaml
=> [CHORE] Merge `develop` into `feature/v3`

essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/PlatformApiTests.kt
This commit updates the test case data to re-enable the RPC tests.
Test coverage improvement. 
N/A
N/A
=> [ANCHOR-693] Re-enable RPC tests

kotlin-reference-server/src/main/kotlin/org/stellar/reference/callbacks/customer/CustomerService.kt
This commit fixes the customer callback endpoints behavior when the `transaction_id` is included in the request.
Previously, the `transaction_id` was ignored.
- Testing with demo wallet.
N/A
N/A
=> [Fix] Persist customer record when transaction_id is used

build.gradle.kts, docs/README.md, service-runner/src/main/resources/version-info.properties
We are releasing 2.8.1 with the SEP-6 fixes.
2.8.1 release.
N/A
N/A
=> Bump version number

build.gradle.kts, docs/README.md, service-runner/src/main/resources/version-info.properties
This bumps the version to 2.8.2
New release
N/A
N/A
=> [Chore] Bump version number

build.gradle.kts, core/build.gradle.kts, gradle/libs.versions.toml, kotlin-reference-server/src/main/kotlin/org/stellar/reference/ReferenceServer.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/callbacks/customer/CustomerService.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/EventConsumer.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/EventService.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/processor/AnchorEventProcessor.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/processor/Sep6EventProcessor.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/plugins/RequestExceptionHandlerPlugin.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/plugins/RequestLoggerPlugin.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/sep24/DepositService.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/sep24/Sep24Route.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/sep24/Sep24TestRoute.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/sep24/WithdrawalService.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/sep31/ReceiveService.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/sep31/Sep31TestRoute.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/service/SepHelper.kt, platform/build.gradle.kts, platform/src/main/java/org/stellar/anchor/platform/config/PropertyAppConfig.java, service-runner/build.gradle.kts, wallet-reference-server/build.gradle.kts, wallet-reference-server/src/main/kotlin/org/stellar/reference/wallet/WalletServer.kt
This PR upgrades most of the dependencies in the project. A follow-up PR will remove unused dependencies.
N/A
N/A
N/A
=> [ANCHOR-688] Upgrade dependencies

build.gradle.kts, docs/README.md, service-runner/src/main/resources/version-info.properties
Preparing for 2.8.3 release
N/A
N/A
N/A
=> Bump version number to 2.8.3

build.gradle.kts, core/src/main/java/org/stellar/anchor/apiclient/BaseApiClient.java, core/src/main/java/org/stellar/anchor/apiclient/CallbackApiClient.java, core/src/main/java/org/stellar/anchor/apiclient/PlatformApiClient.java, docs/README.md, service-runner/src/main/resources/version-info.properties
=> Release 2.8.3 -> main

build.gradle.kts, core/src/main/java/org/stellar/anchor/apiclient/BaseApiClient.java, core/src/main/java/org/stellar/anchor/apiclient/CallbackApiClient.java, core/src/main/java/org/stellar/anchor/apiclient/PlatformApiClient.java, docs/README.md, service-runner/src/main/resources/version-info.properties
=> [Chore] dev -> v3

build.gradle.kts, core/build.gradle.kts
Upgrade JDK-17 in legacy 1.x
Partner request
N/A
N/A
N/A
=> [PARTNER-312] Upgrade to jdk 17 in legacy core

core/build.gradle.kts, core/src/main/java/org/stellar/anchor/dto/sep24/DepositTransactionResponse.java
Add ERROR status to more_info genetaror 
Partner request
N/A
N/A
=> Add ERROR to more_info

build.gradle.kts, docs/README.md, platform/src/main/java/org/stellar/anchor/platform/config/PropertySep10Config.java, service-runner/src/main/resources/version-info.properties
=> [Release 2.8.4] Main -> Develop

api-schema/src/main/java/org/stellar/anchor/api/sep/sep12/Sep12CustomerRequestBase.java, core/src/main/java/org/stellar/anchor/sep12/Sep12Service.java, core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java, essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/e2etest/Sep31End2EndTests.kt, essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/Sep31Tests.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/callbacks/customer/CustomerService.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/client/AnchorReferenceServerClient.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/data/Data.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/di/EventConsumerContainer.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/processor/AnchorEventProcessor.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/processor/Sep31EventProcessor.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/processor/Sep6EventProcessor.kt, platform/src/test/kotlin/org/stellar/anchor/platform/configurator/ConfigManagerTest.kt
This modify  SEP-12 Service  to support new KYC flow in SEP-31. 
It also updates the SEP-31 e2e test to use the new flow.
This is to support the protocol change of SEP-31.
N/A
N/A
=> [ANCHOR-737] Update SEP-31 test with new KYC flow

core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java, core/src/test/kotlin/org/stellar/anchor/sep31/Sep31ServiceTest.kt
Legacy of https://stellarorg.atlassian.net/browse/ANCHOR-737
This removes KYC verification from the SEP-31 transaction initiation
=> [SEP-31] Remove SEP-31 KYC verification

build.gradle.kts, docs/README.md, service-runner/src/main/resources/version-info.properties
Bump version to 2.9
2.9 release
N/A
N/A
=> [Chore] Bump version to 2.9

kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/processor/Sep6EventProcessor.kt
This fixes the call to `NotifyCustomerInfoUpdated`. When the customer does not exist prior to SEP-6 transaction creation, the reference server needs to create one so that the ID is passed to the RPC. Otherwise, the `NotifyCustomerInfoUpdated` to defaults setting the status to `PENDING_ANCHOR`.
Demo wallet fix.
- Tested deposit and withdrawal with demo wallet.
N/A
We need to add tests that mirror the demo wallet flow.
=> [ANCHOR-796] Fix NotifyCustomerInfoUpdated RPC call

kotlin-reference-server/src/main/kotlin/org/stellar/reference/callbacks/rate/RateService.kt
Add CAD->stellarUSDCprod conversion and re-order the conversion pairs
Improve reference server.
N/A
N/A
=> [CHORE] Add CAD->stellarUSDCprod conversion and re-order the conversion pairs

.run/Docker - Run Dev Stack - Kafka, Postgres, SEP24 Reference UI.run.xml
Fix the "Run Dev Stack" run config warning
Improvements.
N/A
N/A
=> [CHORE] Fix the "Run Dev Stack" run config warning

platform/src/main/resources/config/anchor-config-default-values.yaml
- Set app_logging.level default value to ERROR
- improvements
N/A
N/A
=> [ANCHOR-821] Set app_logging.level default value to ERROR

platform/src/main/java/org/stellar/anchor/platform/config/PropertyQueueConfig.java, platform/src/main/java/org/stellar/anchor/platform/event/KafkaSession.java, platform/src/main/java/org/stellar/anchor/platform/utils/ResourceHelper.java, platform/src/test/kotlin/org/stellar/anchor/platform/config/PropertyQueueConfigTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/config/ValidationHelper.kt
-Add the missing PropertyQueueConfig validations
- Improvements
N/A
N/A
=> [ANCHOR-824] Add the missing PropertyQueueConfig validations

build.gradle.kts, docs/README.md, service-runner/src/main/resources/version-info.properties
- Update version to 2.10.0
- Release preparation
N/A
N/A
=> [ANCHOR-825] Update version to 2.10.0

build.gradle.kts, docs/README.md, service-runner/src/main/resources/version-info.properties
Merge Release/2.10.0 to develop
Post release.
N/A
N/A
=> Merge Release/2.10.0 to develop

core/src/main/java/org/stellar/anchor/apiclient/BaseApiClient.java, essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/PlatformApiTests.kt, extended-tests/src/test/kotlin/org/stellar/anchor/platform/extendedtest/custody/CustodyApiTests.kt, extended-tests/src/test/kotlin/org/stellar/anchor/platform/extendedtest/custody/PlatformApiCustodyTests.kt, lib-util/src/main/java/org/stellar/anchor/util/NumberHelper.java, platform/src/main/java/org/stellar/anchor/platform/callback/RestRateIntegration.java, platform/src/test/kotlin/org/stellar/anchor/platform/callback/RestRateIntegrationTest.kt
As title
Unblock chipper when no fee is applied to transaction
=> [ANCHOR-829] Allow `rate.fee.total` to be zero

build.gradle.kts, docs/README.md, service-runner/src/main/resources/version-info.properties
=> Bump version 2.10.1

build.gradle.kts, docs/README.md, service-runner/src/main/resources/version-info.properties
Reverts stellar/java-stellar-anchor-sdk#1512
Accidentally merged to develop :(
=> Revert "Bump version 2.10.1"

build.gradle.kts, docs/README.md, service-runner/src/main/resources/version-info.properties
Merge `release/2.10.1` into `develop`
=> Merge `release/2.10.1` into `develop`

build.gradle.kts, docs/README.md, service-runner/src/main/resources/version-info.properties
Bump version to 2.10.2
Release preparation
N/A
N/A
=> Bump version to 2.10.2

api-schema/src/main/java/org/stellar/anchor/api/sep/sep12/Sep12CustomerRequestBase.java, api-schema/src/main/java/org/stellar/anchor/api/sep/sep12/Sep12GetCustomerRequest.java, api-schema/src/main/java/org/stellar/anchor/api/sep/sep12/Sep12PutCustomerRequest.java, build.gradle.kts, core/src/main/java/org/stellar/anchor/sep12/Sep12Service.java, core/src/test/kotlin/org/stellar/anchor/sep12/Sep12ServiceTest.kt, docs/README.md, kotlin-reference-server/src/main/kotlin/org/stellar/reference/sep24/Sep24TestRoute.kt, platform/src/main/java/org/stellar/anchor/platform/callback/PlatformIntegrationHelper.java, platform/src/main/java/org/stellar/anchor/platform/callback/RestRateIntegration.java, platform/src/main/java/org/stellar/anchor/platform/config/PropertyEventConfig.java, platform/src/main/java/org/stellar/anchor/platform/config/PropertyQueueConfig.java, platform/src/main/java/org/stellar/anchor/platform/event/KafkaSession.java, platform/src/main/java/org/stellar/anchor/platform/utils/ResourceHelper.java, platform/src/test/kotlin/org/stellar/anchor/platform/callback/RestRateIntegrationTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/config/EventConfigTest.kt, platform/src/test/kotlin/org/stellar/anchor/platform/config/PropertyQueueConfigTest.kt, service-runner/src/main/resources/version-info.properties
Merge 2.10.2 to main
Post release merge.
N/A
N/A
=> Merge 2.10.2 to main

helm-charts/reference-server/templates/configmap.yaml, helm-charts/reference-server/templates/deployment.yaml, helm-charts/reference-server/templates/ingress.yaml, helm-charts/reference-server/values.yaml, helm-charts/sep-service/values.yaml
Mainly 3.0 compatibility changes.
=> Update charts for demo

platform/src/main/java/org/stellar/anchor/platform/config/PropertyClientsConfig.java, platform/src/main/resources/config/anchor-client-default-values.yaml
It was agreed offline that we will not use prototype loading for the clients configuration, as this configuration is typically empty.
Thus only updating the default client configuration example to offer clearer guidance on how to set it correctly.
=> [ANCHOR-819] Update client config default value examples

build.gradle.kts, docs/README.md, service-runner/src/main/resources/version-info.properties
Merge Release/2.11.0 to `develop`
post release
N/A
N/A
=> Merge Release/2.11.0 to `develop`

api-schema/src/main/java/org/stellar/anchor/api/rpc/RpcRequest.java, api-schema/src/main/java/org/stellar/anchor/api/rpc/method/GetQuoteRpcRequest.java, api-schema/src/main/java/org/stellar/anchor/api/rpc/method/RpcMethod.java, build.gradle.kts, core/src/main/java/org/stellar/anchor/apiclient/PlatformApiClient.java, core/src/main/java/org/stellar/anchor/sep38/Sep38Helper.java, core/src/main/java/org/stellar/anchor/sep38/Sep38Service.java, core/src/test/kotlin/org/stellar/anchor/sep38/Sep38ServiceTest.kt, essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/PlatformApiTests.kt, platform/src/main/java/org/stellar/anchor/platform/component/platform/RpcActionBeans.java, platform/src/main/java/org/stellar/anchor/platform/rpc/GetQuoteHandler.java, platform/src/test/kotlin/org/stellar/anchor/platform/rpc/GetQuoteHandlerTest.kt
Implement platform Quote API
Feature implementation
Add `get_quote` RPC method.
N/A
=> [ANCHOR-728] Implement platform Quote API

build.gradle.kts, docs/README.md, service-runner/src/main/resources/version-info.properties
Merge `Release/2.11.1` to develop
post release
N/A
N/A
=> Merge Release/2.11.1 to develop 

.github/ISSUE_TEMPLATE/release-a-new-version.md
Add post message to the #release slack channel
Update release process.
NA
NA
=> [CHORE] Add post message to the #release slack channel

kotlin-reference-server/src/main/kotlin/org/stellar/reference/dao/CustomerRepository.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/dao/QuoteRepository.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/dao/TransactionKYCRepository.kt
This updates the reference server initialization to create new columns in the model but not in the database. It also updates the SELECT query builder to use the new method.
`customers.bank_name` does not exist, causing SEP-6 transactions to fail.
N/A
N/A
=> [ANCHOR-865] Add missing columns on ref server start

CHANGELOG.md, core/build.gradle.kts, settings.gradle.kts
Reduce java-stellar-sdk to 0.42.0
Bug fix
=> Reduce java-stellar-sdk to 0.42.0

core/build.gradle.kts, gradle/wrapper/gradle-wrapper.properties
Fix publication problem
Hot fix.
=> Fix publication problem

.github/workflows/sub_essential_tests.yml, build.gradle.kts, docs/README.md, platform/src/main/java/org/stellar/anchor/platform/configurator/DataConfigAdapter.java, platform/src/main/resources/config/anchor-config-default-values.yaml, platform/src/main/resources/config/anchor-config-schema-v1.yaml, service-runner/src/main/resources/profiles/default/config.env, service-runner/src/main/resources/version-info.properties
- Add `schema` configuration
- Bump version to `2.12.0`
- configuration improvemetns
N/A
N/A
=> [ANCHOR-592] Add schema to database configuration

.github/workflows/sub_essential_tests.yml, build.gradle.kts, docs/README.md, platform/src/main/java/org/stellar/anchor/platform/configurator/DataConfigAdapter.java, platform/src/main/resources/config/anchor-config-default-values.yaml, platform/src/main/resources/config/anchor-config-schema-v1.yaml, service-runner/src/main/resources/profiles/default/config.env, service-runner/src/main/resources/version-info.properties
- Merge `release/2.12.0` to `main`
- post `2.12.0` release
The `schema` configuration is added to `anchor-config-default-values`
N/A
=> [ANCHOR-592] Merge release/2.12.0 to `main`

build.gradle.kts, docs/README.md, service-runner/src/main/resources/version-info.properties
This back merge was missing during the 2.12 release
=> [CHORE] Merge main to develop 2.12

.github/workflows/on_release_created_or_updated.yml
=> Back merge Update on_release_created_or_updated.yml

helm-charts/sep-service/templates/sepserver-ingress.yaml
This updates how the headers are set to be compatible with the upstream ingress controller.
Deployments are broken with the new ingress controller.
N/A
N/A
=> [ANCHOR-931] Update custom headers in ingress resource

build.gradle.kts, core/src/main/java/org/stellar/anchor/util/AssetValidator.java, core/src/main/resources/config/anchor-asset-default-values.yaml, core/src/test/kotlin/org/stellar/anchor/asset/DefaultAssetServiceTest.kt, core/src/test/kotlin/org/stellar/anchor/dto/sep38/InfoResponseTest.kt, core/src/test/kotlin/org/stellar/anchor/sep38/Sep38ServiceTest.kt, core/src/test/resources/test_assets.json, core/src/test/resources/test_assets.yaml, docs/README.md, helm-charts/sep-service/values.yaml, platform/src/main/resources/example.anchor-config.yaml, platform/src/test/resources/test_assets.json, platform/src/test/resources/test_assets.yaml, platform/src/test/resources/test_sep38_get_info.json, service-runner/src/main/resources/config/assets.yaml, service-runner/src/main/resources/version-info.properties
Note this branch is cut from `main` to exclude changes unrelated to the patch
1. Merge to main and develop
2. Release note
3. Update stellar-doc about `country_code` getRate callback
4. Update SEP-0038 protocol example request to use 2-letter country code
=> Validate country codes and bump version

build.gradle.kts, core/src/main/java/org/stellar/anchor/util/AssetValidator.java, core/src/main/resources/config/anchor-asset-default-values.yaml, core/src/test/kotlin/org/stellar/anchor/asset/DefaultAssetServiceTest.kt, core/src/test/kotlin/org/stellar/anchor/dto/sep38/InfoResponseTest.kt, core/src/test/kotlin/org/stellar/anchor/sep38/Sep38ServiceTest.kt, core/src/test/resources/test_assets.json, core/src/test/resources/test_assets.yaml, docs/README.md, helm-charts/sep-service/values.yaml, platform/src/main/resources/example.anchor-config.yaml, platform/src/test/resources/test_assets.json, platform/src/test/resources/test_assets.yaml, platform/src/test/resources/test_sep38_get_info.json, service-runner/src/main/resources/config/assets.yaml, service-runner/src/main/resources/version-info.properties
Reverts stellar/anchor-platform#1611 
This override changes on develop
=> Revert "[CHORE] Merge `main` to `develop`"

build.gradle.kts, core/src/main/java/org/stellar/anchor/util/AssetValidator.java, core/src/main/resources/config/anchor-asset-default-values.yaml, core/src/test/kotlin/org/stellar/anchor/asset/DefaultAssetServiceTest.kt, core/src/test/kotlin/org/stellar/anchor/dto/sep38/InfoResponseTest.kt, core/src/test/kotlin/org/stellar/anchor/sep38/Sep38ServiceTest.kt, core/src/test/resources/test_assets.json, core/src/test/resources/test_assets.yaml, docs/README.md, helm-charts/sep-service/values.yaml, platform/src/main/java/org/stellar/anchor/platform/component/platform/PlatformServerBeans.java, platform/src/main/resources/example.anchor-config.yaml, platform/src/test/resources/test_assets.json, platform/src/test/resources/test_assets.yaml, platform/src/test/resources/test_sep38_get_info.json, service-runner/src/main/resources/config/assets.yaml
This is a re-submit of https://github.com/stellar/anchor-platform/pull/1609 as the original PR  was reverted as part of 3.0.1 release revertion
Cut release/3.0.1 from develop HEAD and merge it to main
Regenerate release note
=> [ANCHOR-936] Country code validation and bump version

service-runner/src/main/resources/version-info.properties
- Back merge 3.0.1 to `develop
- post release
NA
NA
=> Back merge `3.0.1` to `develop

.github/workflows/on_pull_request.yml, .github/workflows/on_push_to_develop.yml, .github/workflows/sub_rust_build.yml
This adds a workflow to build the `soroban` directory
We now have Rust code in the project, our CI should build and test against it.
N/A
N/A
N/A
=> Add Github action for Rust build

helm-charts/sep-service/values.yaml
- Update `sep24.more_info_url` config for local helm deployment
- Support sep24 flow.
N/A
N/A
=> [ANCHOR-924] Update sep24 more_info_url config

helm-charts/reference-server/templates/ingress.yaml, helm-charts/sep24-reference-ui/templates/ingress.yaml
As title 😭 
Tested with `helm template --debug --dry-run`
=> [PD] Fix indention

helm-charts/sep24-reference-ui/templates/ingress.yaml
=> fix annotation

helm-charts/reference-server/templates/ingress.yaml, helm-charts/sep24-reference-ui/templates/ingress.yaml
This was missing in ingress configuration.
=> [PD] Add ingress responseHeaders configMap

helm-charts/sep-service/values.yaml
=> [Fix] Update anchor usdc desc in helm chart

kotlin-reference-server/src/main/kotlin/org/stellar/reference/sep24/DepositService.kt
Fix reference server deposit flow did not apply fee.
- Tested with demo wallet that deposit 10 USDC and balance increased by 9
=> [ANCHOR-986][Fix] Fix reference server send out wrong sep24 deposit amount

core/src/main/java/org/stellar/anchor/config/AppConfig.java, platform/src/main/java/org/stellar/anchor/platform/config/PropertyAppConfig.java, platform/src/main/resources/config/anchor-config-default-values.yaml, platform/src/main/resources/config/anchor-config-schema-v1.yaml, platform/src/test/kotlin/org/stellar/anchor/platform/config/AppConfigTest.kt
- Stellar RPC (Soroban RPC) configuration
- Allows AP to communicate with an RPC server.
N/A
N/A
=> [ANCHOR-917] Stellar RPC (Soroban RPC) configuration

build.gradle.kts, docs/README.md, service-runner/src/main/resources/version-info.properties
=> [CHORE] Bump version to 3.0.3

build.gradle.kts, core/src/main/java/org/stellar/anchor/sep24/Sep24Helper.java, core/src/test/kotlin/org/stellar/anchor/sep24/Sep24ServiceTest.kt, core/src/test/kotlin/org/stellar/anchor/sep24/Sep24ServiceTestHelper.kt, docs/README.md, service-runner/src/main/resources/version-info.properties
=> [CHORE] Merge `release/3.0.3` into `main` (#1654)

build.gradle.kts, core/src/main/java/org/stellar/anchor/sep24/Sep24Helper.java, core/src/test/kotlin/org/stellar/anchor/sep24/Sep24ServiceTest.kt, core/src/test/kotlin/org/stellar/anchor/sep24/Sep24ServiceTestHelper.kt, docs/README.md, service-runner/src/main/resources/version-info.properties
=> [CHORE] Merge `main` into `develop` 

build.gradle.kts, docs/README.md, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSepTransaction.java, platform/src/main/resources/db/migration/V21__sep6_24_31_rename_column.sql, service-runner/src/main/resources/version-info.properties
=> [CHOER] Merge `release/3.0.4` into `main`

build.gradle.kts, docs/README.md, platform/src/main/java/org/stellar/anchor/platform/data/JdbcSepTransaction.java, platform/src/main/resources/db/migration/V21__sep6_24_31_rename_column.sql, service-runner/src/main/resources/version-info.properties
=> [CHORE] Merge `main` into `develop`

build.gradle.kts, docs/README.md, service-runner/src/main/resources/version-info.properties
Bump version to 3.1.0
New Release
N/A
N/A
=> Bump version to 3.1.0

.github/workflows/on_push_to_develop.yml, .github/workflows/on_release_created_or_updated.yml
Removes some commented out code from the workflow
Spring cleaning
N/A
N/A
=> [Chore] Remove commented out code from workflow

core/src/main/java/org/stellar/anchor/ledger/LedgerTransaction.java, platform/src/main/java/org/stellar/anchor/platform/observer/ObservedPayment.java, platform/src/test/kotlin/org/stellar/anchor/platform/custody/fireblocks/FireblocksEventServiceTest.kt
Remove un-used fields
Simplify
N/A
N/A
=> [ANCHOR-977] Remove un-used fields from LedgerTransaction and ObservedPayments

core/src/main/java/org/stellar/anchor/sep10/Sep10Service.java
- Improve Sep10Service client domain signature error message.
- Code improvement.
N/A
N/A
=> [ANCHOR-1034] Improve sep10 error message when client domain signature count does not match

platform/src/main/resources/db/migration/V22__web_auth_account.sql, platform/src/main/resources/db/migration/V23__web_auth_nonce.sql
- Since there is no releases between V22 and V23, we should merge these SQL files.
- Improvement
N/A
N/A
=> [CHORE] Merge Flyway SQL file V23 with V22

.github/workflows/on_push_to_develop.yml, .github/workflows/on_release_created_or_updated.yml, core/src/main/java/org/stellar/anchor/sep10/Sep10Service.java
-  merge develop to `feature/stellar-rpc`
- branch maintenance
N/A
N/A
=> [CHORE] merge develop to `feature/stellar-rpc`

core/src/main/java/org/stellar/anchor/ledger/Horizon.java, core/src/main/java/org/stellar/anchor/ledger/LedgerClientHelper.java, core/src/test/kotlin/org/stellar/anchor/ledger/LedgerClientHelperTest.kt
- Handle ENVELOPE_TYPE_TX_FEE_BUMP
- The existing code does not handle fee bump transactions
N/A
N/A
=> [ANCHOR-1041] Handle ENVELOPE_TYPE_TX_FEE_BUMP

build.gradle.kts, core/src/main/java/org/stellar/anchor/util/AssetValidator.java, core/src/main/resources/config/anchor-asset-default-values.yaml, docs/README.md, service-runner/src/main/resources/version-info.properties
- Merge `main` to `develop`
- post release 3.1.1 house keeping. 
N/A
N/A
=> [CHORE] Merge `main` to `develop` (3.1.1)

core/src/main/java/org/stellar/anchor/ledger/LedgerClientHelper.java, core/src/test/kotlin/org/stellar/anchor/ledger/LedgerClientHelperTest.kt, essential-tests/build.gradle.kts, essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/AbstractIntegrationTests.kt, essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/e2etest/Sep24End2EndTests.kt, essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/PaymentObserverTests.kt, platform/src/main/java/org/stellar/anchor/platform/observer/stellar/HorizonPaymentObserver.java, platform/src/main/java/org/stellar/anchor/platform/observer/stellar/StellarRpcPaymentObserver.java, platform/src/test/kotlin/org/stellar/anchor/platform/custody/CustodyPaymentHandlerTest.kt
- Add integration test `PaymentObserverTests`
- Send a payment and assert the events are as expected
- Send a path payment and assert the events are as expected
- Bug fixes
- Test improvements
=> [ANCHOR-1043] Add integration test `PaymentObserverTests`

.github/ISSUE_TEMPLATE/release-a-feature-version.md, .github/ISSUE_TEMPLATE/release-a-hotfix-version.md
- Renamed the release template to FEATURE release template
- Created HOTFIX release template.
- Release flow improvement
=> [CHORE] Update release template and create HOTFIX release flow

build.gradle.kts, core/src/main/java/org/stellar/anchor/util/AssetValidator.java, docs/README.md, service-runner/src/main/resources/version-info.properties
=> [CHORE] Merge `main` to `develop`

.github/ISSUE_TEMPLATE/release-a-feature-version.md, .github/ISSUE_TEMPLATE/release-a-hotfix-version.md, .github/workflows/on_push_to_develop.yml, .github/workflows/on_release_created_or_updated.yml, core/src/main/java/org/stellar/anchor/sep10/Sep10Service.java, core/src/main/java/org/stellar/anchor/util/AssetValidator.java, core/src/main/resources/config/anchor-asset-default-values.yaml, helm-charts/reference-server/templates/externalsecrets.yaml, helm-charts/secret-store/templates/secretstore.yaml, helm-charts/sep-service/templates/externalsecrets.yaml, kotlin-reference-server/src/main/kotlin/org/stellar/reference/callbacks/rate/RateService.kt, platform/src/main/java/org/stellar/anchor/platform/observer/stellar/StellarPaymentObserver.java, service-runner/src/main/resources/config/stellar.localhost.toml
This merges `develop` into `feature/c-accounts
Keep feature branch in sync
- 
N/A
N/A
=> [Chore] Merge `develop` into `feature/c-accounts`

.github/ISSUE_TEMPLATE/release-a-feature-version.md, .github/ISSUE_TEMPLATE/release-a-hotfix-version.md, build.gradle.kts, core/src/main/java/org/stellar/anchor/util/AssetValidator.java, core/src/main/resources/config/anchor-asset-default-values.yaml, docs/README.md, helm-charts/reference-server/templates/externalsecrets.yaml, helm-charts/secret-store/templates/secretstore.yaml, helm-charts/sep-service/templates/externalsecrets.yaml, kotlin-reference-server/src/main/kotlin/org/stellar/reference/callbacks/rate/RateService.kt, kotlin-reference-server/src/main/kotlin/org/stellar/reference/service/SepHelper.kt, service-runner/src/main/resources/config/stellar.localhost.toml, service-runner/src/main/resources/version-info.properties
- merge `develop` to `stellar-rpc`
- branch housekeeping.
=> [Chore] merge `develop` to `feature/stellar-rpc`

core/src/main/java/org/stellar/anchor/ledger/LedgerClientHelper.java
- Fix the `amount` of `LedgerClientHelper` not handling `i128`.
- bug fix
=> Fix the `amount` of `LedgerClientHelper` not handling `i128`.

core/src/test/kotlin/org/stellar/anchor/sep10/Sep10ServiceTest.kt, essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/Sep10ServiceIntegrationTests.kt, essential-tests/src/testFixtures/resources/test_account_with_noncompliant_signer.json
- Remove secret keys in `Sep10ServiceTest` and `Sep10ServiceIntegrationTests`
- Security improvement. 
- https://stellarfoundation.slack.com/archives/C08V2UGHTMX/p1748616946700749
=> [ANCHOR-1063] Remove secret keys in Sep10ServiceTest and Sep10ServiceIntegrationTests

build.gradle.kts, scripts.gradle.kts, service-runner/build.gradle.kts
- In build.gradle.kts, add doLast when necessary. 
- Add eclipse plugin for vscode
- Some actions in the task configurations should not be run when evaluating the Gradle script.
=> [CHORE] In build.gradle.kts, add doLast when necessary. 

.gitignore, helm-charts/secret-store/templates/secretstore.yaml
- Fix the failure when SENTRY_AUTH_TOKEN is empty when running local kube
- bug fixes
=> [HOTFIX] Fix the failure when SENTRY_AUTH_TOKEN is empty when running local kube

essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/PlatformAPITestBase.kt, soroban/README.md
- Merge with the `develop` branch
- branch maintainance
=> [CHORE] Merge with the `develop` branch

helm-charts/sep-service/templates/externalsecrets.yaml
Together with https://github.com/stellar/kube/pull/3321 to enable sep45 for testing
=> Enable sep45 for dev env

helm-charts/secret-store/templates/secretstore.yaml, helm-charts/sep-service/templates/externalsecrets.yaml, helm-charts/sep-service/templates/platform-deployment.yaml, helm-charts/sep-service/templates/sepserver-deployment.yaml
Add secret to sep and platform deployment, and fix syntax :/
=> Fix sep45 helm chart

build.gradle.kts, docs/README.md, service-runner/src/main/resources/version-info.properties
- Update release string to 3.1.3
- Release preparation
=> Update release string to 3.1.3

essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/PaymentObserverTests.kt, platform/src/main/java/org/stellar/anchor/platform/component/observer/PaymentObserverBeans.java, platform/src/main/java/org/stellar/anchor/platform/observer/stellar/StellarRpcPaymentObserver.java, platform/src/test/kotlin/org/stellar/anchor/platform/observer/stellar/StellarRpcPaymentObserverTest.kt
- Add filters based on the distribution account
- Improve the filter efficiency
=> [ANCHOR-1109] Add filters based on the distribution account

helm-charts/sep-service/values.yaml
Need to remove from local values as well
=> [ANCHOR] Update sep helm values according to rpc config change

.github/workflows/on_release_created_or_updated.yml
- Add ARM64 to docker build
- From issue: https://github.com/stellar/anchor-platform/issues/1789
- Improve docker image performance on ARM64.
=> [ANCHOR-1127] Add ARM64 to docker build

essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/e2etest/Sep31End2EndTests.kt
- Merge `main` with  `4.0.0`
- Post release maintenance.
=> [CHORE] Merge `main` with  `4.0.0`

README.md, core/src/test/kotlin/org/stellar/anchor/sep45/Sep45ServiceTest.kt
- Add Sep45Service unit tests
- Test improvements
=> [ANCHOR-1045] Add Sep45Service unit tests
