stellar/anchor-platform

- pom.xml
- src/main/java/org/stellar/anchor/paymentservice/Account.java
- src/main/java/org/stellar/anchor/paymentservice/circle/CirclePaymentsService.java
- src/main/java/org/stellar/anchor/paymentservice/circle/model/CircleBalance.java
- src/main/java/org/stellar/anchor/paymentservice/circle/model/CirclePaymentStatus.java
- src/main/java/org/stellar/anchor/paymentservice/circle/model/CircleTransactionParty.java
- src/main/java/org/stellar/anchor/paymentservice/circle/model/CircleTransfer.java
- src/main/java/org/stellar/anchor/paymentservice/circle/model/CircleWallet.java
- src/main/java/org/stellar/anchor/paymentservice/circle/model/request/CircleSendTransactionRequest.java
- src/main/java/org/stellar/anchor/paymentservice/circle/model/response/CircleTransferResponse.java
- src/main/java/org/stellar/anchor/paymentservice/circle/util/CircleDateFormatter.java
- src/test/kotlin/org/stellar/anchor/paymentservice/AccountCapabilitiesTest.kt
- src/test/kotlin/org/stellar/anchor/paymentservice/circle/CirclePaymentsServiceTest.kt
- src/test/kotlin/org/stellar/anchor/paymentservice/circle/util/CircleDateFormatterTest.kt
Implement `POST /v1/transfer` request that supports `Circle->Circle` and `Circle->Stellar` payments.
> paymentsservice: implement sendPayment to send `Circle->Circle` or `Circle->Stellar` payments

- .github/pull_request_template.md
Add a pull request template based on [stellar/go's](https://github.com/stellar/go/blob/master/.github/pull_request_template.md).
So we establish a clear way to communicate the pull request changes and create a better context for the code reviewers.
> all: add pull request template

- core/src/main/java/org/stellar/anchor/paymentservice/Account.java
- payment-circle/build.gradle.kts
- payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/CirclePaymentsService.java
- payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/model/CirclePayout.java
- payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/model/CircleWallet.java
- payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/model/request/CircleSendTransactionRequest.java
- payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/model/response/CirclePayoutResponse.java
- payment-circle/src/test/kotlin/org/stellar/anchor/paymentservice/circle/CirclePaymentsServiceTest.kt
- settings.gradle.kts
<details>
otherwise).
packages.
</details>
Extend sendPayment functionality to allow sendding `Circle->BankWire` payments.
This is a feature that one of our potential adopters needs and it's likely most partners will need it too.
> payment-circle: extend sendPayment functionality to allow sendding `Circle->BankWire` payments

- payment-circle/src/test/kotlin/org/stellar/anchor/paymentservice/circle/CirclePaymentServiceTest.kt
<details>
otherwise).
packages.
</details>
Fix code formatting in the `CirclePaymentServiceTest` file.
It wasn't formatted properly on #24 and we need it in the proper formatting before we continue to make changes to the file.
> test: fix code formatting in the `CirclePaymentServiceTest` file

- core/src/main/java/org/stellar/anchor/paymentservice/Payment.java
- core/src/main/java/org/stellar/anchor/paymentservice/PaymentHistory.java
- payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/CircleGsonParsable.java
- payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/CirclePaymentService.java
- payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/CircleResponseErrorHandler.java
- payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/StellarReconciliation.java
- payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/model/CircleBalance.java
- payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/model/CirclePayout.java
- payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/model/CircleTransactionParty.java
- payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/model/CircleTransfer.java
- payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/model/CircleWallet.java
- payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/model/request/CircleSendTransactionRequest.java
- payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/model/response/CirclePayoutListResponse.java
- payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/model/response/CircleTransferListResponse.java
- payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/util/NettyHttpClient.java
- payment-circle/src/test/kotlin/org/stellar/anchor/paymentservice/circle/CirclePaymentServiceTest.kt
- payment-circle/src/test/kotlin/org/stellar/anchor/paymentservice/circle/CircleResponseErrorHandlerTest.kt
- payment-circle/src/test/kotlin/org/stellar/anchor/paymentservice/circle/ErrorHandlingTestCase.kt
- payment-circle/src/test/kotlin/org/stellar/anchor/paymentservice/circle/StellarReconciliationTest.kt
- payment-circle/src/test/kotlin/org/stellar/anchor/paymentservice/circle/model/CircleTransferSerializationTest.kt
- payment-circle/src/test/kotlin/org/stellar/anchor/paymentservice/utils/NettyHttpClientTest.kt
<details>
otherwise).
packages.
</details>
Implement `CirclePaymentService#getAccountHistory` as part of the `PaymentService` implementation. This implementation is a bit non conventional because it aggregates results from multiple endpoints into one, since Circle history is distributed across multiple endpoints:
* `GET /v1/transfers` returns CircleWallet->CircleWallet, CircleWallet->Stellar and Stellar->CircleWallet results.
* `GET /v1/payouts` returns CircleWallet->BankWire results.
* (not implemented) `GET /v1/payments` returns BankWire->CircleWallet and CreditCard->CircleWallet
When we aggregate results from multiple endpoints, we mess with the consistency of page sizes: …
> payment-circle: implement getAccountHistory method

- core/src/main/java/org/stellar/anchor/paymentservice/Account.java
- docs/payment-circle.md
- payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/CirclePaymentService.java
- payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/model/CircleBalance.java
- payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/model/CircleBlockchainAddress.java
- payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/model/CircleTransactionParty.java
- payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/model/CircleWallet.java
- payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/model/CircleWireDepositInstructions.java
- payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/model/request/CircleSendTransactionRequest.java
- payment-circle/src/main/java/org/stellar/anchor/paymentservice/circle/util/CircleAsset.java
- payment-circle/src/test/kotlin/org/stellar/anchor/paymentservice/circle/CirclePaymentServiceTest.kt
<details>
otherwise).
packages.
</details>
Code polishes and small fixes. Changes details:
* Add `CircleWallet.defaultCapabilities()` and `CircleWallet.merchantAccountCapabilities()` to avoid hardcoding the capabilities every time.
* Update Account default `balances` and `unsettledBalances` values to null, so the JSON response works better when we don't have the balances. Otherwise, returning an empty list passes the impression the balances are empty when that might not be the case.
* Fix paginated responses cursors.
* Updated docs on how to get the bank deposit instructions.
* Solve warnings
* Update `CirclePaymentServiceTest` to reduce code repetition and standardize …
> payment-circle: polish responses and code

- core/src/main/java/org/stellar/anchor/asset/AssetResponse.java
- core/src/main/java/org/stellar/anchor/asset/AssetService.java
- core/src/main/java/org/stellar/anchor/asset/ResourceJsonAssetService.java
- core/src/main/java/org/stellar/anchor/dto/sep24/InfoResponse.java
- core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java
- core/src/main/java/org/stellar/anchor/sep38/Sep38Service.java
- core/src/test/kotlin/org/stellar/anchor/asset/ResourceJsonAssetServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/dto/sep24/Sep24DtoTests.kt
- core/src/test/kotlin/org/stellar/anchor/sep24/Sep24ServiceTest.kt
- platform/src/main/java/org/stellar/anchor/server/SepConfig.java
<details>
otherwise).
packages.
</details>
Move AssetService, AssetResponse and ResourceJsonAssetService to a different folder so they are decoupled from SEP-24 and can be used across other SEPs.
These files are relevant for SEP-6, SEP-24, SEP-31 and SEP-38 and shouldn't be confined to the `*/sep24/*` folder.
> core: move AssetService, AssetResponse and ResourceJsonAssetService to a different folder

- core/src/main/java/org/stellar/anchor/sep1/ResourceReader.java
- core/src/main/java/org/stellar/anchor/sep1/Sep1Service.java
- core/src/main/java/org/stellar/anchor/sep10/Sep10Service.java
- core/src/main/java/org/stellar/anchor/util/Sep1Helper.java
- platform/example.anchor-config.yaml
- platform/src/main/java/org/stellar/anchor/platform/SepConfig.java
- platform/src/test/kotlin/org/stellar/anchor/platform/AnchorPlatformIntegrationTest.kt
closes #105
<details>
otherwise).
packages.
</details>
This PR reads SEP1 content from resource external to the application.
> core: platform: Read SEP1 stellar.toml from external resource

- core/src/main/java/org/stellar/anchor/asset/AssetInfo.java
- core/src/main/java/org/stellar/anchor/dto/sep38/GetPricesResponse.java
- core/src/main/java/org/stellar/anchor/dto/sep38/InfoResponse.java
- core/src/main/java/org/stellar/anchor/sep38/Sep38Service.java
- core/src/test/kotlin/org/stellar/anchor/sep38/Sep38ServiceTest.kt
- core/src/test/resources/test_assets.json
- platform/src/main/java/org/stellar/anchor/platform/AnchorPlatformServer.java
- platform/src/main/resources/assets-prod.json
- platform/src/main/resources/assets-test.json
- platform/src/test/resources/test_assets.json
- platform/src/test/resources/test_sep38_get_info.json
<details>
otherwise).
packages.
</details>
The number of decimals returned in SEP-38's [`GET /prices`], [`POST /quote`] and [`GET /quote/:id`] requests now defaults to **7** and can be configured to a different value in the assets.json config file.
Addressing Jake's comment in https://github.com/stellar/java-stellar-anchor-sdk/pull/113#discussion_r826102562.
[`GET /prices`]: https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0038.md#get-prices
[`POST /quote`]: https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0038.md#post-quote
[`GET /quote/:id`]: https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0038.md#get-quote
> core: SEP-38's number of decimals can now be set in the assets.json configuration file

- .github/workflows/build_and_test.yml
<details>
otherwise).
packages.
</details>
Add a Github Action that runs the [stellar-anchor-tests](https://github.com/stellar/stellar-anchor-tests) script in the preview instance to validate SEPs 1 and 38.
To make sure our SEP implementations are fully compliant.
Close #116 
There's also a Jenkins job attempting to run this same script but it's failing, so please nevermind the following Jenkins status:
Will be following up about that in this issue: https://github.com/stellar/java-stellar-anchor-sdk/issues/171
> ci: add script to validate SEP-1 and SEP-38

- anchor-reference-server/src/main/java/org/stellar/anchor/reference/service/CustomerService.java
- core/src/main/java/org/stellar/anchor/dto/sep31/Sep31InfoResponse.java
- core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java
- core/src/main/java/org/stellar/anchor/sep31/Sep31TransactionStore.java
- core/src/main/java/org/stellar/anchor/sep38/Sep38Service.java
- core/src/main/java/org/stellar/anchor/util/MemoHelper.java
- data-spring-jdbc/src/main/java/org/stellar/anchor/server/data/JdbcSep31TransactionRepo.java
- data-spring-jdbc/src/main/java/org/stellar/anchor/server/data/JdbcSep31TransactionStore.java
- platform-apis/src/main/java/org/stellar/platform/apis/callbacks/requests/PutCustomerRequest.java
- platform/src/main/java/org/stellar/anchor/platform/AnchorPlatformServer.java
- platform/src/main/java/org/stellar/anchor/platform/SepConfig.java
- platform/src/main/java/org/stellar/anchor/platform/controller/Sep12Controller.java
- platform/src/main/java/org/stellar/anchor/platform/paymentobserver/StellarPaymentObserver.java
- platform/src/main/java/org/stellar/anchor/platform/service/PaymentOperationToEventListener.java
- platform/src/main/kotlin/org/stellar/anchor/platform/Sep38Tests.kt
- platform/src/main/kotlin/org/stellar/anchor/platform/SepClient.kt
- platform/src/main/resources/assets-test.json
<details>
otherwise).
packages.
</details>
Integrate PaymentObserver with SEP-31. 
N/A.
The transaction status is changed to COMPLETED after the payment is received. When event queue is implemented, the reference server should call `PATCH /transactions` to update the status from PENDING_RECEIVER to COMPLETED.
> platform: Integrate payment observer with SEP-31

- anchor-reference-server/src/main/java/org/stellar/anchor/reference/AnchorReferenceServer.java
- anchor-reference-server/src/main/java/org/stellar/anchor/reference/YamlPropertySourceFactory.java
<details>
otherwise).
packages.
</details>
The reference server does not read from anchor-reference-server.yaml. This is the fix that can read YAML file.
N/A
N/A
> anchor-reference-server: Add Yaml configuration support to the reference server.

- .github/workflows/build_and_test.yml
- anchor-reference-server/src/main/java/org/stellar/anchor/reference/controller/CustomerController.java
- anchor-reference-server/src/main/java/org/stellar/anchor/reference/controller/GlobalControllerExceptionHandler.java
- anchor-reference-server/src/main/java/org/stellar/anchor/reference/service/CustomerService.java
- core/src/main/java/org/stellar/anchor/dto/sep12/Sep12DeleteCustomerRequest.java
- core/src/main/java/org/stellar/anchor/integration/customer/CustomerIntegration.java
- core/src/main/java/org/stellar/anchor/sep10/Sep10Service.java
- core/src/main/java/org/stellar/anchor/sep12/Sep12Service.java
- core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java
- docs/docker-examples/kafka/docker-compose.yaml
- platform-apis/src/main/java/org/stellar/platform/apis/callbacks/requests/DeleteCustomerRequest.java
- platform-apis/src/main/java/org/stellar/platform/apis/callbacks/responses/DeleteCustomerResponse.java
- platform/src/main/java/org/stellar/anchor/platform/callback/RestCustomerIntegration.java
- platform/src/main/java/org/stellar/anchor/platform/controller/GlobalControllerExceptionHandler.java
- platform/src/main/java/org/stellar/anchor/platform/controller/Sep10Controller.java
- platform/src/main/java/org/stellar/anchor/platform/controller/Sep12Controller.java
- platform/src/main/kotlin/org/stellar/anchor/platform/Sep12Client.kt
- platform/src/main/kotlin/org/stellar/anchor/platform/Sep12Tests.kt
- platform/src/main/resources/default-config.yaml
- platform/src/test/resources/stellar-anchor-tests-sep-config.json
<details>
otherwise).
packages.
</details>
Increase the number of SEPs our CI script [stellar-anchor-tests](https://github.com/stellar/stellar-anchor-tests) is testing. We were only covering SEP-1 and SEP-38, and this PR adds coverage for SEP-10, SEP-12, and SEP-31 as well.
This PR also includes:
* Fixes for those SEPs to make sure they pass the tests and thus are compliant with the industry standards.
* Implement SEP-12 `DELETE /customer`.
* Fix exception handlers (and add missing ones), mostly in `GlobalControllerExceptionHandler`.
* Add missing SEP-12 controller handler for different deletion content types
To improve our test coverage and make sure our code is compliant …
> all: update the `stellar-anchor-tests` CI command to also validate SEP-10, SEP-12 and SEP-31

- Dockerfile
- anchor-reference-server/src/main/java/org/stellar/anchor/reference/AnchorReferenceConfig.java
- anchor-reference-server/src/main/java/org/stellar/anchor/reference/AnchorReferenceServer.java
- anchor-reference-server/src/main/java/org/stellar/anchor/reference/controller/CustomerController.java
- anchor-reference-server/src/main/java/org/stellar/anchor/reference/controller/FeeController.java
- anchor-reference-server/src/test/kotlin/org/stellar/anchor/server/AnchorReferenceServerIntegrationTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/AnchorPlatformIntegrationTest.kt
<details>
otherwise).
packages.
</details>
Currently, the REFERENCE_SERVER_CONFIG (previously REFERENCE_CONFIG) is read from the environment. If it does not exist, the application won't start. This is to improve the import mechanism.
N/A
N/A
> Improve the REFERENCE_SERVER_CONFIG import mechanism

- anchor-reference-server/src/main/java/org/stellar/anchor/reference/controller/HealthController.java
- core/src/main/java/org/stellar/anchor/util/HealthCheck.java
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/AnchorPlatformIntegrationTest.kt
- platform/src/main/java/org/stellar/anchor/platform/controller/HealthController.java
<details>
otherwise).
packages.
</details>
Add health check endpoints at `/health` for both the SEP and Reference servers.
So we can have endpoints to check the status of the servers and their sub-services.
Add coverage to all sub-services, like kafka, stellar watcher, circle watcher, etc.
> all: add health check endpoints at `/health` for both the SEP and Reference servers

- core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java
- integration-tests/src/main/kotlin/org/stellar/anchor/platform/Sep31Client.kt
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/Sep31Tests.kt
… found
<details>
otherwise).
packages.
</details>
Fix issue #254 . 
When the asset code is invalid, we should return 400 instead of status code 500, which is caused by an NullPointerException.
N/A
N/A
> core: Fix NullPointerException when the asset in the SEP-31 request not valid

- core/src/main/java/org/stellar/anchor/config/AppConfig.java
- core/src/main/java/org/stellar/anchor/config/PII.java
- core/src/main/java/org/stellar/anchor/config/Secret.java
- core/src/main/java/org/stellar/anchor/config/Sep10Config.java
- core/src/main/java/org/stellar/anchor/sep1/Sep1Service.java
- core/src/main/java/org/stellar/anchor/sep10/Sep10Service.java
- core/src/main/java/org/stellar/anchor/util/FileUtil.java
- core/src/main/java/org/stellar/anchor/util/Log.java
- core/src/test/kotlin/org/stellar/anchor/Constants.kt
- core/src/test/kotlin/org/stellar/anchor/sep1/Sep1ServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/util/LogTest.kt
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/AnchorPlatformIntegrationTest.kt
- platform/src/main/resources/log4j2.yaml
<details>
otherwise).
packages.
</details>
Improve the logging of SEP-1 and SEP-10
N/A
N/A
> core: Improve SEP-1, SEP-10 logging

- api-schema/src/main/java/org/stellar/anchor/api/sep/sep38/RateFeeDetail.java
<details>
otherwise).
packages.
</details>
Add `@NoArgsConstructor` to `RateFeeDetail` so it can be parsed by kafka.
Otherwise, kafka would throw errors.
> bugfix: add NoArgsConstructor to RateFeeDetail so it can be parsed by kafka

- .gitignore
- api-schema/src/main/java/org/stellar/anchor/api/callback/GetFeeRequest.java
- core/src/main/java/org/stellar/anchor/sep12/Sep12Service.java
- core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java
- core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java
- core/src/main/java/org/stellar/anchor/util/SepHelper.java
- core/src/main/java/org/stellar/anchor/util/SepLanguageHelper.java
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/AnchorPlatformIntegrationTest.kt
- platform/src/main/java/org/stellar/anchor/platform/controller/Sep12Controller.java
- platform/src/main/java/org/stellar/anchor/platform/controller/Sep31Controller.java
- platform/src/main/java/org/stellar/anchor/platform/controller/Sep38Controller.java
<details>
otherwise).
packages.
</details>
Replace usage of ~`client_domain`~ with `client_id` in the `GET /fee` callback API
This change was made in the documentation in https://github.com/stellar/stellar-anchor-platform/pull/25 but wasn't updated in the code.
Closes #325.
> Note: we need to make sure we're more thorough next time and create tickets for the changes that need to be performed across other repos and the code.
> bugfix: replace usage of `client_domain` with `client_id` in the GET /fee callback API

- integration-tests/src/main/kotlin/org/stellar/anchor/platform/Sep12Client.kt
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/PlatformTests.kt
- platform/src/main/java/org/stellar/anchor/platform/controller/Sep12Controller.java
<details>
otherwise).
packages.
</details>
Fix reference cycle caused by print.
For some reason, when we printed the request, it caused a reference cycle that went on until the computer memory is over, to finally throw a 500.
The reference cycle happened in:
https://github.com/stellar/java-stellar-anchor-sdk/blob/c6bfc92f9499f9efec4ec10cca6933a6c3088ac9/core/src/main/java/org/stellar/anchor/filter/BaseTokenFilter.java#L84
The error:
> Note: these lines repeat in a loop, the full stack trace has hundreds of lines.
> hotfix: fix `gson` reference cycle triggered by a print

- docs/03 - Implementing the Anchor Server/Callbacks API.yml
The `client_id` field description is good only for SEP-31. This PR adds more descriptions for SEP-6 and SEP-24 and custodial account. 
<details>
otherwise).
packages.
</details>
Add more details of the client_id field of the fee callback API
adds more descriptions for SEP-6 and SEP-24 and custodial account. 
The code should be modified to reflect the change.
> docs: Add more details of the `client_id` field of the fee callback API.

- core/src/main/java/org/stellar/anchor/sep24/Sep24Helper.java
- core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java
- core/src/main/java/org/stellar/anchor/sep24/Sep24Transaction.java
- core/src/test/kotlin/org/stellar/anchor/TestHelper.kt
- core/src/test/kotlin/org/stellar/anchor/filter/Sep10TokenFilterTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep24/Sep24ServiceTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/configurator/ConfiguratorTest.kt
Closes #331
https://github.com/stellar/java-stellar-anchor-sdk/issues/331 
<details>
otherwise).
packages.
</details>
Fixed the memo value is being dropped when generating SEP-24 interactive URL JWT and more_info_url JWT
Bug
N/A
> core: Fix issue-331 memo value is being dropped when generating SEP-24 interactive URL JWT and more_info_url JWT

- end-to-end-tests/end_to_end_tests.py
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/AnchorPlatformIntegrationTest.kt
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/Sep31Tests.kt
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/Sep38Tests.kt
- platform/src/main/resources/assets-test.json
- platform/src/main/resources/sep1/stellar-wks.toml
<details>
otherwise).
packages.
</details>
Remove duplicate USDC asset that was causing USDC transfer to not work.
Also, use a different USDC (issued by our account) so we can have more control over it.
> bugfix: remove duplicate USDC asset that was causing USDC transfer to not work

- core/src/main/java/org/stellar/anchor/sep12/Sep12Service.java
<details>
otherwise).
packages.
</details>
Swap out hardcoded customer type values in SEP-12 to `receiving_user` and `sending_user`
These are the values currently used by bitso's e2e test
We should remove the hardcoded values and make customer type configurable across SEPs
> Swap out hardcoded customer type values in SEP-12

- platform/src/main/java/org/stellar/anchor/platform/callback/RestCustomerIntegration.java
<details>
otherwise).
packages.
</details>
Let '/customer' DELETE calls expect 204 on success, instead of 200.
This is in line with the OpenAPI spec for anchor platform
> Let /customer DELETE calls expect 204 on success instead of 200

- .github/workflows/build_and_test.yml
<details>
otherwise).
packages.
</details>
When pushing the image to Docker Hub, include the `latest` tag.
This solution was based on [the documentation](https://github.com/docker/build-push-action#customizing).
The only tag we were using was the commit sha, but `latest` is a widely used (and expected) tag.
Close #350.
> dockerhub: include `latest` tag when pushing the image

- docs/00 - Stellar Anchor Platform.md
<details>
otherwise).
packages.
</details>
Update documentation with a high-level estimate of database storage usage for the Anchor Platform, considering the SEP-31 (with SEP-38) flow.
Our tests indicate that **each SEP-31 (with SEP-38) transaction occupies ~2KB of space in the database**. The tests also indicate that the data space usage tends to decrease as the number of SEP-31 transactions increases. These results were achieved by executing 500 SEP-31 transactions on a Postgres database.
Close #304.
This is not a real-world scenario, but it's a good estimate of the amount of data that will be used by SEP-31 transactions.
> docs: add high-level database sizing information

- anchor-reference-server/src/main/java/org/stellar/anchor/reference/client/PlatformApiClient.java
- core/src/main/java/org/stellar/anchor/auth/AuthHelper.java
- core/src/test/kotlin/org/stellar/anchor/auth/AuthHelperTest.kt
- core/src/test/kotlin/org/stellar/anchor/auth/JwtServiceTest.kt
- platform/src/main/java/org/stellar/anchor/platform/callback/PlatformIntegrationHelper.java
- platform/src/test/kotlin/org/stellar/anchor/platform/callback/PlatformIntegrationHelperTest.kt
<details>
otherwise).
packages.
</details>
Fix auth header when the authorization type is NONE.
When trying to set the RequestBuilder header to Authorization: null, we were getting a NullPointerException in:
https://github.com/stellar/java-stellar-anchor-sdk/blob/be4095414e6201e2ab7779cea1621e7d1f07881a/platform/src/main/java/org/stellar/anchor/platform/callback/PlatformIntegrationHelper.java#L17-L22
> bugfix: fix auth header when the authorization type is NONE

- core/src/main/java/org/stellar/anchor/sep31/RefundPaymentBuilder.java
- core/src/main/java/org/stellar/anchor/sep31/RefundsBuilder.java
- core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java
- core/src/main/java/org/stellar/anchor/sep31/Sep31TransactionBuilder.java
- core/src/test/java/org/stellar/anchor/sep31/PojoSep31RefundPayment.java
- core/src/test/java/org/stellar/anchor/sep31/PojoSep31Refunds.java
- core/src/test/kotlin/org/stellar/anchor/sep31/Sep31HelperTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep31/Sep31ServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep31/Sep31TransactionBuilderTest.kt
- platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep31Refunds.java
Improve the core's `org.stellar.anchor.sep31` package test coverage to 100%.
<details>
otherwise).
packages.
</details>
This PR is to improve SEP-31 core package test coverage to 100%. 
N/A
This PR focuses on test coverage with some validations. More validation can be added to cover the corner cases.
> core: Improve SEP-31 unit test coverage

- anchor-reference-server/src/main/java/org/stellar/anchor/reference/config/IntegrationAuthSettings.java
- anchor-reference-server/src/main/resources/anchor-reference-server.yaml
- core/src/main/java/org/stellar/anchor/config/IntegrationAuthConfig.java
- platform/src/main/java/org/stellar/anchor/platform/config/PropertyIntegrationAuthConfig.java
- platform/src/main/resources/anchor-config-defaults.yaml
<details>
otherwise).
packages.
</details>
The default value of integration-auth configuration is JWT_TOKEN. We should set it to none.
N/A
N/A
> platform: Set the integration-auth as NONE and disable the metrics in default

- anchor-reference-server/src/main/java/org/stellar/anchor/reference/controller/UniqueAddressController.java
- anchor-reference-server/src/main/java/org/stellar/anchor/reference/service/UniqueAddressService.java
- core/src/main/java/org/stellar/anchor/util/ConditionalOnPropertyNotEmpty.java
<details>
otherwise).
packages.
</details>
Create annotation `ConditionalOnPropertyNotEmpty` and add it to the `UniqueAddressController` and `UniqueAddressService`, so they are only instantiated when the `anchor.settings.distributionWallet` property is not empty.
Close #443
> hotfix: solve issue where `uniqueAddressService` was crashing

- helm-charts/sep-service/Chart.yaml
- helm-charts/sep-service/templates/configmap.yaml
<details>
otherwise).
packages.
</details>
Fix typo in helm chart to check for kafkaPublisher
The typo causes the template to always use the default clause for `kafkaPublisher.eventTypeToQueue`
> helm: Fix typo in helm chart for kafkaPublisher.eventTypeToQueue

- platform/src/test/kotlin/org/stellar/anchor/platform/LogAppenderTest.kt
Closes #452 
While running LogAppenderTest in IntelliJ, the test fails because the log4j console appender does not write to system output. The system capture would fail. 
This PR fixes 
<details>
otherwise).
packages.
</details>
Make sure the logger output correct logger name. 
While running LogAppenderTest in IntelliJ, the test fails because the log4j console appender does not write to system output. The system capture would fail. 
N/A
> platform: Fix error when not running LogAppenderTest from console

- docs/resources/deployment-examples/example-fargate/terraform/codebuild_config.tf
- docs/resources/deployment-examples/example-fargate/terraform/variables.tf
This PR removes hardcoded branch for AWS CodeBuild source version and replaces it with a terraform variable with default to "main".   our design partner was deploying the fargate example and buildspec error was given:
```
YAML_FILE_ERROR: stat /codebuild/output/src961726718/src/github.com/jlaguilarm/java-stellar-anchor-sdk/docs/resources/deployment-examples/aws-fargate-ecs/buildspec-dev.yml: no such file or directory
```
> codebuild_source_version

- helm-charts/sep-service/Chart.yaml
This bumps helm chart version number to 0.3.87 prior to publishing.   This chart update includes fixes for CI integration testing of unique endpoint feature for sep31 post transaction.
https://github.com/stellar/java-stellar-anchor-sdk/pull/466
https://github.com/stellar/java-stellar-anchor-sdk/pull/458
> Bump Helm Chart to 0.3.87

- docs/resources/deployment-examples/example-fargate/Dockerfile
- docs/resources/deployment-examples/example-fargate/buildspec-dev.yml
- docs/resources/deployment-examples/example-fargate/terraform/variables.tf
after deploying to partner, some paths which existed prior to documentation refactor remained.  
specifically,  docs/resources/deployment-examples/example-fargate
> fixing paths for buildspec after documentation refactor

- gradle/wrapper/gradle-wrapper.properties
- gradlew
The version catalog feature was incubating in Gradle 7.3. It is now a stabilized feature in 7.5.1. 
This is to prepare to structuring the dependency management of Gradle.
<details>
otherwise).
packages.
</details>
Upgrade Gradle from 7.5 to 7.5.1.
The version catalog feature was incubating in Gradle 7.3. It is now a stabilized feature in 7.5.1. 
N/A.
> Upgrade Gradle from 7.3 to 7.5.1

- .github/workflows/build_and_test.yml
<details>
otherwise).
packages.
</details>
Change the `complete` ci job so that it always runs, regardless of whether other jobs succeed or not, and it errors if a needed job is cancelled.
GitHub jobs are by default skipped if a needed job fails. Skipped jobs are, surprise, interpreted as successful/passes by the GitHub Actions required checks. Here's an example of one where this happened:
Ref: https://github.com/stellar/java-stellar-anchor-sdk/pull/468
Therefore the `complete` job needs to always run, regardless of whether its needed jobs complete successfully or not.
Also, GitHub jobs can be cancelled. When a job is cancelled its `needs.*.result` value will be …
> all: fix complete ci job

- integration-tests/build.gradle.kts
<details>
otherwise).
packages.
</details>
Fix `build.gradle.kts` from the integration-tests package.
So the integration tests can be executed.
> hotfix: fix build.gradle.kts from the integration-tests package, so the integration tests can be executed

- core/src/main/java/org/stellar/anchor/sep12/Sep12Service.java
- core/src/test/kotlin/org/stellar/anchor/sep12/Sep12ServiceTest.kt
<details>
otherwise).
packages.
</details>
The SEP-12's deletion should not require the memo to be in the JWT_TOKEN when it is sent on the request body
Close #509
> hotfix: SEP-12's deletion should not require the memo to be in the JWT_TOKEN when it is sent on the request body

- platform/src/main/java/org/stellar/anchor/platform/service/MetricEmitterService.java
<details>
otherwise).
packages.
</details>
Start the metrics emitter in @PostConstruct. 
If MetricsEmitter calls Hibernate before it is fully initialized, it causes database locking error in SQLite. We should delay the scheduling of the thread to avoid the contention.
This issue can be further avoided when we implement the start-up sequence dependency.
> platform: Fix the contention problem that causes locked database.

- .github/workflows/build_and_test.yml
<details>
otherwise).
packages.
</details>
Fix CI not being executed in the develop branch after merging.
After we changed the default branch to `develop`, we hadn't updated the CI to run on the new default branch (after merging PRs).
> hotfix: CI was not being executed in the develop branch after merging

- platform/src/main/java/org/stellar/anchor/platform/payment/observer/stellar/StellarPaymentObserver.java
- platform/src/test/kotlin/org/stellar/anchor/platform/payment/observer/stellar/StellarPaymentObserverTest.kt
<details>
otherwise).
packages.
</details>
- When no cursor can be found in the database, the Stellar streamer will start from the most recent cursor in the Network.
- Also, the streaming request was updated to use `?limit=200` for improved efficiency. The default limit is 10, which is 20 times less efficient.
To improve the efficiency of the streamer on average and mostly on the first run.
Close #500.
> Feature: when no cursor can be found in the database, the Stellar streamer will start from the most recent cursor in the Network

- core/src/main/java/org/stellar/anchor/util/UrlValidationUtil.java
<details>
otherwise).
packages.
</details>
The `UrlValidateionUtil.validateUrl()` tries to connect to a URL defined in a config file. However, the URL may not be reachable at the time of construction. 
Added `testConnection` argument to make the connection test optional.
N/A
N/A
> core: Make testing connection of UrlValidateionUtil.validateUrl() optional

- .github/workflows/basic_tests.yml
- .github/workflows/release_main.yml
<details>
otherwise).
packages.
</details>
Fix the way the Action tries to grab the Release tag name.
the previous way was not working: https://github.com/stellar/java-stellar-anchor-sdk/actions/runs/3063883688
> hotfix: fix how the GH Action gets the tag name

- build.gradle.kts
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/AnchorPlatformIntegrationTest.kt
- platform/src/main/java/org/stellar/anchor/platform/StellarObservingService.java
- platform/src/main/java/org/stellar/anchor/platform/controller/CirclePaymentObserverController.java
- platform/src/main/java/org/stellar/anchor/platform/controller/PlatformController.java
- platform/src/main/java/org/stellar/anchor/platform/controller/Sep10Controller.java
- platform/src/main/java/org/stellar/anchor/platform/controller/Sep12Controller.java
- platform/src/main/java/org/stellar/anchor/platform/controller/Sep1Controller.java
- platform/src/main/java/org/stellar/anchor/platform/controller/Sep24Controller.java
- platform/src/main/java/org/stellar/anchor/platform/controller/Sep31Controller.java
- platform/src/main/java/org/stellar/anchor/platform/controller/Sep38Controller.java
- service-runner/src/main/java/org/stellar/anchor/platform/ServiceRunner.java
<details>
otherwise).
packages.
</details>
Add a `/health` endpoint to the Stellar Observer deployment.
To enable people to check the status of the Stellar Observer.
> Feature: add health check to stellar observer

- api-schema/src/main/java/org/stellar/anchor/api/exception/EventPublishException.java
- build.gradle.kts
- core/src/main/java/org/stellar/anchor/event/EventPublishService.java
- core/src/main/java/org/stellar/anchor/event/KafkaEventService.java
- core/src/main/java/org/stellar/anchor/event/SqsEventService.java
- core/src/main/java/org/stellar/anchor/util/ExponentialBackoffTimer.java
- core/src/test/kotlin/org/stellar/anchor/util/ExponentialBackoffTimerTest.kt
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/AnchorPlatformIntegrationTest.kt
- platform/src/main/java/org/stellar/anchor/platform/StellarObservingService.java
- platform/src/main/java/org/stellar/anchor/platform/controller/CirclePaymentObserverController.java
- platform/src/main/java/org/stellar/anchor/platform/controller/PlatformController.java
- platform/src/main/java/org/stellar/anchor/platform/controller/Sep10Controller.java
- platform/src/main/java/org/stellar/anchor/platform/controller/Sep12Controller.java
- platform/src/main/java/org/stellar/anchor/platform/controller/Sep1Controller.java
- platform/src/main/java/org/stellar/anchor/platform/controller/Sep24Controller.java
- platform/src/main/java/org/stellar/anchor/platform/controller/Sep31Controller.java
- platform/src/main/java/org/stellar/anchor/platform/controller/Sep38Controller.java
- platform/src/main/java/org/stellar/anchor/platform/payment/observer/PaymentListener.java
- platform/src/main/java/org/stellar/anchor/platform/payment/observer/circle/CirclePaymentObserverService.java
- platform/src/main/java/org/stellar/anchor/platform/payment/observer/stellar/StellarPaymentObserver.java
- platform/src/main/java/org/stellar/anchor/platform/service/PaymentOperationToEventListener.java
- platform/src/main/java/org/stellar/anchor/platform/utils/ExponentialBackoffTimer.java
- platform/src/main/java/org/stellar/anchor/platform/utils/ExponentialBackoffUtil.java
- service-runner/src/main/java/org/stellar/anchor/platform/ServiceRunner.java
<details>
otherwise).
packages.
</details>
Add retry and exponential back-off to the stellar observer when the queue is offline.
Close #293.
> Feature: stellar observer retry with exponential back-off timer

- helm-charts/sep-service/Chart.yaml
- helm-charts/sep-service/example_values.yaml
- helm-charts/sep-service/templates/deployment.yaml
<details>
otherwise).
packages.
</details>
* Expose the `8082` metrics port to the internal network.
* Add `deployment.annotations` to the example values.
* Delete duplicate appearance of `ORG_URL` in the example values.
To improve the helm chart to be closer to a real-world scenario.
> Feature: update helm chart by exposing the metrics port to the internal network

- .github/workflows/branch_develop.yml
- .github/workflows/branch_release.yml
- .github/workflows/published.yml
<details>
otherwise).
packages.
</details>
When calling another workflow, make sure it will inherit the secrets from its parent.
Jobs like [this](https://github.com/stellar/java-stellar-anchor-sdk/actions/runs/3137863047/jobs/5100787037) were failing because the secrets were not being passed from caller to callee.
GH covers this in https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/reusing-workflows#passing-secrets-to-nested-workflows.
> Fix: workflow secrets were not being passed from parent (caller) to child (callee) workflows

- platform/src/main/java/org/stellar/anchor/platform/callback/PlatformIntegrationHelper.java
<details>
otherwise).
packages.
</details>
Stop crashing when parsing response content into ErrorResponse.
So we can better debug what's causing an issue.
> Fix: stop crashing when parsing response content into ErrorResponse

- helm-charts/sep-service/Chart.yaml
- helm-charts/sep-service/example_values.yaml
- helm-charts/sep-service/templates/deployment.yaml
- helm-charts/sep-service/templates/ingress.yaml
- helm-charts/sep-service/templates/service.yaml
<details>
otherwise).
packages.
</details>
Add an option to make the Stellar observer into a separate deployment service.
Because it's recommended to use it as a separate service.
> Feature: separate observer deployment

- CHANGELOG.md
- build.gradle.kts
- core/src/test/kotlin/org/stellar/anchor/sep10/Sep10ServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep31/Sep31TransactionTest.kt
- platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep31RefundPayment.java
- platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep31Refunds.java
- platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep31Transaction.java
- platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep31TransactionStore.java
- platform/src/test/kotlin/org/stellar/anchor/platform/data/JdbcSep31TransactionTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/service/TransactionServiceTest.kt
closes #626 
<details>
otherwise).
packages.
</details>
Fix gson serialization error of the Refunds object.
Gson tries to serialize JdbcSep31Transaction.refunds, which is an interface. It is changed to JdbcSep31Refunds. 
Bug fixes.
Add `PATCH /transactions` to integration tests.
> Fix Sep31Transaction.refunds Gson serialization exception

- CHANGELOG.md
- anchor-reference-server/src/main/java/org/stellar/anchor/reference/event/KafkaListener.java
- api-schema/src/main/java/org/stellar/anchor/api/platform/HealthCheckResult.java
- build.gradle.kts
- core/src/main/java/org/stellar/anchor/healthcheck/HealthCheckProcessor.java
- core/src/main/java/org/stellar/anchor/util/ExponentialBackoffTimer.java
- docs/resources/docker-examples/kafka/docker-compose.yaml
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/AnchorPlatformIntegrationTest.kt
- platform/src/main/java/org/stellar/anchor/platform/configurator/ConfigManager.java
- platform/src/main/java/org/stellar/anchor/platform/controller/HealthController.java
- platform/src/main/java/org/stellar/anchor/platform/payment/observer/stellar/StellarPaymentObserver.java
- platform/src/main/java/org/stellar/anchor/platform/service/HealthCheckService.java
- platform/src/test/kotlin/org/stellar/anchor/platform/controller/HealthControllerTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/payment/observer/stellar/StellarPaymentObserverTest.kt
<details>
otherwise).
packages.
</details>
From Release 1.2.2.
1. Add silence watcher that sets the observer to SILENCE_ERROR when the SSEStream is silent for too long.
2. Add SSEStream failure handler that sets the observer to STREAM_ERROR when failed.
3. Add status watcher that decides to reconnect or to set the health status to RED depends on the reconnection/backoff timer status.
4. Add proper HTTP status code to the /health endpoint.
Merge from release 1.2.2
N/A
> observer: Merge 1.2.2 to `develop`

- platform/src/main/java/org/stellar/anchor/platform/config/PropertyAssetsConfig.java
- platform/src/main/java/org/stellar/anchor/platform/service/PropertyAssetsService.java
<details>
otherwise).
packages.
</details>
Added type and value checks to PropertyAssetsConfig.
When running sep server with empty configuration, it throws NPE because assets are not defined. Although this is expected, but not friendly. 
Validator checks will make catching errors earlier and easier to fix the issues without reading the stack trace.
N/A
> Add type and value checks to PropertyAssetsConfig

- docs/resources/deployment-examples/example-fargate/terraform/ecs.tf
- docs/resources/deployment-examples/example-fargate/terraform/security-groups.tf
- docs/resources/deployment-examples/example-fargate/terraform/sep_service.tf
- docs/resources/deployment-examples/example-fargate/terraform/task_def_stellar_observer.tf
This pull request fixes payment observer terraform.  It ensures resource naming is unique and adds the required service resources to enable payment observer as a separate service.
note, this was tested by deploying to fresh AWS account using terraform cloud and using stellar tests validation
introduction of payment observer task definition broke terraform for anchor playform for fargate.
https://stellarorg.atlassian.net/browse/ANCHOR-62
> Reece fixobserver

- docs/resources/deployment-examples/example-fargate/terraform/task_def_sep.tf
This PR is a hotfix to align the Fargate SEP10_SIGNING_SEED task definition container environment variable with the configuration file placeholder.]
_
Currently the configuration that gets deployed expects a variable named SEP10_SIGNING_SEED
```
sep10:
enabled: true
homeDomain: anchor-sep-preview-id.previews.kube001.services.stellar-ops.com
signingSeed: ${SEP10_SIGNING_SEED}
```
the Fargate Task Definition environment variable name is incorrectly named SEP_10_SIGNING_SEED
in this case, sep10 defaults (in code) are used.
> fix sep10 signing seed env variable name

- Dockerfile
This PR will enable our partners to add datadog tracing javaagent.  This will enable them to configure the datadog tracing agent so they can integrate AnchorPlatform java metrics into their datadog monitoring dashboards.
This PR will downloading the agent and enabling then partners can enable it via environment variables.
https://stellarorg.atlassian.net/browse/ANCHOR-82
> Datadog APM Support

- platform/src/main/java/org/stellar/anchor/platform/component/share/EventBeans.java
- platform/src/main/java/org/stellar/anchor/platform/event/KafkaEventPublisher.java
<details>
otherwise).
packages.
</details>
Fix ANCHOR-105.
- Set Kafka producer backoff timer starting from 1 second and max at 20 seconds.
- Disable Kafka producer if event service is not enabled.
Bug fixes.
N/A
> platform: [ANCHOR-105] Disable Kafka client if events.publisher.type is not KAFKA or event service is not enabled

- core/src/main/java/org/stellar/anchor/config/Sep1Config.java
- core/src/main/java/org/stellar/anchor/sep1/Sep1Service.java
- core/src/test/kotlin/org/stellar/anchor/sep1/Sep1ServiceTest.kt
- platform/src/main/java/org/stellar/anchor/platform/config/PropertySep1Config.java
- platform/src/test/kotlin/org/stellar/anchor/Sep1ServiceTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/config/Sep1ConfigTest.kt
<details>
otherwise).
packages.
</details>
Make PropertySep1Config.type as an enum
N/A
N/A
> core: [ANCHOR-49] Make PropertySep1Config.type as an enum

- core/src/main/java/org/stellar/anchor/config/MetricConfig.java
- platform/src/main/java/org/stellar/anchor/platform/component/share/MetricsBeans.java
- platform/src/main/java/org/stellar/anchor/platform/config/MetricConfig.java
- platform/src/main/java/org/stellar/anchor/platform/service/MetricEmitterService.java
<details>
otherwise).
packages.
</details>
1. Removed `MetricsConfig` interface.
2. Renamed `PropertyMetricsConfig` to `MetricsConfig`.
`MetricsConfig` interface is not necessary
N/A
> all: [ANCHOR-95] Removed MetricsConfig interface

- anchor-reference-server/src/main/java/org/stellar/anchor/reference/service/CustomerService.java
- api-schema/src/main/java/org/stellar/anchor/api/exception/Sep31AmbiguousCustomerInfoException.java
- core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java
- core/src/test/kotlin/org/stellar/anchor/sep31/Sep31ServiceTest.kt
<details>
otherwise).
packages.
</details>
Adding iteration over customer types in validateSenderAndReceiver.
Should fix #717. Previously, this method was searching for the customer with a first type in the map. Now, it searches for all types. 
Customer types must be mutually exclusive (i.e. same customer can NOT have multiple types at the same time)
> [Anchor-149] Fix customer type not being properly resolved (when multiple types are configured)

- .gitignore
- core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java
- core/src/main/java/org/stellar/anchor/sep24/Sep24Transaction.java
- core/src/main/java/org/stellar/anchor/sep24/Sep24TransactionBuilder.java
- core/src/main/java/org/stellar/anchor/util/MemoHelper.java
- core/src/test/java/org/stellar/anchor/sep24/PojoSep24Transaction.java
- platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep24Transaction.java
<details>
otherwise).
packages.
</details>
Adds `refund_memo` and `refund_memo_type` support to SEP-24 `POST /transactions/withdraw/interactive` request.
This was added to SEP-24. ([#1321](https://github.com/stellar/stellar-protocol/pull/1321))
> SEP-24: add `refund_memo` and `refund_memo_type` support

- .github/workflows/end_to_end_tests.yml
- Dockerfile
- anchor-reference-server/src/main/resources/anchor-reference-server-docker-compose-config.yaml
- docs/resources/deployment-examples/example-k8s/anchor-platform-dev/reference-server-config-map.yaml
- integration-tests/docker-compose-configs/anchor-platform-default-configs/anchor-platform-config.yaml
- integration-tests/docker-compose-configs/anchor-platform-unique-address/anchor-reference-server-config.yaml
- integration-tests/src/test/resources/integration-test.anchor-config.yaml
- platform/src/main/resources/anchor-docker-compose-config.yaml
<details>
otherwise).
packages.
</details>
Replace the Gradle build image to `gradle:jdk11-alpine`.
The `open-jdk:11-jdk` is not working fine in some environment.
> Change the gradle build image to gradle:jdk11-alpine

- anchor-reference-server/src/main/java/org/stellar/anchor/reference/model/Customer.java
- anchor-reference-server/src/main/java/org/stellar/anchor/reference/service/CustomerService.java
- api-schema/src/main/java/org/stellar/anchor/api/callback/PutCustomerRequest.java
- api-schema/src/main/java/org/stellar/anchor/api/sep/sep12/Sep12PutCustomerRequest.java
- core/src/main/java/org/stellar/anchor/sep9/Sep9Fields.java
- docs/03 - Implementing the Anchor Server/Communication/Callbacks API.yml
- end-to-end-tests/end_to_end_tests.py
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/Sep12Tests.kt
- platform/src/test/resources/stellar-anchor-tests-sep-config.json
<details>
otherwise).
packages.
</details>
Adds `bank_account_type` to the list of SEP-9 fields, with initial supported values of checking or savings. Some jurisdictions have banking systems that require that the account type be specified in addition to the account number.
Note that `bank_account_type` does not indicate the format of `bank_account_number`, and should not be used to validate `bank_account_number`.
If an anchor needs to be able to validate an account identifier, it should use other SEP-9 fields added specifically for the format they're looking to validate, such as `cbu_number` or `clabe_number`. These fields often contain pieces of information other than the …
> [Anchor-169] add bank_account_type in customer fields and SEP-9 fields

- platform/src/main/java/org/stellar/anchor/platform/service/PaymentOperationToEventListener.java
<details>
otherwise).
packages.
</details>
Change `amountExpected` to `amountIn`
`amountExpected` is amount passed from wallet as part of request. This field is optional and can be null. `amountIn` is either `amountExpected` (if not null) or amount set by the user in the web view. It's always non-null.
N/A/
> Small fix for payment observer

- anchor-reference-server/src/main/java/org/stellar/anchor/reference/config/KafkaListenerSettings.java
- anchor-reference-server/src/main/java/org/stellar/anchor/reference/event/KafkaListener.java
- anchor-reference-server/src/main/resources/anchor-reference-server-docker-compose-config.yaml
- anchor-reference-server/src/main/resources/anchor-reference-server.yaml
- docker-compose/anchor-get-started/common-services/reference-config.yaml
- docs/resources/deployment-examples/example-k8s/anchor-platform-dev/reference-server-config-map.yaml
- integration-tests/docker-compose-configs/anchor-platform-default-configs/anchor-reference-server-config.yaml
- integration-tests/docker-compose-configs/anchor-platform-unique-address/anchor-reference-server-config.yaml
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/AnchorPlatformIntegrationTest.kt
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/StellarObserverTests.kt
<details>
otherwise).
packages.
</details>
We are taking Kafka out from the integration tests. 
To accelerate the integration tests. The events/kafka are tested in e2e tests.
N/A
> Disable Kafka requirements for integration tests

- core/src/main/java/org/stellar/anchor/config/SecretConfig.java
- platform/src/main/java/org/stellar/anchor/platform/component/sep/SepBeans.java
- platform/src/main/java/org/stellar/anchor/platform/config/PropertyDataConfig.java
- platform/src/main/java/org/stellar/anchor/platform/config/PropertySecretConfig.java
- platform/src/main/java/org/stellar/anchor/platform/configurator/ConfigManager.java
- platform/src/main/java/org/stellar/anchor/platform/configurator/DataConfigAdapter.java
- platform/src/main/java/org/stellar/anchor/platform/configurator/EventProcessorConfigManager.java
- platform/src/main/java/org/stellar/anchor/platform/configurator/LogConfigAdapter.java
- platform/src/main/java/org/stellar/anchor/platform/configurator/ObserverConfigManager.java
- platform/src/main/java/org/stellar/anchor/platform/configurator/SecretManager.java
- platform/src/main/java/org/stellar/anchor/platform/configurator/SepConfigManager.java
- platform/src/main/java/org/stellar/anchor/platform/configurator/SpringConfigAdapter.java
<details>
otherwise).
packages.
</details>
When database credential is not provided, print error messages instead of exceptions. 
**Note**: The database initialization happens before the Spring validation framework. We need to do pre-Spring validation.
**Example output:**
username not set:
```
12:12:09.276 INFO  - o.s.a.p.c.SecretManager - Secret manager started.
12:12:09.291 INFO  - o.s.a.p.c.SepConfigManager - Read and process configurations
12:12:09.291 INFO  - o.s.a.p.c.ConfigManager - reading default configuration values
12:12:09.338 INFO  - o.s.a.p.c.ConfigManager - default configuration version=1
12:12:09.354 INFO  - o.s.a.p.c.ConfigManager - validating default …
```
> [ANCHOR-172] When database credential is not provided, print error messages instead of exceptions

- api-schema/src/main/java/org/stellar/anchor/api/platform/PlatformTransactionData.java
- api-schema/src/main/java/org/stellar/anchor/api/shared/Customers.java
- platform/src/main/java/org/stellar/anchor/platform/service/PaymentOperationToEventListener.java
- platform/src/main/java/org/stellar/anchor/platform/service/TransactionService.java
- platform/src/main/java/org/stellar/anchor/platform/utils/TransactionHelper.java
<details>
otherwise).
packages.
</details>
Small fixes.
1. Make it possible to update `stellarTransactionId` in patch (previously missed updates from payment observer). Also add it to `getTransaction`
2. Fix `amountExpected` in `getTransaction` (see comment)
3. Update customers logic. Now sender is always user account address (regardless of type). Receiver is set to null for deposit, and to `withdraw_anchor_account` for withdraw.
To make reference server work
N/A
> Fixes for stellarTransactionId and Customers

- .run/v2.0 - Platform Server - ServiceRunner [Integration Test Config].run.xml
- anchor-reference-server/src/main/resources/anchor-reference-server-docker-compose-config.yaml
- anchor-reference-server/src/main/resources/anchor-reference-server.yaml
- docker-compose/anchor-get-started/common-services/common-services.yaml
- docker-compose/anchor-get-started/sep24/docker-compose.yaml
- docker-compose/anchor-get-started/sep31/docker-compose.yaml
- docs/resources/deployment-examples/example-fargate/example_config/anchor_config.yaml
- helm-charts/sep-service/example_values.yaml
- integration-tests/docker-compose-configs/anchor-platform-default-configs/anchor-platform-config.yaml
- platform/src/main/java/org/stellar/anchor/platform/config/PropertyDataConfig.java
- platform/src/main/java/org/stellar/anchor/platform/configurator/ConfigHelper.java
- platform/src/main/java/org/stellar/anchor/platform/configurator/ConfigManager.java
- platform/src/main/java/org/stellar/anchor/platform/configurator/DataConfigAdapter.java
- platform/src/main/resources/anchor-docker-compose-config.yaml
- platform/src/main/resources/config/anchor-config-default-values.yaml
- platform/src/main/resources/config/anchor-config-schema-v1.yaml
- platform/src/main/resources/example.anchor-config.yaml
<details>
otherwise).
packages.
</details>
This is to replace `data.url` with `data.server` and `data.database` fields.
Here is the original data configuration:
```
data: 
url: jdbc:postgresql://127.0.0.1:5432/postgres
```
Here is the data configuration after the refactoring.
```
data:
type: postgres
server: 127.0.0.1:5432
database: postgres
```
This is to avoid mistakes while constructing database url string to reduce the user friction. 
N/A
> [ANCHOR-173] Removed data.url and add data.server and data.database fields

- platform/src/main/java/org/stellar/anchor/platform/component/sep/SepBeans.java
<details>
otherwise).
packages.
</details>
This is to fix:
```
When sep10.enabled is false or omitted, and secret.sep10.signing_seed / SECRET_SEP10_SIGNING_SEED is omitted, a null pointer exception is raised. I noticed that if I enable SEP-10, but omit the signing seed, this results in a user-friendly error message as expected.
The signing seed should not be required if SEP-10 is not enabled.
```
The bug is caused by creating Sep10Service bean when `sep10.enabled` is set to false. 
This fix avoids creating SEP service beans when the configuration is disabled. 
Bug fixes.
N/A
> [ANCHOR-174] Stop creating SEP service beans when disabled in configuration. (fix Sep10 npe)

- Dockerfile
<details>
otherwise).
packages.
</details>
Fix the Gradle build docker image to 7.6.0
We were using `gradle:jdk11` which gets upgraded to 8.x and breaks the Jenkins build. That is not desired. We are fixing it to `gradle:7.6.0-jdk11-alpine` to avoid unexpected issues.
N/A
> root: Fix the Gradle build docker image to gradle:7.6.0-jdk11-alpine

- core/src/main/java/org/stellar/anchor/auth/JwtService.java
- core/src/main/java/org/stellar/anchor/auth/Sep24InteractiveUrlJwt.java
- core/src/test/kotlin/org/stellar/anchor/auth/JwtServiceTest.kt
- platform/src/main/java/org/stellar/anchor/platform/service/SimpleInteractiveUrlConstructor.java
- platform/src/test/kotlin/org/stellar/anchor/platform/service/SimpleInteractiveUrlConstructorTest.kt
<details>
otherwise).
packages.
</details>
Add sub field to SEP24 interactive URL JWT. The `sub` field contains:
- Just account: `GASBFIRJMPVQGT66PLVGBLT37I3QDQSWYUIKZ3W7JJIJXB7SVB6KA7WM`
- Just account + memo:  `GASBFIRJMPVQGT66PLVGBLT37I3QDQSWYUIKZ3W7JJIJXB7SVB6KA7WM:123456`
- Mux account:  `GASBFIRJMPVQGT66PLVGBLT37I3QDQSWYUIKZ3W7JJIJXB7SVB6KA7WM:123456`
The mux account will be decoded and represented as just account + memo
The first step for building a business server will be to authenticate the user by verifying the JWT added to the interactive url by the Anchor Platform.
It is straightforward to verify the JWT’s signature using the shared secret, but it is less …
> [ANCHOR-176] Add sub field to SEP24 interactive URL JWT

- platform/src/main/java/org/stellar/anchor/platform/config/PropertySep24Config.java
- platform/src/test/kotlin/org/stellar/anchor/platform/config/Sep24ConfigTest.kt
<details>
otherwise).
packages.
</details>
Fix missing more_info URL JWT secret validation.
Here is the original bug report: 
================
If the developer does not configure `secret.sep24.more_info_url.jwt_secret` / `SECRET_SEP24_MORE_INFO_URL_JWT_SECRET`, requests to SEP-24’s `GET /transaction(s`) endpoints return 500 because the anchor platform cannot create the url tokens without the secret.
This makes the more info URL jwt secret a required environment variable. However, I suggest we make both the interactive url and more info url use the same jwt secret.
N/A
> [ANCHOR-175] Fix missing more_info URL JWT secret validation.

- core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java
<details>
otherwise).
packages.
</details>
Replaces the use of `token.getAccount()` with `token.getSub()` when generating the interactive URL JWT.
This fix ensures the interactive JWT includes the user's memo when the wallet is custodial. This bug is not present in the develop branch so no port is needed.
[TODO or N/A]
> core: use `token.getSub()` instead of `token.getAccount()` for interactive JWT

- CHANGELOG.md
- build.gradle.kts
- core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java
<details>
otherwise).
packages.
</details>
Commit Sep31 transaction to database before calling the unique_address endpoint
This is to fix the bug where the Sep31 transaction object is dirty after calling `txnStore.save()`. At that moment, the `unieuq_address` is called which in turn calls the `GET /transaction` endpoint to retrieve the saved transaction. 
N/A
> Release 1.2.9

- CHANGELOG.md
- build.gradle.kts
- core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java
<details>
otherwise).
packages.
</details>
Fix asset being set incorrectly when quote is null
Bug fix
N/A
> ANCHOR-227: Fix incorrect asset

- CHANGELOG.md
- build.gradle.kts
- core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java
<details>
otherwise).
packages.
</details>
Release 1.2.10
Release 1.2.10
N/A
> ANCHOR-227: Fix incorrect asset (#805)

- CHANGELOG.md
- platform/src/main/java/org/stellar/anchor/platform/service/TransactionService.java
<details>
otherwise).
packages.
</details>
Indicative quote fails validation in previous versions
Bug fix
N/A
> ANCHOR-231: Fix indicative quote fails validation

- platform/src/main/java/org/stellar/anchor/platform/configurator/ConfigEnvironment.java
- platform/src/test/kotlin/org/stellar/anchor/platform/configurator/ConfigManagerTest.kt
<details>
otherwise).
packages.
</details>
Fix the getenv method so it can handle line breaks /n and quotes /" when reading System envs
When providing a multiline env var with `\n`, it was being ingested as `\\n`. The same for quotes.
> fix: getenv so it can handle line breaks `/n` and quotes `/"` when reading System envs

- core/src/main/java/org/stellar/anchor/sep10/Sep10Service.java
- core/src/main/java/org/stellar/anchor/util/NetUtil.java
- core/src/test/kotlin/org/stellar/anchor/sep10/Sep10ServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/util/NetUtilTest.kt
- platform/src/main/java/org/stellar/anchor/platform/component/sep/SepBeans.java
- platform/src/main/java/org/stellar/anchor/platform/config/PropertySep10Config.java
- platform/src/main/resources/config/anchor-config-default-values.yaml
- platform/src/test/kotlin/org/stellar/anchor/platform/config/Sep10ConfigTest.kt
- service-runner/src/main/resources/profiles/default/config.env
- service-runner/src/main/resources/profiles/sep24/config.env
… host_url
<details>
otherwise).
packages.
</details>
When sep10.web_auth_domain is not set, it is default to the domain of host_ur. 
This is to simplify the `sep10.web_auth_domain` configuration and avoid configuration mistakes.
> [ANCHOR-233] When sep10.web_auth_domain is not set, it is default to the domain of host_url

- build.gradle.kts
- gradle/libs.versions.toml
- integration-tests/build.gradle.kts
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/Sep24End2EndTests.kt
- platform/src/main/java/org/stellar/anchor/platform/service/TransactionService.java
- service-runner/build.gradle.kts
- service-runner/src/main/kotlin/org/stellar/anchor/platform/TestProfileRunner.kt
<details>
otherwise).
packages.
</details>
Fix stellar_transaction_id is not set in DB 
Due to this bug stellar_transaction_id is not set in the result GET transaction response. Also, it's not possible to query by stellar_transaction_id.
Only works with the latest transaction's id. If multiple Stellar transactions are associated with the SEP transaction, only latest Stellar transaction will be visible.
> Fix stellar transaction id is not set properly

- kotlin-reference-server/src/main/kotlin/org/stellar/reference/plugins/Sep24Route.kt
- service-runner/src/main/java/org/stellar/anchor/platform/ServiceRunner.java
<details>
otherwise).
packages.
</details>
Remove stellar prefix for deposit and withdrawal
Stellar asset validation fails. Need this fix for development
[TODO or N/A]
> kotlin-reference-server: Remove stellar prefix for deposit and withdrawal

- build.gradle.kts
<details>
otherwise).
packages.
</details>
Change version to 2.0.0-rc.2
Release preparation.
N/A
> Bump version to 2.0.0-rc.2

- api-schema/src/main/java/org/stellar/anchor/api/sep/sep24/TransactionResponse.java
- core/src/main/java/org/stellar/anchor/sep24/Sep24Helper.java
- core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java
<details>
otherwise).
packages.
</details>
Make more_info_url to be mandatory
Previously, it was not being set in some statuses. This fixes it and removes default url (stellar.org)
N/A
> Make more_info_url to be mandatory

- api-schema/src/main/java/org/stellar/anchor/api/custody/fireblocks/CreateTransactionRequest.java
- platform/src/main/java/org/stellar/anchor/platform/config/FireblocksConfig.java
- platform/src/main/java/org/stellar/anchor/platform/controller/custody/PaymentController.java
- platform/src/main/java/org/stellar/anchor/platform/custody/PaymentService.java
- platform/src/main/java/org/stellar/anchor/platform/custody/fireblocks/FireblocksPaymentService.java
- platform/src/main/resources/config/anchor-config-default-values.yaml
- platform/src/main/resources/config/anchor-config-schema-v1.yaml
- platform/src/test/kotlin/org/stellar/anchor/platform/config/FireblocksConfigTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/custody/fireblocks/FireblocksPaymentServiceTest.kt
- platform/src/test/resources/custody/api/payment/fireblocks/create_new_transaction_payment_request.json
<details>
otherwise).
packages.
</details>
Added configuration for mapping stellar asset codes to fireblocks asset codes.
Platform can match Fireblocks asset codes to Stellat asset codes.
[TODO or N/A]
> SDFSOF-24 - Added mapping of stellar asset codes to fireblocks asset codes

- .run/Run - Java Reference Server - no Docker.run.xml
- .run/Run - Kotlin Reference Server - no Docker.run.xml
- .run/Run - SepServer - no Docker.run.xml
- platform/src/main/java/org/stellar/anchor/platform/config/PropertySep1Config.java
- platform/src/test/kotlin/org/stellar/anchor/Sep1ServiceTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/config/Sep1ConfigTest.kt
- service-runner/src/main/kotlin/org/stellar/anchor/platform/TestProfileRunner.kt
- service-runner/src/main/kotlin/org/stellar/anchor/platform/run_profiles/RunSEP24NoFrontend.kt
<details>
otherwise).
packages.
</details>
Fix ANCHOR-259: https://stellarorg.atlassian.net/browse/ANCHOR-259
Bug fixes.
> Fix the bug that allows SEP1_VALUE and SEP1_TYPE mapped to sep1.toml.value and sep1.toml.type

- platform/src/main/java/org/stellar/anchor/platform/configurator/ConfigManager.java
…prefix
<details>
otherwise).
packages.
</details>
Default STELLAR_ANCHOR_CONFIG to "file:" prefix if not specified.
This will make the configuration less confusing and more consistent.
> [ANCHOR-290] Default STELLAR_ANCHOR_CONFIG to "file:" prefix if not specified.

- .github/workflows/sub_stellar_anchor_tests.yml
- .github/workflows/wk_push_to_develop.yml
<details>
otherwise).
packages.
</details>
Remove `set-output` from Github worflows
The command is deprecated and will stop to work in 05/31/2023
N/A
> [ANCHOR-291] Fix: update Github workflow to remove deprecated commands

- kotlin-reference-server/src/main/resources/default-config.yaml
- platform/src/main/resources/example.anchor-config.yaml
<details>
otherwise).
packages.
</details>
The Kotlin reference server is using the same account to send deposit money [java-stellar-anchor-sdk/default-config.yaml at develop · stellar/java-stellar-anchor-sdk](https://github.com/stellar/java-stellar-anchor-sdk/blob/develop/kotlin-reference-server/src/main/resources/default-config.yaml#L9) as the withdraw flow.
When both transactions are submitted to the same block, the race condition causes tx_bad_seq error.
The reference server uses the same account as the CLIENT_WALLET_KEY. We should have another account dedicated for the Kotlin reference server.
> Fix tx_bad_seq error caused at Sep24End2EndTest.kt::`withdraw end-to-end flow()`

- platform/src/main/java/org/stellar/anchor/platform/service/TransactionService.java
- platform/src/test/kotlin/org/stellar/anchor/platform/service/TransactionServiceTest.kt
<details>
otherwise).
packages.
</details>
Add NPE catchs on sending PATCH transactions request
Return a understandable error response to the user instead of only Null exception error stack trace
The PATCH transactions endpoint will need more attention to handle failures of one or more transactions inside a list of transactions. Today the TransactionService returns a BadRequestException as soon as the first failure occurs, even if other transactions were already committed.
> [ANCHOR-205] Validate PATCH transactions request body.

- CHANGELOG.md
- build.gradle.kts
- core/src/main/java/org/stellar/anchor/sep38/Sep38Service.java
- core/src/test/kotlin/org/stellar/anchor/sep38/Sep38ServiceTest.kt
<details>
otherwise).
packages.
</details>
This fixes a bug in SEP-38 POST quote where the anchor platform recalculates buy and sell amounts even if a value is returned by `/rate` integration.
As part of the SEP-38 POST quote flow, `/rate` is called to return buy or sell amounts calculated by the business server.  These amounts should not be recalculated by the platform due to differences in decimal precision between the anchor platform and the business server.
N/A
> [ANCHOR-308] fix: Use amounts calculated by rate integration in SEP-38

- core/src/main/java/org/stellar/anchor/config/AppConfig.java
- core/src/main/java/org/stellar/anchor/config/Sep10Config.java
- core/src/main/java/org/stellar/anchor/sep10/Sep10Service.java
- core/src/test/kotlin/org/stellar/anchor/TestConstants.kt
- core/src/test/kotlin/org/stellar/anchor/filter/Sep10JwtFilterTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep10/Sep10ServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep24/Sep24ServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep31/Sep31ServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/util/LogTest.kt
- platform/src/main/java/org/stellar/anchor/platform/config/PropertyAppConfig.java
- platform/src/main/java/org/stellar/anchor/platform/config/PropertySep10Config.java
- platform/src/main/resources/config/anchor-config-default-values.yaml
- platform/src/main/resources/config/anchor-config-schema-v1.yaml
- platform/src/test/kotlin/org/stellar/anchor/platform/config/AppConfigTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/config/Sep10ConfigTest.kt
<details>
otherwise).
packages.
</details>
Remove host_url and review usages of web_auth_domain
Previously, host_url was not used outside of SEP-10. In addition, in some instances web_auth_domain was incorrectly used in place of home_domain
N/A
> [ANCHOR-311] Remove host_url and review usages of web_auth_domain

- build.gradle.kts
- platform/src/main/java/org/stellar/anchor/platform/component/share/RequestLoggerBeans.java
- platform/src/main/java/org/stellar/anchor/platform/component/share/SharedConfigBeans.java
- platform/src/main/java/org/stellar/anchor/platform/config/AppLoggingConfig.java
- platform/src/main/java/org/stellar/anchor/platform/configurator/LogConfigAdapter.java
- platform/src/main/java/org/stellar/anchor/platform/utils/RequestLoggerFilter.java
- platform/src/main/resources/config/anchor-config-default-values.yaml
- platform/src/main/resources/config/anchor-config-schema-v1.yaml
- platform/src/test/kotlin/org/stellar/anchor/platform/utils/RequestLoggerFilterTest.kt
- service-runner/src/main/kotlin/org/stellar/anchor/platform/TestProfileRunner.kt
- service-runner/src/main/resources/profiles/default/config.env
- service-runner/src/main/resources/profiles/sep24/config.env
<details>
otherwise).
packages.
</details>
- Add RequestLoggerFilter configuration
- Fix the bug when starting servers fail, the `TestProfileRunner` does not quite.
Prevent unintentional PII leak.
> [ANCHOR-283] Add RequestLoggerFilter configuration to prevent unintentional PII (sensitive) logs

- platform/src/main/java/org/stellar/anchor/platform/component/custody/CustodyBeans.java
- platform/src/main/java/org/stellar/anchor/platform/component/custody/FireblocksBeans.java
- platform/src/main/java/org/stellar/anchor/platform/controller/custody/CustodyTransactionController.java
- platform/src/main/java/org/stellar/anchor/platform/custody/CustodyTransactionService.java
- platform/src/main/java/org/stellar/anchor/platform/custody/fireblocks/FireblocksCustodyTransactionService.java
- platform/src/test/kotlin/org/stellar/anchor/platform/custody/CustodyTransactionServiceTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/job/FireblocksTransactionsReconciliationJobTest.kt
<details>
otherwise).
packages.
</details>
Added a memo_type validation for deposit case when integration with Fireblocks is enabled
Fireblocks doesn't supports memo of type hash. If send such memo Fireblocks returns 500 error code. That's why it's necessary to add a validation.
> custody-service: SDFSOF-55 - Added a memo_type validation when integration with Fireblocks is enabled

- .run/Test - Fireblocks End2End Test - no fullstack.run.xml
- .run/Test - Fireblocks End2End Test - with fullstack.run.xml
- build.gradle.kts
- platform/src/main/java/org/stellar/anchor/platform/component/sep/SepBeans.java
<details>
otherwise).
packages.
</details>
- Add possibility to run Custody End2End tests separately
- Fix issue with SEP-31 deposit info generator type
- Run Custody End2End tests using personal credentials
- Use Custody Server to generate SEP-31 deposit info
[TODO or N/A]
> SDFSOF-31: Add possibility to run Custody End2End tests separately

- integration-tests/src/test/kotlin/org/stellar/anchor/platform/DatabaseMigrationTests.kt
- platform/src/main/java/org/stellar/anchor/platform/observer/stellar/PaymentObservingAccountsManager.java
- platform/src/main/java/org/stellar/anchor/platform/observer/stellar/StellarPaymentObserver.java
- platform/src/main/java/org/stellar/anchor/platform/service/MetricEmitterService.java
- platform/src/main/java/org/stellar/anchor/platform/utils/DaemonExecutors.java
- platform/src/main/java/org/stellar/anchor/platform/utils/DaemonThreadFactory.java
- service-runner/src/main/kotlin/org/stellar/anchor/platform/TestProfileRunner.kt
<details>
otherwise).
packages.
</details>
We plan to run the action many times to increase the probability of the fix. 
[View List of GitHub Action Results](https://github.com/stellar/java-stellar-anchor-sdk/actions?query=branch%3Afeature%2Fanchor-330-fix-test-instability++). 
- Wait to make sure the servers are properly shutdown.
- Mark watcher threads as daemon to avoid blocking shutdown
Attempt to fix the racing condition where the servers were not shutdown before the next test starts. 
The gradle tests were not stable because we are getting BindException indicating address alreay in useerror. It looks like we are trying to start the servers while the previous tests were …
> [ANCHOR-330] Attempt to fix the racing condition where the servers were not shutdown before the next test starts

- integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/Sep24End2EndTests.kt
<details>
otherwise).
packages.
</details>
The default timeout configuration seems to set the socket timeout to a value too low (or null?) for the tests to run on my machine.
This is what I see when I run the tests. I'm not sure why this is passing in the CI build, maybe it's specific to platform.
```
io.ktor.client.network.sockets.SocketTimeoutException: Socket timeout has expired [url=http://localhost:8080/sep24/transactions/deposit/interactive, socket_timeout=unknown] ms
at io.ktor.client.plugins.HttpTimeoutKt.SocketTimeoutException(HttpTimeout.kt:239)
at io.ktor.client.engine.okhttp.OkUtilsKt.mapOkHttpException(OkUtils.kt:80)
at …
```
> Fix: Increase timeouts for anchor client in SEP-24 e2e test

- platform/src/main/java/org/stellar/anchor/platform/config/PropertySep10Config.java
- platform/src/test/kotlin/org/stellar/anchor/platform/config/Sep10ConfigTest.kt
<details>
otherwise).
packages.
</details>
Add validation that calls `ManageDataOperation.Builder` to validate the `homeDomain` and `webAuthDomain`.
Cath the errors early.
> [ANCHOR-328] Add homeDomain and webAuthDomain length validation 

- core/src/main/java/org/stellar/anchor/asset/DefaultAssetService.java
- core/src/test/kotlin/org/stellar/anchor/asset/DefaultAssetServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/dto/sep38/InfoResponseTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep38/Sep38ServiceTest.kt
- core/src/test/resources/test_assets.json
- core/src/test/resources/test_assets.json.quotes_required_but_not_supported
- core/src/test/resources/test_assets.yaml
- core/src/test/resources/test_native_asset_sep31.json.bad
- core/src/test/resources/test_native_asset_sep38.json.bad
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/Sep31Tests.kt
- service-runner/src/main/resources/config/assets.yaml
<details>
otherwise).
packages.
</details>
This disables SEP-31 and SEP-38 support for the native asset. It will be re-enabled again once E2E tests have been added for SEP-31.
SEP-31 has not been tested end-to-end with the native asset.
This is not a true feature flag, but we expect anchors to upgrade to a new AP version as E2E tests will likely uncover some bugs.
> [ANCHOR-343] Disable SEP-31 and SEP-38 for native asset

- platform/src/test/kotlin/org/stellar/anchor/platform/utils/RequestLoggerFilterTest.kt
<details>
otherwise).
packages.
</details>
`RequestLoggerFilterTest` is missing the `mockk` `unmockAll()` and `clearAllMocks()` which may cause subsequent tests to fail. 
Bug fixing.
> [ANCHOR-351] Add the missing unmock for RequestLoggerFilterTest

- platform/src/main/resources/config/anchor-config-default-values.yaml
- platform/src/main/resources/config/anchor-config-schema-v1.yaml
<details>
otherwise).
packages.
</details>
Add client_attribution to the configuration.
This is to support the client status callback feature.
> [ANCHOR-342] Add `clients` to the configuration

- platform/src/main/resources/config/anchor-config-default-values.yaml
<details>
otherwise).
packages.
</details>
Add `type` field to the client configuration. The required fields will change according to the `type` assigned.
To clearly distinguish the `custodial` and `noncustodial` wallet clients.
> [ANCHOR-342] Add `type` to clients configuration

- core/src/main/java/org/stellar/anchor/sep10/Sep10Helper.java
- core/src/main/java/org/stellar/anchor/sep10/Sep10Service.java
- core/src/test/kotlin/org/stellar/anchor/sep10/Sep10ServiceTest.kt
- platform/src/main/java/org/stellar/anchor/platform/config/ClientsConfig.java
- platform/src/main/resources/config/anchor-config-default-values.yaml
- platform/src/test/kotlin/org/stellar/anchor/platform/config/ClientsConfigTest.kt
<details>
otherwise).
packages.
</details>
Create client status call back configuration, validate both `custodial` and `non-custodial` type
Note that for non-custodial client with signing_key provided, we need to check it against TOML file. 
The function `fetchSigningKey` is a copy of `getClientAccountId`(which returns signing_key read from toml file) in `Sep10Service`,  I would love to extract this function to a helper class for reuse.
> [Anchor-338] Implement static status callback configuration

- api-schema/src/main/java/org/stellar/anchor/api/rpc/action/NotifyOnchainFundsReceivedRequest.java
- api-schema/src/main/java/org/stellar/anchor/api/rpc/action/NotifyRefundInitiatedRequest.java
- api-schema/src/main/java/org/stellar/anchor/api/rpc/action/NotifyRefundSentRequest.java
- core/src/main/java/org/stellar/anchor/sep24/Sep24Refunds.java
- core/src/main/java/org/stellar/anchor/util/AssetHelper.java
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/PlatformApiTests.kt
- platform/src/main/java/org/stellar/anchor/platform/action/ActionHandler.java
- platform/src/main/java/org/stellar/anchor/platform/action/NotifyOnchainFundsReceivedHandler.java
- platform/src/main/java/org/stellar/anchor/platform/action/NotifyRefundInitiatedHandler.java
- platform/src/main/java/org/stellar/anchor/platform/action/NotifyRefundSentHandler.java
- platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep24RefundPayment.java
- platform/src/main/java/org/stellar/anchor/platform/service/PaymentOperationToEventListener.java
<details>
otherwise).
packages.
</details>
Added handlers for notify_onchain_funds_received, notify_refund_initiated and notify_refund_sent
Those handlers handle status transfer and update corresponding data in the database
[TODO or N/A]
> SDFSOF-64 - Added handlers for notify_onchain_funds_received, notify_refund_initiated and notify_refund_sent.

- Dockerfile
- platform/src/main/java/org/stellar/anchor/platform/StellarObservingService.java
- platform/src/main/java/org/stellar/anchor/platform/payment/observer/stellar/StellarPaymentObserver.java
- platform/src/main/java/org/stellar/anchor/platform/service/AnchorMetrics.java
<details>
otherwise).
packages.
</details>
Bitso requested the observer to publish the latest block as a metric.
**Prometheus endpoint:**
```
http://localhost:18083/actuator/prometheus
```
**Response:**
```
stellar_payment_observer{status="latest_block_processed",} 386954.0
stellar_payment_observer{status="latest_block_read",} 386954.0
```
To detect if the observer is working and processing transactions.
> [ANCHOR-372] Add latest block metrics to payment observer

- api-schema/src/main/java/org/stellar/anchor/api/rpc/action/ActionMethod.java
- api-schema/src/main/java/org/stellar/anchor/api/rpc/action/NotifyRefundPendingRequest.java
- platform/src/main/java/org/stellar/anchor/platform/action/NotifyRefundPendingHandler.java
- platform/src/main/java/org/stellar/anchor/platform/action/NotifyRefundSentHandler.java
- platform/src/main/java/org/stellar/anchor/platform/component/platform/ActionBeans.java
- platform/src/test/kotlin/org/stellar/anchor/platform/action/NotifyRefundPendingHandlerTest.kt
<details>
otherwise).
packages.
</details>
Renamed notify_refund_initiated to notify_refund_pending
To be consistent with other events
[TODO or N/A]
> SDFSOF-118 - Renamed notify_refund_initiated to notify_refund_pending

- api-schema/src/main/java/org/stellar/anchor/api/rpc/action/DoStellarRefundRequest.java
- api-schema/src/main/java/org/stellar/anchor/api/rpc/action/NotifyRefundPendingRequest.java
- api-schema/src/main/java/org/stellar/anchor/api/rpc/action/NotifyRefundSentRequest.java
- platform/src/main/java/org/stellar/anchor/platform/action/DoStellarRefundHandler.java
- platform/src/main/java/org/stellar/anchor/platform/action/NotifyRefundPendingHandler.java
- platform/src/main/java/org/stellar/anchor/platform/action/NotifyRefundSentHandler.java
- platform/src/test/kotlin/org/stellar/anchor/platform/action/DoStellarRefundHandlerTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/action/NotifyRefundPendingHandlerTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/action/NotifyRefundSentHandlerTest.kt
<details>
otherwise).
packages.
</details>
Added validation for assets in actions
We should validate refund assets
[TODO or N/A]
> SDFSOF-120: Allow asset attribute in refund object

- platform/src/main/java/org/stellar/anchor/platform/action/NotifyTransactionExpiredHandler.java
- platform/src/test/kotlin/org/stellar/anchor/platform/action/NotifyTransactionExpiredHandlerTest.kt
<details>
otherwise).
packages.
</details>
Transaction status can't be changed to Expired after funds were received
If funds were received business should do refund
[TODO or N/A]
> SDFSOF-64 - Transaction status can't be changed to Expired after funds were received

- api-schema/src/main/java/org/stellar/anchor/api/shared/StellarPayment.java
- api-schema/src/main/java/org/stellar/anchor/api/shared/StellarTransaction.java
- api-schema/src/test/kotlin/org/stellar/anchor/api/shared/StellarPaymentTest.kt
- api-schema/src/test/kotlin/org/stellar/anchor/api/shared/StellarTransactionTest.kt
<details>
otherwise).
packages.
</details>
This adds the `JsonProperty` annotation to the nested `AnchorEvent` types so that Kafka's `JsonSerializer` can correctly serialize camel case fields.
Field names are incorrectly serialized for some parts of the AnchorEvent.
N/A
> [ANCHOR-393] Set JsonProperty for nested AnchorEvent types

- .github/workflows/release_main.yml
<details>
otherwise).
packages.
</details>
Disable the release to latest in 1.x branch.
Example bad workflow: https://github.com/stellar/java-stellar-anchor-sdk/actions/runs/5693240869
1.x releases are currently overwriting 2.x releases.
N/A
> [ANCHOR-399] Disable release to latest in 1.x branch

- core/src/main/java/org/stellar/anchor/sep24/Sep24Helper.java
- core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java
- platform/src/main/java/org/stellar/anchor/platform/component/eventprocessor/EventProcessorBeans.java
- platform/src/main/java/org/stellar/anchor/platform/component/sep/SepBeans.java
- platform/src/main/java/org/stellar/anchor/platform/component/share/UtilityBeans.java
- platform/src/main/java/org/stellar/anchor/platform/event/ClientStatusCallbackHandler.java
- platform/src/main/java/org/stellar/anchor/platform/event/EventProcessorManager.java
- platform/src/test/kotlin/org/stellar/anchor/platform/event/ClientStatusCallbackHandlerTest.kt
<details>
otherwise).
packages.
</details>
This is to fix the request body used in client status callback is not a Sep24GetTransactionResponse
original pr: https://github.com/stellar/java-stellar-anchor-sdk/pull/988
According to Sep24Controller, response from `/trasaction` is of `Sep24GetTransactionResponse` type, which should be the correct body format used in  callback
> [ANCHOR-244] Use Sep24GetTransactionResponse as response body in ClientStatusCallback

- core/src/main/java/org/stellar/anchor/auth/JwtService.java
- core/src/main/java/org/stellar/anchor/auth/Sep24InteractiveUrlJwt.java
- core/src/main/java/org/stellar/anchor/auth/Sep24MoreInfoUrlJwt.java
- core/src/test/kotlin/org/stellar/anchor/TestConstants.kt
- core/src/test/kotlin/org/stellar/anchor/auth/JwtServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep24/Sep24ServiceTest.kt
- platform/src/main/java/org/stellar/anchor/platform/component/sep/SepBeans.java
- platform/src/main/java/org/stellar/anchor/platform/component/share/UtilityBeans.java
- platform/src/main/java/org/stellar/anchor/platform/config/ClientsConfig.java
- platform/src/main/java/org/stellar/anchor/platform/service/SimpleInteractiveUrlConstructor.java
- platform/src/main/java/org/stellar/anchor/platform/service/SimpleMoreInfoUrlConstructor.java
- platform/src/main/java/org/stellar/anchor/platform/service/UrlConstructorHelper.java
- platform/src/test/kotlin/org/stellar/anchor/platform/config/Sep10ConfigTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/service/SimpleInteractiveUrlConstructorTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/service/SimpleMoreInfoUrlConstructorTest.kt
<details>
otherwise).
packages.
</details>
This sets `client_name` and `client_domain` for the JWTs generated by SEP-24. It also adds the missing `sub` claim to the more info URL JWT.
These claims are used to identify the wallet and user.
N/A
> [ANCHOR-397] Add missing claims to SEP-24 JWTs

- helm-charts/sep-service/Chart.yaml
- helm-charts/sep-service/templates/configmap.yaml
- helm-charts/sep-service/templates/deployment.yaml
This change updates the legacy/main-1.2 helm chart to externalize the optionalMetricsEnabled parameter and also add metrics port for the stellar observer.
* [x ] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
otherwise).
* [x ] This PR's title starts with name of package that is most changed in the PR, ex.
packages.
I have tested this PR using helm template command.  Results verified using example-values file and uncommenting the stellar observer section.
helm chart updates.
partner needs to access metrics port for observer in order to integrate with datadog.
also needs to enable the optionalmetrics and need this parameter available in helm chart values.
Test Evidence:
helm …
> ANCHOR-408 helm-charts/sep-service helm chart observer metrics

- .github/workflows/sub_gradle_test_and_build.yml
<details>
otherwise).
packages.
</details>
Skip spotless tasks in Github actions to accelerate the CI
Optimization
> Skip spotless tasks in Github actions to accelerate the CI

- helm-charts/sep-service/Chart.yaml
- helm-charts/sep-service/templates/configmap.yaml
- helm-charts/sep-service/templates/deployment.yaml
This is an update the the previous PR related to the change. Once the previous PR was deployed and helm chart published, we discovered that the metrics were not being exposed on 8082.  Upon investigating we learned that the observer metrics port is currently hardcoded to 18083.  This change exposes that metrics port for the observer service.  We will determine whether or not to refactor the helm chart to make this consistent and configurable for 1.X.
* [x ] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [x ] This PR avoids mixing refactoring changes with feature changes (split into two PRs
otherwise).
* [x ] This PR's title starts with name of package that is most changed in the PR, ex.
`paymentservice.stellar`, or `all` or `doc` if the changes are broad …
> ANCHOR-408 helm-chart/sep-service observer metrics port fix

- core/src/main/java/org/stellar/anchor/util/NetUtil.java
- core/src/test/kotlin/org/stellar/anchor/util/NetUtilTest.kt
- platform/src/main/java/org/stellar/anchor/platform/config/PropertySep10Config.java
- platform/src/test/kotlin/org/stellar/anchor/platform/config/Sep10ConfigTest.kt
<details>
otherwise).
packages.
</details>
Remove hostname lookup from Sep10Config validation
After discussion, we don't think this being necessary
> Remove hostname lookup from Sep10Config validation

- helm-charts/sep-service/Chart.yaml
- helm-charts/sep-service/templates/configmap.yaml
- helm-charts/sep-service/templates/deployment.yaml
<details>
This PR fixes Stellar Observer Deployment Annotations.  Currently they use the SEP Service Deployment annotations, due to a bug in the helm chart template.  Fixing indentation for annotation as well.
* [ x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [ x] This PR avoids mixing refactoring changes with feature changes (split into two PRs
otherwise).
* [x ] This PR's title starts with name of package that is most changed in the PR, ex.
packages.
```
helm template sep ~/dev/anchor-platform-1.x/java-stellar-anchor-sdk/helm-charts/sep-service -f ./values.yaml
values.yaml
...
stellarObserver:
enabled: true
deployment:
port: 8083
annotations:
prometheus.io/path: …
```
> Anchor-408 helm-charts/sep-service fix observer annotations

- integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/Sep24End2EndTests.kt
- platform/src/main/java/org/stellar/anchor/platform/configurator/ConfigMap.java
- platform/src/test/kotlin/org/stellar/anchor/platform/configurator/ConfigMapTest.kt
- service-runner/src/main/resources/profiles/sep24/config.env
<details>
otherwise).
packages.
</details>
All configs are loaded into a map before being sent to Spring. Currently, client configs are being overwritten at the client level with the format `clients[0].property` which will not overwrite the `clients` property from the default config. This commit fixes the property merging logic such that if it discovers an indexed property, it will attempt to remove any non-indexed property with the same name.
This is a bug in the configuration override logic.
The fix is ugly but I didn't want to spend too much time refactoring the configurator. A better fix would be to set the overriding properties at different precedence levels and just …
> [ANCHOR-407] Fix client config override

- anchor-reference-server/src/main/java/org/stellar/anchor/reference/event/KafkaListener.java
- api-schema/src/main/java/org/stellar/anchor/api/event/AnchorEvent.java
- platform/src/main/java/org/stellar/anchor/platform/event/KafkaSession.java
<details>
otherwise).
packages.
</details>
This fixes the same thing that https://github.com/stellar/java-stellar-anchor-sdk/pull/1011 does but uses Gson instead of adding the missing `JsonProperty` annotations.
I realized we can just use `StringSerializer` instead of `JsonSerialization` and manually serialize using Gson ourselves before sending it to Kafka.
N/A
> [ANCHOR-396] Use Gson for Kafka serialization/deserialization

- api-schema/src/main/java/org/stellar/anchor/api/event/AnchorEvent.java
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/Sep24End2EndTests.kt
<details>
otherwise).
packages.
</details>
This updates the `AnchorEvent`'s `type` serialization to use lowercase letters. This does not break anything because status callback has not been released yet.
`types` are lowercased in the docs. https://github.com/stellar/stellar-docs/blob/fa78b1f185b02cd17f3d38ae7ea93765a7c70c7f/openapi/anchor-platform/schemas.yml#L757C1-L760
N/A
> Fix: Use lowercase type names in AnchorEvent

- build.gradle.kts
- core/src/main/java/org/stellar/anchor/sep1/Sep1Service.java
- core/src/main/java/org/stellar/anchor/util/NetUtil.java
- core/src/main/java/org/stellar/anchor/util/Sep1Helper.java
- docs/00 - Stellar Anchor Platform.md
- platform/src/main/java/org/stellar/anchor/platform/config/PropertySep1Config.java
- platform/src/test/kotlin/org/stellar/anchor/Sep1ServiceTest.kt
This PR moves the exception obfuscation for the stellar toml file handling to the Toml module and out of NetUtil. The reason is that NetUtil fetch is a lower level function that is shared. Obfuscating the exception message may not be applicable for other usages. THis PR also logs the actual exception message so that it is available for troubleshooting. Added some additional test coverage for Sep1Helper as well.
PR Structure
[x ] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
This PR avoids mixing refactoring changes with feature changes (split into two PRs
otherwise).
[ x] This PR's title starts with name of package that is most changed in the PR, ex.
paymentservice.stellar, or all or doc if the changes are broad or impact many
packages.
> ANCHOR-403 Obfuscate Exception in Sep1Helper instead of NetUtil

- platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep24Transaction.java
- platform/src/main/resources/db/migration/V8__sep24_field_updates.sql
Remove `more_info_url` from sep24 database table. 
This field is not used.
./gradlew test
> [ANCHOR-416] Remove `more_info_url` from sep24 database table

- integration-tests/src/test/kotlin/org/stellar/anchor/platform/DatabaseMigrationTests.kt
The PostgresMigrationTest requires the SEP server up and running. This causes race condition where we  try to access the SEP1 toml while the server is still starting up.  
This PR removes the need to read the SEP-1 toml file in database migration tests.
To improve the test stability.
> [ANCHOR-426] Make database migration tests not require the servers to get up-running

- .github/workflows/sub_gradle_test_and_build.yml
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/ReferenceServer.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/callbacks/customer/CustomerRoute.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/callbacks/fee/FeeRoute.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/callbacks/rate/RateRoute.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/callbacks/rate/RateService.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/callbacks/test/TestCustomerRoute.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/callbacks/uniqueaddress/UniqueAddressRoute.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/dao/CustomerRepository.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/dao/QuoteRepository.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/data/Config.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/plugins/ConfigureRouting.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/plugins/RequestExceptionHandlerPlugin.kt
- kotlin-reference-server/src/main/resources/default-config.yaml
The changes include:
1. Introduces a new plugin to catch and map exceptions to a HTTP error code.
2. Put the `/invalidate_clabe` endpoint behind a configuration.
3. Re-introduces the SEP-12 validation from stellar-anchor-tests. Previously, when a GET /customer request does not include an account/memo, the query does not assert that they are null. This caused a race when updating an account that maps to many customers.
Address the comments from the previous PR https://github.com/stellar/java-stellar-anchor-sdk/pull/1060.
N/A
> [ANCHOR-295] Cleanup Kotlin referencer server implementation

- build.gradle.kts
- docs/README.md
Fix the mistakenly removed `printVersionName` Gradle task
The missing `printVersionName` causes docker publication failure.
NA
> Fix the mistakenly removed `printVersionName` Gradle task

- core/src/test/kotlin/org/stellar/anchor/sep1/Sep1ServiceTest.kt
Add missing `clearAllMocks()` calls in `Sep1ServiceTest`.
The `RequestLoggerFilterTest` fails from time to time. We suspect it is caused by some un-cleared static mocks from previous tests. 
However, I am not able to re-produce the issue at this moment. I made a fix based on possible un-cleared static mocks that may affect the stability of the tests. If the bug happens again, we should re-open this bug with detailed log messages.
> [ANCHOR-410] Add tear down process for the uncleared static mocks in SepServiceTest

- build.gradle.kts
- platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep24TransactionRepo.java
- platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep24TransactionStore.java
- platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep31TransactionRepo.java
- platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep31TransactionStore.java
- platform/src/main/java/org/stellar/anchor/platform/service/PaymentOperationToEventListener.java
- platform/src/test/kotlin/org/stellar/anchor/platform/service/PaymentOperationToEventListenerTest.kt
This PR does two things:
- The queries to fetch transactions from the database now uses the status that the transaction should be in as an additional filter in addition to the account and memo filters
- They also check for matches using the destination account of the payment rather than the source account of the payment
There is no reason to check for matches against transactions that are not in the status that indicates the transaction is ready to receive the payment.
We also need to match against the destination account because that is the account we're monitoring. The source accounts of payments are unpredictable.
We'll need to port this to 1.x
> ANCHOR-427: add status filter and use destination accounts for matching transactions in observer

- api-schema/src/main/java/org/stellar/anchor/api/platform/PlatformTransactionData.java
- core/src/main/java/org/stellar/anchor/util/TransactionHelper.java
Add missing refund memo to the platform trasaction 
N/A
> [Anchor-428] Add refund memo to platform transaction

- .github/pull_request_template.md
- .github/workflows/basic_tests.yml
Removes the SEP validation test suite from our CI pipeline.
Maintaining working preview deployments and using them for our SEP validation test suite is too high of a maintenance burden for the usage 1.x has in the ecosystem. We can run the same tests locally before releasing.
> remove SEP suite validation in 1.x actions

- api-schema/src/main/java/org/stellar/anchor/api/callback/SendEventRequest.java
- api-schema/src/main/java/org/stellar/anchor/api/callback/SendEventRequestPayload.java
- api-schema/src/main/java/org/stellar/anchor/api/platform/GetTransactionResponse.java
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/KotlinReferenceServerIntegrationTest.kt
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/Sep24End2EndTests.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/client/AnchorReferenceServerClient.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/data/Event.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/EventService.kt
**Lets hold off on this until we merge everything from SoftServe**
Updates the schema used when sending event callbacks to the business server.
Current schema:
```js
{
timestamp: 1693524508,
payload: {
type: 'transaction_created',
id: '19f8caad-0214-4ef3-99a6-134f59a3dbbe',
sep: '24',
transaction: {
id: '29f84658-7090-47b7-874d-5d4ffa592a39',
sep: '24',
kind: 'deposit',
status: 'incomplete',
amount_expected: [Object],
started_at: '2023-08-31T23:28:25.120858Z',
destination_account: 'GA57OTKBRMLNMYIMK3VL23HI6XVCB7P2H5Q353U3ZEQR6HIE5TBAXY3O'
}
}
}
```
New schema:
```js
{
id: '19f8caad-0214-4ef3-99a6-134f59a3dbbe',
timestamp: '2023-08-31T23:28:25.120858Z',
type: 'transaction_created',
payload: {
transaction: {
id: '29f84658-7090-47b7-874d-5d4ffa592a39',
sep: '24',
kind: 'deposit',
status: …
```
> [ANCHOR-435]: Update event callback schema

- core/src/main/java/org/stellar/anchor/sep38/Sep38Service.java
- core/src/test/kotlin/org/stellar/anchor/sep38/Sep38ServiceTest.kt
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/ApiKeyAuthIntegrationTest.kt
- platform/src/main/java/org/stellar/anchor/platform/controller/Sep38Controller.java
Add missing client_id to rate callback in SEP38 /price and /prices endpoints
Bug fix
> [ANCHOR-420] Add missing `client_id` to rate callback in SEP38 `/price` and `/prices` endpoints

- api-schema/src/main/java/org/stellar/anchor/api/sep/sep6/StartDepositRequest.java
- api-schema/src/main/java/org/stellar/anchor/api/sep/sep6/StartWithdrawRequest.java
- core/src/main/java/org/stellar/anchor/sep6/RequestValidator.java
- core/src/main/java/org/stellar/anchor/sep6/Sep6Service.java
- core/src/test/kotlin/org/stellar/anchor/sep6/RequestValidatorTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep6/Sep6ServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep6/Sep6ServiceTestData.kt
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/Sep6End2EndTest.kt
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/Sep6Tests.kt
- platform/src/main/java/org/stellar/anchor/platform/component/sep/SepBeans.java
- platform/src/main/java/org/stellar/anchor/platform/controller/sep/Sep6Controller.java
This change:
- Adds additional validation to SEP-6 deposit
- Adds `minAmount` and `maxAmount` validation to all operations
- Makes `type` and `amount` optional in `deposit` and `withdraw`
- Refactors the validation into its own class
During the testing of `stellar-anchor-tests`, it was discovered that `type` and `amount` are optional parameters for the `deposit` and `withdraw` endpoints. `Sep6Service` had a lot of code duplication so I decided to refactor the validation into its own class.
- `stellar-anchor-tests`
N/A
> [ANCHOR-353] SEP-6: Refactor request validation

- api-schema/src/main/java/org/stellar/anchor/api/platform/PlatformTransactionData.java
- api-schema/src/main/java/org/stellar/anchor/api/sep/sep6/StartDepositExchangeRequest.java
- core/src/main/java/org/stellar/anchor/sep6/Sep6Service.java
- core/src/test/kotlin/org/stellar/anchor/sep6/Sep6ServiceTest.kt
- platform/src/main/java/org/stellar/anchor/platform/component/sep/SepBeans.java
- platform/src/main/java/org/stellar/anchor/platform/controller/sep/Sep6Controller.java
This implements the GET `deposit-exchange` endpoint. There's a lot of duplicated code that could be shared with `deposit` and `withdraw`/`withdraw-exchange`. Once the integration and end-to-end tests have been implemented, I will focus on cleaning up the code.
SEP-6 implementation.
Integration and end-to-end tests are missing, they will be added in another PR.
> [ANCHOR-357] SEP-6: Implement deposit-exchange

- api-schema/src/main/java/org/stellar/anchor/api/callback/SendEventRequestPayload.java
- api-schema/src/main/java/org/stellar/anchor/api/exception/SepCustomerInfoNeededException.java
- api-schema/src/main/java/org/stellar/anchor/api/sep/CustomerInfoNeededResponse.java
- api-schema/src/main/java/org/stellar/anchor/api/sep/sep12/Sep12Status.java
- api-schema/src/main/java/org/stellar/anchor/api/sep/sep6/StartWithdrawExchangeRequest.java
- api-schema/src/main/java/org/stellar/anchor/api/sep/sep6/StartWithdrawRequest.java
- core/src/main/java/org/stellar/anchor/sep6/RequestValidator.java
- core/src/main/java/org/stellar/anchor/sep6/Sep6Service.java
- core/src/test/kotlin/org/stellar/anchor/sep6/RequestValidatorTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep6/Sep6ServiceTest.kt
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/Sep6End2EndTest.kt
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/Sep6Tests.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/data/Event.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/EventService.kt
- platform/src/main/java/org/stellar/anchor/platform/component/sep/SepBeans.java
- platform/src/main/java/org/stellar/anchor/platform/controller/AbstractControllerExceptionHandler.java
This adds a check to verify that a customer is SEP-12 accepted as part of the deposit/withdraw request validation. This also removes the `VERIFICATION_REQUIRED` status as it is not a valid SEP-12 customer info status.
This was caught by a `stellar-anchor-tests` test case.
- `stellar-anchor-tests`
N/A
> [ANCHOR-353] SEP-6: Verify SEP-12 status before deposit/withdraw proceeds

- core/src/main/java/org/stellar/anchor/config/Sep38Config.java
- core/src/test/kotlin/org/stellar/anchor/sep38/Sep38ServiceTest.kt
- integration-tests/src/main/kotlin/org/stellar/anchor/platform/Sep38Client.kt
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/Sep38Tests.kt
- platform/src/main/java/org/stellar/anchor/platform/component/sep/SepBeans.java
- platform/src/main/java/org/stellar/anchor/platform/config/PropertySep38Config.java
- platform/src/main/resources/config/anchor-config-default-values.yaml
- platform/src/main/resources/config/anchor-config-schema-v1.yaml
- platform/src/test/kotlin/org/stellar/anchor/platform/component/SepBeansTest.kt
Add sep38.requires_sep10 configuration with default value to FALSE
Currently, according to the SEP-38 spec, some of the SEP38 endpoints have SEP-10 as optional. This task seeks ensure we support this optionality by add configurability to these endpoints' SEP-10 requirements.
Tests were added to verify url pattern was added to filter if auth is required
> [Anchor-418] Support auth with SEP10 in SEP38

- api-schema/src/main/java/org/stellar/anchor/api/sep/sep6/InfoResponse.java
- core/src/main/java/org/stellar/anchor/sep6/Sep6Service.java
- core/src/test/kotlin/org/stellar/anchor/sep6/Sep6ServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep6/Sep6ServiceTestData.kt
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/Sep6Tests.kt
Since we are validating min/max amounts, if set, these should be show in the GET /info response.
These are currently missing from the info response.
N/A
> SEP-6: Show min/max amounts in the info response

- core/src/main/java/org/stellar/anchor/sep6/Sep6Service.java
- core/src/main/java/org/stellar/anchor/sep6/Sep6TransactionStore.java
- core/src/test/kotlin/org/stellar/anchor/sep6/Sep6ServiceTestData.kt
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/Sep6Tests.kt
- platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep6TransactionRepo.java
- platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep6TransactionStore.java
- platform/src/main/java/org/stellar/anchor/platform/service/PaymentOperationToEventListener.java
- platform/src/main/java/org/stellar/anchor/platform/service/TransactionService.java
- platform/src/test/kotlin/org/stellar/anchor/platform/service/PaymentOperationToEventListenerTest.kt
Removes the `to` account set by the withdraw endpoint.
`to` is an optional field in the transactions object, and is meant to store the user's off-chain account. This is not known at the time of transaction creation.
N/A
> SEP-6: Remove to account set by withdraw

- core/src/main/java/org/stellar/anchor/config/Sep1Config.java
- core/src/main/java/org/stellar/anchor/sep1/ISep1Service.java
- core/src/main/java/org/stellar/anchor/sep1/Sep1Service.java
- core/src/test/kotlin/org/stellar/anchor/sep1/Sep1ServiceTest.kt
- platform/src/main/java/org/stellar/anchor/platform/controller/sep/Sep1Controller.java
- platform/src/test/kotlin/org/stellar/anchor/Sep1ServiceTest.kt
- Restructure Sep1 service functions for extensibility and customizability.
- Replaced the static mocks with member functions of `Sep1Service`.
Core SDK release.
The test coverage is at 85%. This is because [the `TomlType` check ](https://github.com/lijamie98/java-stellar-anchor-sdk/blob/feature/anchor-497-sep1-refactor-core/core/src/main/java/org/stellar/anchor/sep1/Sep1Service.java#L45-L47)was not able to be tested. 
Also avoiding the static functions mocking also reduces the coverage.
> [ANCHOR-497]: Restructure Sep1Service functions for extensibility and customizability

- core/src/main/java/org/stellar/anchor/sep6/RequestValidator.java
- core/src/main/java/org/stellar/anchor/sep6/Sep6Service.java
- core/src/test/kotlin/org/stellar/anchor/sep6/RequestValidatorTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep6/Sep6ServiceTest.kt
SEP-6 will now check the KYC information of the SEP-10 account instead of the requested account.
The requested account is not the same as the SEP-10 account for custodial wallets.
N/A
> [Fix] SEP-6: Verify KYC of authenticated account

- core/src/main/java/org/stellar/anchor/sep6/RequestValidator.java
- core/src/main/java/org/stellar/anchor/sep6/Sep6Service.java
- core/src/main/java/org/stellar/anchor/sep6/Sep6Transaction.java
- core/src/main/java/org/stellar/anchor/sep6/Sep6TransactionBuilder.java
- core/src/main/java/org/stellar/anchor/util/TransactionHelper.java
- core/src/test/java/org/stellar/anchor/sep6/PojoSep6Transaction.java
- core/src/test/kotlin/org/stellar/anchor/TestConstants.kt
- core/src/test/kotlin/org/stellar/anchor/sep6/RequestValidatorTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep6/Sep6ServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep6/Sep6ServiceTestData.kt
- platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep6Transaction.java
- platform/src/main/resources/db/migration/V10__sep6_field_updates.sql
This sets the `customers`(See `TransactionSEP31` [docs](https://developers.stellar.org/api/anchor-platform/resources/get-transaction)) field in the SEP-6 platform transaction.
When the business server receives a transaction event, it needs to verify if the customer has enough KYC information to proceed with the transaction. Currently, the platform transaction only has `source_account` and `destination_account` fields which is not enough to identify users using a custodial wallet.
This persists SEP-12 customer IDs in the SEP-6 transaction table. SEP-12 customers can be deleted at any time, therefore an anchor may lose the mapping from transactions to these customers. This should be fine though since transactions would likely not move back into …
> [Fix] SEP-6: Set customers field in platform transaction

- Dockerfile
- core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java
- platform/src/main/java/org/stellar/anchor/platform/service/SimpleInteractiveUrlConstructor.java
- scripts/docker-start.sh
Add ability to pass JVM flags to docker container
Currently, we can't pass flags to the java command running in the container 
Manual testing: checked passing flags is working 
N/A
> ANCHOR-385: Add ability to pass JVM flags to docker container

- core/src/test/kotlin/org/stellar/anchor/auth/AuthHelperTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep10/Sep10ServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/util/LogTest.kt
- core/src/test/kotlin/org/stellar/anchor/util/NetUtilTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/callback/PlatformIntegrationHelperTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/configurator/ConfigManagerTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/service/RpcServiceTest.kt
- test-lib/src/main/kotlin/org/stellar/anchor/LockAndMockExtension.kt
- test-lib/src/main/kotlin/org/stellar/anchor/TestMutex.kt
Add @LockAndMockStatic and @LockStatic annotations. Instead of 
```kotlin
class MyTest {
@LockAndMockStatic([NetUtil::class]) 
fun myTest(){
lockAndMockStatic() {
// my tests here
}
}
}
```
the test method can be annotated with `@LockAndMockStatic`
```kotlin
@ExtendWith(LockAndMockTest::class) 
class MyTest {
@LockAndMockStatic([NetUtil::class]) 
fun myTest(){
}
}
```
To simplify the `lockAndMock` function.
> [ANCHOR-518] Add @LockAndMockStatic and @LockStatic annotations

- api-schema/src/main/java/org/stellar/anchor/api/platform/PlatformTransactionData.java
- core/src/main/java/org/stellar/anchor/util/TransactionHelper.java
This commit adds the `type` field to the SEP-6 platform transaction.
The `type` determines which fields need to be collected for KYC.
N/A
> [Fix] SEP-6: Add `type` to platform transaction

- core/src/main/java/org/stellar/anchor/config/Sep10Config.java
- core/src/main/java/org/stellar/anchor/sep10/Sep10Service.java
- core/src/test/kotlin/org/stellar/anchor/sep10/Sep10ServiceTest.kt
- platform/src/main/java/org/stellar/anchor/platform/config/PropertySep10Config.java
- platform/src/main/resources/config/anchor-config-default-values.yaml
- platform/src/main/resources/config/anchor-config-schema-v1.yaml
- platform/src/test/kotlin/org/stellar/anchor/platform/config/Sep10ConfigTest.kt
Add `home_domains` to SEP-10 to take a list of domains,
Rename `Sep10Config::getHomeDomain()` to  `Sep10Config::getHomeDomains()` to always return a list of available domains
`home_domain` and `home_domains` cannot coexist in Sep10Config, this is comment in default-value.yml, also enforced in validation rules
`web_auth_domain` will be required if there are more than 1 home domain specified in `home_domains`
The SDP multi-tenant integration will rely on multiple toml files, so we’ll need the Anchor Platform to accommodate that by allowing multiple home_domains to be configured, in the format of a comma-separated list of domains.
> [ANCHOR- 474]  Update SEP10.home_domain to accommodate multi-tenancy

- api-schema/build.gradle.kts
- build.gradle.kts
- core/build.gradle.kts
- integration-tests/build.gradle.kts
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/Sep12Tests.kt
- platform/build.gradle.kts
- scripts.gradle.kts
Extract the test concurrency settings to `scripts.gradle.kts` file
Refactoring
> Extract the test concurrency settings to `scripts.gradle.kts` file

- core/src/test/kotlin/org/stellar/anchor/sep10/Sep10ServiceTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/event/ClientStatusCallbackHandlerTest.kt
This fixes two test concurrency bugs due to static mocking.
1. `Sep10ServiceTest`:  the verify sees two calls to `Sep10Challenge#newChallenge`. My guess is that the `LockAndMockStatic` annotation does not know about `ParameterizedTest`s.
2. `Sep24ServiceTest`: the mock of `KeyPair` in `Sep10ServiceTest` to throw an exception causes the `Sep24Service` to throw it as well.
These two issues were only observed in the `sep-6` branch despite it using static mocks or touching existing tests.
Fixes test stability in `sep-6` branch.
- Ran `./gradlew test` a few times
N/A
This is only a temporary fix as it does not prevent us from writing similar tests in the future.
> [Fix] Fix test failures due to static mock race

- core/src/main/java/org/stellar/anchor/auth/JwtService.java
- platform/src/test/kotlin/org/stellar/anchor/platform/service/SimpleMoreInfoUrlConstructorTest.kt
Fix `SimpleMoreInfoUrlConstructorTest` calendar skew
The tests in `SimpleMoreInfoUrlConstructorTest` calls Calendar which may be statically mocked by other concurrent tests. Add `@LockStatic` to avoid the conflict. 
> [ANCHOR-522] Fix `SimpleMoreInfoUrlConstructorTest` calendar skew

- api-schema/src/main/java/org/stellar/anchor/api/platform/PlatformTransactionData.java
- platform/src/main/java/org/stellar/anchor/platform/service/TransactionService.java
- platform/src/test/kotlin/org/stellar/anchor/platform/service/TransactionServiceTest.kt
add `withdraw_anchor_account` to `PATCH /transactions` to support setting destination accounts for withdrawals dynamically
Today, the Anchor Platform sets `withdraw_anchor_account` to the value of the asset’s distribution account set in the config when the transaction is created.
Per partner request, support setting `withdraw_anchor_account` via `PATCH /transactions` – the address set can be different from the configured distribution account for the asset
- Added test case to verify `withdraw_anchor_account` is updated via patch /transaction
> [ANCHOR-476] add withdraw_anchor_account to PATCH /transactions

- .github/workflows/sub_gradle_test_and_build.yml
- api-schema/src/main/java/org/stellar/anchor/api/shared/StellarId.java
- core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java
- core/src/main/java/org/stellar/anchor/sep6/ExchangeAmountsCalculator.java
- core/src/main/java/org/stellar/anchor/sep6/RequestValidator.java
- core/src/main/java/org/stellar/anchor/sep6/Sep6Service.java
- core/src/main/java/org/stellar/anchor/sep6/Sep6Transaction.java
- core/src/main/java/org/stellar/anchor/sep6/Sep6TransactionBuilder.java
- core/src/main/java/org/stellar/anchor/sep6/Sep6TransactionUtils.java
- core/src/main/java/org/stellar/anchor/util/TransactionHelper.java
- core/src/test/java/org/stellar/anchor/sep6/PojoSep6Transaction.java
- core/src/test/kotlin/org/stellar/anchor/sep31/Sep31ServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep31/Sep31TransactionTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep6/ExchangeAmountsCalculatorTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep6/RequestValidatorTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep6/Sep6ServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep6/Sep6ServiceTestData.kt
- integration-tests/src/main/kotlin/org/stellar/anchor/platform/Sep6Client.kt
- integration-tests/src/test/kotlin/org/stellar/anchor/platform/test/Sep6Tests.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/processor/Sep6EventProcessor.kt
- platform/src/main/java/org/stellar/anchor/platform/component/sep/SepBeans.java
- platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep6Transaction.java
- platform/src/main/resources/db/migration/V10__sep6_field_updates.sql
- platform/src/test/kotlin/org/stellar/anchor/platform/rpc/DoStellarRefundHandlerTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/rpc/NotifyRefundSentHandlerTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/rpc/NotifyTransactionErrorHandlerTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/rpc/NotifyTransactionExpiredHandlerTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/rpc/NotifyTransactionRecoveryHandlerTest.kt
This removes KYC verification from the SEP-6 transaction initiation. Now that KYC is removed, the customer may not be known to the Anchor at the time of transaction initiation so the `customer` field cannot be set. To allow Anchors to associate SEP transactions with a customer, the SEP-10 account memo is now added as a field to the `StellarId` object. 
This means for the exchange endpoints, the platform can no longer make a request to the Fee integration as it requires setting SEP-12 sender and receiver fields. Business servers are expected to update the amounts asynchronously like they already do for regular fees.
KYC verification is done "interactively" in SEP-6.
Stellar docs need to be updated so that the `StellarId` object includes an optional `memo` field
N/A
> [ANCHOR-515] SEP-6: Remove KYC verification

- kotlin-reference-server/src/main/kotlin/org/stellar/reference/ReferenceServer.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/EventConsumer.kt
Cleanly shut down the reference server's Kafka consumer.
I am making this small change to test why the CI passes in PR, but not after merging into `sep-6` branch.
N/A
N/A
> [Fix] SEP-6: Shutdown the event consumer cleanly

- core/src/main/java/org/stellar/anchor/sep24/InteractiveUrlConstructor.java
- core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java
- core/src/test/kotlin/org/stellar/anchor/sep24/Sep24ServiceTest.kt
- platform/src/main/java/org/stellar/anchor/platform/service/SimpleInteractiveUrlConstructor.java
- platform/src/test/kotlin/org/stellar/anchor/platform/service/SimpleInteractiveUrlConstructorTest.kt
Fix account not being forwarded in SEP-9's /customer callback
When receiving callback for SEP-9 field forwarding all JWT fields (account and memo) was missing. Turned out, they were not being forwarded properly 
-  Adjusted test scenario 
There is a task for documenting this feature 
N/A
> [ANCHOR-526] Fix account not being forwarded in SEP-9's /customer callback

- core/src/main/java/org/stellar/anchor/sep24/InteractiveUrlConstructor.java
- core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java
- platform/src/main/java/org/stellar/anchor/platform/service/SimpleInteractiveUrlConstructor.java
- platform/src/test/kotlin/org/stellar/anchor/platform/service/SimpleInteractiveUrlConstructorTest.kt
Merges `develop` into `sep-6`.
Keep `sep-6` branch up to date.
N/A
N/A
> [Chore] Merge `develop` into `sep-6`

- build.gradle.kts
- docs/README.md
This bumps the version numbers to 2.4.0.
SEP-6 release
Stellar docs PR: https://github.com/stellar/stellar-docs/pull/253
N/A
> [Chore] Bump version to 2.4.0

- core/src/main/java/org/stellar/anchor/sep6/Sep6Service.java
- core/src/test/kotlin/org/stellar/anchor/sep6/Sep6ServiceTestData.kt
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/e2etest/Sep6End2EndTest.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/processor/Sep6EventProcessor.kt
- platform/src/main/java/org/stellar/anchor/platform/rpc/NotifyAmountsUpdatedHandler.java
- platform/src/test/kotlin/org/stellar/anchor/platform/rpc/NotifyAmountsUpdatedHandlerTest.kt
This fixes the implementation of the `NotifyAmountsUpdatedHandler` so that it matches the SEP-24 behaviour.
Previously, this was used incorrectly to update fees.
N/A
N/A
> [ANCHOR-525] SEP-6: Fix `NotifyAmountsUpdatedHandler`

- platform/src/main/java/org/stellar/anchor/platform/rpc/NotifyRefundPendingHandler.java
- platform/src/main/java/org/stellar/anchor/platform/rpc/NotifyRefundSentHandler.java
- platform/src/test/kotlin/org/stellar/anchor/platform/rpc/NotifyRefundPendingHandlerTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/rpc/NotifyRefundSentHandlerTest.kt
This adds the missing implementation for the `NotifyRefundSent` and the `NotifyRefundPending` RPC actions.
They were missed in the previous PRs.
N/A
N/A
> [ANCHOR-547] Fix: Add refunds pending/sent support for SEP-6

- core/src/main/java/org/stellar/anchor/sep6/Sep6Service.java
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/PlatformApiTests.kt
This adds basic RPC flow tests to the exchange endpoints.
Increasing test coverage.
N/A
N/A
> [ANCHOR-354] SEP-6: Add tests for exchange flow

- build.gradle.kts
- docs/01 - Contributing/A - Development Environment.md
- service-runner/build.gradle.kts
Add Gradle tasks to start servers and run docker compose up
Improve developer experience
Added instructions to how to contribute document.
> [ANCHOR-533] Add Gradle tasks to start servers and run docker compose up

- Dockerfile
- docs/resources/deployment-examples/example-fargate/Dockerfile
Update ubuntu to 22.04 from 20.04
We are updating all ubuntu base images in SDF projects to 22.04 LTS.
I built the docker image and it built successfully.
NA
NA
> Update ubuntu to 22.04 from 20.04

- build.gradle.kts
- docs/README.md
Bumps the version numbers to 2.5.0.
2.5.0 release
> Bump version to 2.5.0 

- build.gradle.kts
- docs/README.md
- platform/src/main/java/org/stellar/anchor/platform/component/sep/SepBeans.java
AP does not currently start up due to `ClientFinder` bean initialization.
`ClientFinder` bean initialization depends on both `sep6` and `sep24` being enabled in the config. It should initialize when either is enabled.
N/A
N/A
> [ANCHOR-567] Fix application startup without SEP-6 enabled

- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/e2etest/Sep31End2EndTests.kt
Wraps the SEP-31 test transaction submission in a retry.
Test stability improvement.
N/A
N/A
> [ANCHOR-566] [Fix] Wrap SEP-31 transaction submission in retry

- platform/src/main/java/org/stellar/anchor/platform/controller/HealthController.java
- platform/src/main/java/org/stellar/anchor/platform/controller/custody/CustodyHealthController.java
- platform/src/main/java/org/stellar/anchor/platform/controller/custody/CustodyPaymentController.java
- platform/src/main/java/org/stellar/anchor/platform/controller/custody/CustodyTransactionController.java
- platform/src/main/java/org/stellar/anchor/platform/controller/custody/CustodyWebhookController.java
- platform/src/main/java/org/stellar/anchor/platform/controller/observer/ObserverHealthController.java
- platform/src/main/java/org/stellar/anchor/platform/controller/platform/PlatformController.java
- platform/src/main/java/org/stellar/anchor/platform/controller/platform/PlatformHealthController.java
- platform/src/main/java/org/stellar/anchor/platform/controller/platform/PlatformRpcController.java
- platform/src/main/java/org/stellar/anchor/platform/controller/sep/Sep10Controller.java
- platform/src/main/java/org/stellar/anchor/platform/controller/sep/Sep12Controller.java
- platform/src/main/java/org/stellar/anchor/platform/controller/sep/Sep1Controller.java
- platform/src/main/java/org/stellar/anchor/platform/controller/sep/Sep24Controller.java
- platform/src/main/java/org/stellar/anchor/platform/controller/sep/Sep31Controller.java
- platform/src/main/java/org/stellar/anchor/platform/controller/sep/Sep38Controller.java
- platform/src/main/java/org/stellar/anchor/platform/controller/sep/Sep6Controller.java
- platform/src/main/java/org/stellar/anchor/platform/controller/sep/SepHealthController.java
This sets the content types for all SEP and Platform endpoints.
The default content for Spring `@RestController` is not `application/json`.
N/A
N/A
> [ANCHOR-543] Fix content types for SEP/Platform endpoints

- essential-tests/build.gradle.kts
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/PlatformApiTests.kt
- extended-tests/src/test/kotlin/org/stellar/anchor/platform/extendedtest/custody/CustodyApiTests.kt
- extended-tests/src/test/kotlin/org/stellar/anchor/platform/extendedtest/custody/PlatformApiCustodyTests.kt
Re-enable PlatformApiTests, PlatformApiCustodyTests, and CustodyApiTests
Fix test failures due to testnet resets
> [ANCHOR-575] Re-enable PlatformApiTests, PlatformApiCustodyTests, and CustodyApiTests

- kotlin-reference-server/src/main/kotlin/org/stellar/reference/data/Data.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/processor/Sep6EventProcessor.kt
- platform/src/main/java/org/stellar/anchor/platform/rpc/NotifyAmountsUpdatedHandler.java
- platform/src/main/java/org/stellar/anchor/platform/rpc/RequestOffchainFundsHandler.java
- platform/src/main/java/org/stellar/anchor/platform/rpc/RequestOnchainFundsHandler.java
- platform/src/main/java/org/stellar/anchor/platform/service/PaymentOperationToEventListener.java
- platform/src/test/kotlin/org/stellar/anchor/platform/rpc/NotifyAmountsUpdatedHandlerTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/rpc/RequestOffchainFundsHandlerTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/rpc/RequestOnchainFundsHandlerTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/service/PaymentOperationToEventListenerTest.kt
This updates the SEP-6 reference implement to support wallet testing. The following was fixed:
- More than one deposit/withdraw be requested without restarting the server
- Empty `amount` requests are now supported
This is required for wallet testing.
- Testing with the demo wallet
N/A
N/A
> [ANCHOR-549] Add demo wallet support to SEP-6 reference

- essential-tests/build.gradle.kts
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/e2etest/Sep24End2EndTests.kt
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/e2etest/Sep31End2EndTests.kt
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/StellarObserverTests.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/client/AnchorReferenceServerClient.kt
When the test parallelization is turned on, the essential tests may fail from time to time.
- The SSEStream may cause IOException that causes the SSEStream to restart and set the observer status to YELLOW.
- Remove the reference server event deletion that causes instability of event assertion.
- Log the events to find the root cause of the event assertion failure
Improve test stability.
> [ANCHOR-566] Fix the assertion failure caused by SSEStream connection reset that caused the status to become YELLOW and remove event deletion

- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/PlatformApiTests.kt
- extended-tests/src/test/kotlin/org/stellar/anchor/platform/extendedtest/custody/CustodyApiTests.kt
- extended-tests/src/test/kotlin/org/stellar/anchor/platform/extendedtest/custody/PlatformApiCustodyTests.kt
The platform tests hardcode transaction hashes that get erased after a Testnet reset. This commit updates the hardcoded values with new transactions.
Testnet reset broke these tests.
N/A
This will need to be repeated after the next Testnet reset. We need to look for a way around this.
> [ANCHOR-593] Fix extended tests post Testnet reset

- api-schema/src/main/java/org/stellar/anchor/api/callback/PutCustomerRequest.java
- core/src/main/java/org/stellar/anchor/sep12/Sep12Service.java
- core/src/test/kotlin/org/stellar/anchor/sep12/Sep12ServiceTest.kt
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/e2etest/Sep6End2EndTest.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/callbacks/customer/CustomerService.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/dao/CustomerRepository.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/dao/Customers.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/processor/Sep6EventProcessor.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/model/Customer.kt
This changes the `birth_date` type from an `Instant` to an ISO-8601 date validated String.
SEP-12 dates are ISO-8601 date strings.
N/A
N/A
> [ANCHOR-588] Fix `birth_date` field type

- kotlin-reference-server/src/main/resources/default-config.yaml
- service-runner/src/main/resources/common/docker-compose.yaml
Starts the platform server as part of docker compose up.
This is a bug fix for ANCHOR-563
- Testing with demo wallet after this is merged
N/A
N/A
> [Fix] Start platform server in docker compose

- docs/README.md
This adds the docker compose instructions to the README.
Previous commits added docker compose support.
- SEP-6 deposit and withdrawal flows tested with the demo wallet.
N/A
N/A
> [ANCHOR-563] Add run instructions to README

- api-schema/src/main/java/org/stellar/anchor/util/GsonUtils.java
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/Sep10Tests.kt
- lib-util/src/main/kotlin/org/stellar/anchor/client/Sep10Client.kt
This commit fixes the URL encoding of the challenge transaction returned by the SEP-10 endpoint. This is done by disabling the "HTML escaping" done by the Gson instance used throughout the project. It is safe to do so because Anchor Platform only returns HTTP responses with the `application/json` content type, which does not require URL encoding.
The challenge transaction returned by the `/auth` endpoint is not decodable.
N/A
N/A
> [ANCHOR-587] Disable URL encoding of SEP-10 challenge response

- core/src/main/java/org/stellar/anchor/sep10/Sep10Helper.java
- core/src/main/java/org/stellar/anchor/sep10/Sep10Service.java
- core/src/test/kotlin/org/stellar/anchor/TestConstants.kt
- core/src/test/kotlin/org/stellar/anchor/sep10/Sep10ServiceTest.kt
- platform/src/main/java/org/stellar/anchor/platform/config/PropertySep10Config.java
- platform/src/main/resources/config/anchor-config-default-values.yaml
- platform/src/test/kotlin/org/stellar/anchor/platform/config/Sep10ConfigTest.kt
Introduce the capability to use a wildcard prefix in the SEP10_HOME_DOMAINS configuration. This enhancement will allow for more dynamic and flexible domain management, especially beneficial in multi-tenant settings.
1. Support wildcard match (e.g., *.stellar.org).
2. To Ensure backward compatibility, the existing configurations with specific domains (e.g. ap.stellar.org) continue to work seamlessly.
> [ANCHOR-590] Support wildcard `homeDomains` for sep10

- core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java
- core/src/test/kotlin/org/stellar/anchor/sep24/Sep24ServiceTest.kt
- core/src/test/resources/test_assets.json
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/e2etest/Sep24End2EndTests.kt
Fix the copy paste bug in Sep24Service and Sep24ServiceTest
In the Sep24Service.deposit(...) method, we’re asserting for minAmount and maxAmount from the withdrawal config instead of the deposit config
-  This bug slipped through because majority of the parameter in our profile are set to the same. Having a variety of test scenarios helps us identify bugs in different conditions
> [ANCHOR-454][Easy] Fix copy paste bug in SEP24

- extended-tests/src/test/kotlin/org/stellar/anchor/platform/extendedtest/custody/CustodyApiTests.kt
- extended-tests/src/test/kotlin/org/stellar/anchor/platform/extendedtest/custody/PlatformApiCustodyTests.kt
This fixes the extended tests that broke after the Testnet reset.
N/A
- 
N/A
N/A
> [ANCHOR-608] Fix Testnet reset affected tests

- build.gradle.kts
- platform/src/main/java/org/stellar/anchor/platform/configurator/SpringFrameworkConfigurator.java
- platform/src/main/resources/log4j2-spring.yaml
Remove hardcoded DEBUG level of Stellar and add support of dynamic logging configuration reload
Previously, it was impossible to set DEBUG level to Stellar level config
Manually tested with different log levels
N/A
N/A
> [ANCHOR-610] Fix log level

- build.gradle.kts
- platform/src/main/java/org/stellar/anchor/platform/controller/GlobalControllerExceptionHandler.java
This lowers the log level and removes the stack trace for bad request exceptions. 
Our partners are monitoring ERROR logs. Bad requests are currently triggering their alarms.
- Manual testing by submitting bad requests creates `INFO` logs.
N/A
N/A
> [ANCHOR-616] Lower request validation error log level

- core/src/test/kotlin/org/stellar/anchor/sep10/Sep10ServiceTest.kt
- platform/src/main/resources/config/anchor-config-default-values.yaml
- platform/src/main/resources/config/anchor-config-schema-v1.yaml
Clean up dead code.
All uses has been removed in https://github.com/stellar/java-stellar-anchor-sdk/pull/1068
Better engineering
> [Dead Code] Clean up isKnownCustodialAccountRequired

- .github/workflows/sub_essential_tests.yml
- .github/workflows/sub_extended_tests.yml
- .github/workflows/sub_jacoco_report.yml
- docs/01 - Contributing/A - Development Environment.md
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/di/ServiceContainer.kt
- service-runner/src/main/resources/common/docker-compose.yaml
- service-runner/src/main/resources/docker-compose-test.yaml
- service-runner/src/main/resources/docker-compose.yaml
This adds a Postgres DB for the reference server.
We need a persistent data store for permanent deployment.
N/A
N/A
> [ANCHOR-391] Use Postgres in reference server

- build.gradle.kts
- platform/src/main/java/org/stellar/anchor/platform/controller/GlobalControllerExceptionHandler.java
This reduces the log levels for client-sided errors.
These are client-sided errors. They should be set to `info` as some partners are alerting on `error`.
N/A
N/A
> [Fix] Reduce log level for client errors

- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/e2etest/Sep6End2EndTest.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/ReferenceServer.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/data/Config.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/di/EventConsumerContainer.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/EventConsumer.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/EventRoute.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/EventService.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/processor/AnchorEventProcessor.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/processor/NoOpEventProcessor.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/processor/Sep6EventProcessor.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/processor/SepAnchorEventProcessor.kt
- kotlin-reference-server/src/main/resources/default-config.yaml
- service-runner/src/main/resources/docker-compose.yaml
Listens to webhooks instead of consuming directly from the internal `TRANSACTION` topic in the reference server.
This is the recommended approach for businesses building on the Anchor Platform.
N/A
N/A
> [ANCHOR-439] Listen to webhooks in reference server

- build.gradle.kts
- docs/README.md
- service-runner/src/main/resources/version-info.properties
Bumps version to 2.6.0. This also fixes the broken CI badge in the README.
2.6.0 release
N/A
N/A
> Bump version to 2.6

- Dockerfile
- docs/README.md
- service-runner/src/main/resources/common/docker-compose.yaml
This commit fixes the docker-compose stack. Also, this replaces the Anchor Platform image used by the stack with a locally built one.
Two things broke the stack:
- We are listening to webhook events instead of directly consuming Kafka, we need to start the `event-processor`.
- Docker ports were incorrectly mapped
- Tested SEP-6 deposit and withdrawal using demo-wallet
N/A
Future bugs like this will be difficult to catch without running automated tests against the docker-compose stack. Rather than directly running the `ServiceRunner` in GH actions, we can use docker-compose instead and run our tests against that.
> [ANCHOR-625] Fix docker compose stack

- platform/src/main/java/org/stellar/anchor/platform/configurator/ConfigManager.java
- platform/src/main/java/org/stellar/anchor/platform/configurator/ConfigMap.java
- platform/src/test/kotlin/org/stellar/anchor/platform/configurator/ConfigManagerTest.kt
The existing health check result dumps the full config with values. This replaces the result with a list of the configured keys instead.
Environment variables are being exposed by the `/health` endpoints.
N/A
N/A
> [ANCHOR-580] Replace ConfigManager HC result with config keys

- core/src/main/java/org/stellar/anchor/auth/AuthHelper.java
- core/src/main/java/org/stellar/anchor/filter/AbstractJwtFilter.java
- core/src/main/java/org/stellar/anchor/filter/ApiKeyFilter.java
- core/src/main/java/org/stellar/anchor/filter/CustodyAuthJwtFilter.java
- core/src/main/java/org/stellar/anchor/filter/PlatformAuthJwtFilter.java
- core/src/main/java/org/stellar/anchor/filter/Sep10JwtFilter.java
- core/src/test/kotlin/org/stellar/anchor/auth/AuthHelperTest.kt
- core/src/test/kotlin/org/stellar/anchor/filter/AbstractJwtFilterTest.kt
- core/src/test/kotlin/org/stellar/anchor/filter/ApiKeyFilterTest.kt
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/CallbackApiTests.kt
- platform/src/main/java/org/stellar/anchor/platform/component/custody/CustodyBeans.java
- platform/src/main/java/org/stellar/anchor/platform/component/platform/PlatformServerBeans.java
- platform/src/main/java/org/stellar/anchor/platform/component/share/CustodyApiBeans.java
- platform/src/main/java/org/stellar/anchor/platform/component/share/PlatformApiClientBeans.java
- platform/src/main/java/org/stellar/anchor/platform/config/CallbackApiConfig.java
[ANCHOR-618] Fix auth header not configurable for callback API and platform API
Bug fixes.
N/A
N/A
[ANCHOR-618]: https://stellarorg.atlassian.net/browse/ANCHOR-618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ANCHOR-618] Fix auth header not configurable for callback API and platform API

- core/src/main/java/org/stellar/anchor/sep10/Sep10Helper.java
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/EventProcessingTests.kt
- platform/src/main/java/org/stellar/anchor/platform/config/PropertySep10Config.java
- platform/src/main/resources/config/anchor-config-default-values.yaml
- platform/src/main/resources/config/anchor-config-schema-v1.yaml
- platform/src/main/resources/example.anchor-config.yaml
- platform/src/test/kotlin/org/stellar/anchor/platform/config/Sep10ConfigTest.kt
- service-runner/build.gradle.kts
- service-runner/src/main/resources/profiles/host-docker-internal/config.env
The `home_domain` was retained for backward compatibility purposes.  
Removed as part of the efforts for v3.0.
> [ANCHOR-640] Remove SEP10 home_domain

- helm-charts/reference-server/templates/configmap.yaml
- helm-charts/reference-server/templates/deployment.yaml
- helm-charts/reference-server/templates/externalsecrets.yaml
- helm-charts/reference-server/templates/service.yaml
- helm-charts/reference-server/values.yaml
- helm-charts/secret-store/templates/secretstore.yaml
- helm-charts/secret-store/values.yaml
- helm-charts/sep-service/templates/configmap.yaml
- helm-charts/sep-service/templates/eventprocessor-deployment.yaml
- helm-charts/sep-service/templates/eventprocessor-service.yaml
- helm-charts/sep-service/templates/externalsecrets.yaml
- helm-charts/sep-service/templates/observer-deployment.yaml
- helm-charts/sep-service/templates/observer-service.yaml
- helm-charts/sep-service/templates/platform-deployment.yaml
- helm-charts/sep-service/templates/platform-service.yaml
- helm-charts/sep-service/templates/sepserver-deployment.yaml
- helm-charts/sep-service/templates/sepserver-ingress.yaml
- helm-charts/sep-service/templates/sepserver-service.yaml
- helm-charts/sep-service/values.yaml
This parameterizes the secret keys by namespace.
Secrets are prefixed by namespace in SDF's Vault cluster.
- Testing with demo wallet.
N/A
N/A
> [ANCHOR-605] Parameterize secrets by namespace

- Makefile
This adds the missing Make targets.
This is used by the Jenkins pipeline to build and publish to the container registry.
N/A
N/A
> [ANCHOR-605] Add Makefile for Jenkins build

- core/src/main/java/org/stellar/anchor/util/TransactionHelper.java
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/EventProcessingTests.kt
- helm-charts/reference-server/templates/configmap.yaml
- helm-charts/reference-server/templates/deployment.yaml
- helm-charts/reference-server/templates/externalsecrets.yaml
- helm-charts/reference-server/templates/service.yaml
- helm-charts/reference-server/values.yaml
- helm-charts/secret-store/templates/secretstore.yaml
- helm-charts/secret-store/values.yaml
- helm-charts/sep-service/templates/configmap.yaml
- helm-charts/sep-service/templates/eventprocessor-deployment.yaml
- helm-charts/sep-service/templates/eventprocessor-service.yaml
- helm-charts/sep-service/templates/externalsecrets.yaml
- helm-charts/sep-service/templates/observer-deployment.yaml
- helm-charts/sep-service/templates/observer-service.yaml
- helm-charts/sep-service/templates/platform-deployment.yaml
- helm-charts/sep-service/templates/platform-service.yaml
- helm-charts/sep-service/templates/sepserver-deployment.yaml
- helm-charts/sep-service/templates/sepserver-ingress.yaml
- helm-charts/sep-service/templates/sepserver-service.yaml
- helm-charts/sep-service/values.yaml
- platform/src/main/java/org/stellar/anchor/platform/component/sep/SepBeans.java
- platform/src/main/java/org/stellar/anchor/platform/component/share/UtilityBeans.java
- platform/src/main/java/org/stellar/anchor/platform/service/Sep24MoreInfoUrlConstructor.java
- platform/src/main/java/org/stellar/anchor/platform/service/Sep6MoreInfoUrlConstructor.java
- platform/src/main/java/org/stellar/anchor/platform/service/SimpleInteractiveUrlConstructor.java
- platform/src/main/java/org/stellar/anchor/platform/service/SimpleMoreInfoUrlConstructor.java
- platform/src/main/java/org/stellar/anchor/platform/service/UrlConstructorHelper.java
- platform/src/test/kotlin/org/stellar/anchor/platform/service/Sep24MoreInfoUrlConstructorTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/service/SimpleInteractiveUrlConstructorTest.kt
Use platform API fields for the SEP-24 and SEP-6 txn_fields extractions for more info URL and interactive URLs.
Feature enhancement
- Update `txn_fields` description for stellar doc. 
- [ANCHOR-647](https://stellarorg.atlassian.net/browse/ANCHOR-647)
[ANCHOR-647]: https://stellarorg.atlassian.net/browse/ANCHOR-647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ANCHOR-635] Use platform API fields for the SEP-24 and SEP-6 `txn_fields` extractions

- core/src/main/java/org/stellar/anchor/MoreInfoUrlConstructor.java
- core/src/main/java/org/stellar/anchor/sep24/Sep24Helper.java
- core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java
- core/src/main/java/org/stellar/anchor/sep6/Sep6Service.java
- core/src/main/java/org/stellar/anchor/sep6/Sep6TransactionUtils.java
- core/src/test/kotlin/org/stellar/anchor/sep24/Sep24ServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep6/Sep6ServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep6/Sep6TransactionUtilsTest.kt
- platform/src/main/java/org/stellar/anchor/platform/component/sep/SepBeans.java
- platform/src/main/java/org/stellar/anchor/platform/event/ClientStatusCallbackHandler.java
- platform/src/main/java/org/stellar/anchor/platform/service/Sep24MoreInfoUrlConstructor.java
- platform/src/main/java/org/stellar/anchor/platform/service/Sep6MoreInfoUrlConstructor.java
- platform/src/main/java/org/stellar/anchor/platform/service/SimpleMoreInfoUrlConstructor.java
- platform/src/test/kotlin/org/stellar/anchor/platform/event/ClientStatusCallbackHandlerTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/service/Sep24MoreInfoUrlConstructorTest.kt
We receive a lang parameter as part of the requests (GET /transaction and GET /transactions) 
Right now the generated more_info_url doesn’t have this request argument forwarded to the JWT, which should be used by the Anchor’s UI
> [ANCHOR-629] Add `lang` to more_info_url jwt

- helm-charts/sep-service/templates/sepserver-ingress.yaml
This sets the `ingress.rules.host` to the value set by the same name in the values file.
Bug discovered during development deployment.
N/A
N/A
> [ANCHOR-605] Fix ingress rules host value

- helm-charts/sep-service/templates/sepserver-ingress.yaml
This fixes the Ingress rules host value.
It should be set to `ingress.rules.host` instead of `ingress.rules`. This is currently causing deployment failure.
```
client.go:261: [debug] error updating the resource "anchor-platform-sep-server":
cannot patch "anchor-platform-sep-server" with kind Ingress: Ingress.networking.k8s.io "anchor-platform-sep-server" is invalid: spec.rules[0].host: Invalid value: "map[host:anchor-sep-server-dev.stellar.org]": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
- Checked the YAML generated by `helm template`
N/A
N/A
> [Fix] Properly set ingress rules host

- .github/dependabot.yml
Create dependabot to auto update dependency
> [ANCHOR-680] Create dependabot.yml

- .github/dependabot.yml
As title. 
Updates on every version are causing spamming and instability
Reference: [Specifying dependencies and versions to ignore](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore)
> [ANCHOR-680] Enable only security updates for Dependabot

- platform/src/main/java/org/stellar/anchor/platform/config/PropertySep10Config.java
The error message is confusing because the actual limitation is 59 bytes.
```
The sep10.home_domain (%s) is longer than the maximum length (64) of a domain. Error=%s
``` 
Bug fix.
N/A
N/A
> [ANCHOR-681] Fix the 64-byte limit error message to 59-byte of the `sep10.home_domain` and `sep10.home_domains`

- helm-charts/reference-server/templates/deployment.yaml
A previous commit refactored the config map by moving `horizonEndpoint` into the values file but did not set the associated environment variable.
The reference server is crashing in dev.
- Tested with demo wallet.
N/A
N/A
> Fix reference server config map

- helm-charts/reference-server/templates/deployment.yaml
- helm-charts/sep-service/templates/eventprocessor-deployment.yaml
- helm-charts/sep-service/templates/observer-deployment.yaml
- helm-charts/sep-service/templates/platform-deployment.yaml
- helm-charts/sep-service/templates/sepserver-deployment.yaml
This allows pod-level annotations to be set.
We need to tell which port and endpoint Prometheus should scrape the metrics from using annotations.
- Verified the manifest is correctly generated using `helm template`
N/A
N/A
> [ANCHOR-604] Add deployment annotations

- platform/src/main/java/org/stellar/anchor/platform/component/share/MetricsBeans.java
- platform/src/main/java/org/stellar/anchor/platform/config/MetricConfig.java
- platform/src/main/resources/config/anchor-config-default-values.yaml
- platform/src/main/resources/config/anchor-config-schema-v1.yaml
This adds the `metric.prefix` configuration. When set, all metrics will be prefixed with the specified prefix value.
We need to prefix all metrics with `ap` for Prometheus.
- Checked the metrics have the specified endpoint when set, and nothing when not set.
N/A
N/A
> [ANCHOR-605] Enable metric prefix

- api-schema/src/main/java/org/stellar/anchor/api/rpc/method/NotifyRefundPendingRequest.java
- api-schema/src/main/java/org/stellar/anchor/api/shared/Refunds.java
- api-schema/src/main/java/org/stellar/anchor/api/shared/SepRefunds.java
- core/src/main/java/org/stellar/anchor/sep24/Sep24Refunds.java
- core/src/test/java/org/stellar/anchor/sep24/PojoSep24Refunds.java
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/PlatformApiTests.kt
- platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep24Refunds.java
- platform/src/main/java/org/stellar/anchor/platform/rpc/NotifyRefundPendingHandler.java
- platform/src/main/java/org/stellar/anchor/platform/rpc/RpcMethodHandler.java
- platform/src/test/kotlin/org/stellar/anchor/platform/rpc/NotifyRefundPendingHandlerTest.kt
Add support for withdrawals for existing `notify_refund_pending` RPC method
I noticed refunds are not available for `pending_user_transfer_complete` and `pending_external statuses`.
Generally speaking, in the regular flow transaction goes from `pending_user_transfer_start` -> `pending_anchor` -> `completed`
However, when the anchor takes times to process a transaction and it's still in `pending_anchor` , user wants to refund it and can do so.
In the cases where status is `pending_user_transfer_complete` (funds are available for pickup) or `pending_external` (funds are processed by external entity) we want to fist move it to `pending_anchor` to indicate that funds are not available for pickup anymore, (or that bank transfer was cancelled), i.e. indicate that refund has been initiated.
In …
> Add withdrawal support for notify_refund_pending RPC method

- platform/src/main/java/org/stellar/anchor/platform/config/PropertyAppConfig.java
- platform/src/main/resources/example.anchor-config.yaml
Add Futurenet in Network config
Previously, Futurenet was not supported 
N/A
N/A
> Add Futurenet in Network config

- platform/src/main/java/org/stellar/anchor/platform/observer/stellar/PaymentObservingAccountsManager.java
Reduce log level of PaymentObservingAccountsManager to DEBUG
Current log level is INFO, and it prints debugging information
N/A
N/A
N/A
> Reduce log level

- core/src/main/java/org/stellar/anchor/auth/JwtService.java
- core/src/test/kotlin/org/stellar/anchor/auth/AuthHelperTest.kt
Fix bug when exception was thrown on null platformSecret for callback/custody secret encoding 
Wrong secret was checked for being null
- /gradlew test
- Changed existing test to reproduce
N/A
N/A
> Fix bug in JWT service

- core/src/main/java/org/stellar/anchor/client/ClientFinder.java
- core/src/main/java/org/stellar/anchor/config/ClientsConfig.java
- core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java
- core/src/test/kotlin/org/stellar/anchor/sep31/Sep31ServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/util/ClientFinderTest.kt
- platform/src/main/java/org/stellar/anchor/platform/component/share/ClientsBeans.java
- platform/src/main/java/org/stellar/anchor/platform/config/PropertyClientsConfig.java
- platform/src/main/java/org/stellar/anchor/platform/config/PropertySep10Config.java
- platform/src/main/java/org/stellar/anchor/platform/event/EventProcessorManager.java
- platform/src/main/resources/config/anchor-config-default-values.yaml
- platform/src/test/kotlin/org/stellar/anchor/platform/config/PropertyClientsConfigTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/config/Sep10ConfigTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/service/Sep24MoreInfoUrlConstructorTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/service/SimpleInteractiveUrlConstructorTest.kt
- Deprecate `signing_key` and `domain`, replace with `signing_keys` and `domains`
- Remove `signing_key` field for noncustodial client (usage only found in validation)
- Replace the use of `signing_key` and `domain` with `signing_keys` and `domains` in related function and test cases
Will update in https://developers.stellar.org/network/anchor-platform/admin-guide/sep10
> [ANCNHOR-626] Update ClientsConfig with SigningKeys and Domains

- build.gradle.kts
- docs/README.md
- service-runner/src/main/resources/version-info.properties
Bumps the version numbers to 2.7.0.
2.7.0 release
> Bump version 2.7.0

- api-schema/build.gradle.kts
- core/build.gradle.kts
- essential-tests/build.gradle.kts
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/e2etest/Sep24End2EndTests.kt
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/e2etest/Sep31End2EndTests.kt
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/e2etest/Sep6End2EndTest.kt
- extended-tests/build.gradle.kts
- extended-tests/src/test/kotlin/org/stellar/anchor/platform/extendedtest/rpc/RpcEnd2EndTests.kt
- platform/build.gradle.kts
Disable the Junit concurrency for test stability reason. 
The tests had been unstable due to the concurrency that fails some of the tests. 
- The workflow is successful for 5 consecutive runs.
NA.
NA.
> [ANCHOR-692] Disable JUnit test parallel execution

- platform/src/main/java/org/stellar/anchor/platform/component/sep/SepBeans.java
- platform/src/main/java/org/stellar/anchor/platform/component/share/ObservingAccountsBeans.java
- platform/src/main/java/org/stellar/anchor/platform/observer/stellar/PaymentObservingAccountsManager.java
This PR add check to `ObservingAccountsBeans ` to check if SEP-31 is enabled. In this case the bean is always created, but only activate if SEP-31 is enabled.
This is because this bean is required in the presence for the creation of `PaymentObserverBeans`. We can't simply use conditional annotation that disable the bean's creation
The PaymentObseringAccountManager should only be restarted when needed. Currently only SEP-31 requires the service.
> [ANCHOR-698] Enable PaymentObservingAccountsManager for SEP-31 only

- .github/workflows/sub_essential_tests.yml
- core/src/main/java/org/stellar/anchor/sep24/Sep24RefundPayment.java
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/Sep24Tests.kt
- platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep24RefundPayment.java
- platform/src/main/java/org/stellar/anchor/platform/event/ClientStatusCallbackHandler.java
- platform/src/main/java/org/stellar/anchor/platform/rpc/NotifyRefundPendingHandler.java
- platform/src/main/java/org/stellar/anchor/platform/rpc/NotifyRefundSentHandler.java
- platform/src/test/kotlin/org/stellar/anchor/platform/rpc/DoStellarRefundHandlerTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/rpc/NotifyRefundPendingHandlerTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/rpc/NotifyRefundSentHandlerTest.kt
As title
id_type is part of refunds' payments object schema
However, it’s missing in JdbcSep24RefundPayment object
- `./gradlew test
Right now SEP6/24/31 are using different pattern for refund payment and that should be unified
> [ANCHOR-695] Add missing `idType` to `JdbcSep24RefundPayment`

- service-runner/src/main/resources/common/docker-compose.yaml
- service-runner/src/main/resources/docker-compose-test.yaml
- service-runner/src/main/resources/docker-compose.yaml
This removes the version field from the docker compose YAMLs.
This field is obsolete and is preventing the `TestProfileRunner` from starting up the dependencies.
```
Exception in thread "main" com.palantir.docker.compose.execution.DockerExecutionException: 'docker-compose ps -q time="2024-06-10T15:15:34-04:00" level=warning msg="/Users/philipliu/Documents/work/java-stellar-anchor-sdk/service-runner/out/production/resources/docker-compose-test.yaml: `version` is obsolete"' returned exit code 1
The output was:
time="2024-06-10T15:15:34-04:00" level=warning msg="/Users/philipliu/Documents/work/java-stellar-anchor-sdk/service-runner/out/production/resources/docker-compose-test.yaml: `version` is obsolete"
no such service: time="2024-06-10T15:15:34-04:00" level=warning …
```
> Remove version from docker-compose YAMLs

- .github/workflows/on_pull_request.yml
This PR temporarily disables extended tests.
The custody API tests depend on Circle USDC, which was not issued when creating this PR. They will be re-enabled when Circle USDC is available.
N/A
N/A
> Temporarily disable extended tests

- api-schema/src/main/java/org/stellar/anchor/api/callback/GetCustomerRequest.java
- api-schema/src/main/java/org/stellar/anchor/api/callback/PutCustomerRequest.java
- api-schema/src/main/java/org/stellar/anchor/api/sep/sep12/Sep12GetCustomerRequest.java
- api-schema/src/main/java/org/stellar/anchor/api/sep/sep12/Sep12PutCustomerRequest.java
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/callbacks/customer/CustomerService.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/dao/TransactionKYCRepository.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/dao/TransactionKYCs.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/di/ServiceContainer.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/model/TransactionKYC.kt
This adds the `transaction_id` fields to the SEP-12 GET/PUT endpoints. This also updates the Customer callback implementation to return different required fields if the transaction requires additional fields. The required fields will be determined by a transaction "classifier" service, which creates records in the KYC table whenever a transaction requires additional KYC.
This implementation assumes that the KYC information is shared across all customer transactions. This means that the `transaction_id` is ignored by PUT /customer callback as KYC.
This is to support the new SEP-12 protocol and SEP-6 KYC flows. A separate PR will update the flows and tests.
Customer callback documentation will be updated with the `transaction_id` field.
N/A
> [ANCHOR-712] Add transaction_id field to SEP-12 PUT/GET requests

- .github/workflows/on_push_to_develop.yml
This disables extended tests on `develop` merge as well.
The tests have been disabled for PR builds but also should be disabled on `develop` builds until Circle USDC is available.
N/A
N/A
> Disable extended tests on develop merge

- .github/workflows/on_pull_request.yml
- .github/workflows/on_push_to_develop.yml
- extended-tests/src/test/kotlin/org/stellar/anchor/platform/extendedtest/custody/CustodyApiTests.kt
- extended-tests/src/test/kotlin/org/stellar/anchor/platform/extendedtest/custody/PlatformApiCustodyTests.kt
This re-enables the extended tests.
They were disabled to unblock PRs.
N/A
N/A
> [ANCHOR-716] Re-enable extended tests

- api-schema/src/main/java/org/stellar/anchor/api/platform/PlatformTransactionData.java
- api-schema/src/main/java/org/stellar/anchor/api/rpc/method/RequestCustomerInfoUpdateRequest.java
- api-schema/src/main/java/org/stellar/anchor/api/sep/sep12/Sep12CustomerRequestBase.java
- api-schema/src/main/java/org/stellar/anchor/api/sep/sep6/Sep6TransactionResponse.java
- build.gradle.kts
- core/src/main/java/org/stellar/anchor/sep12/Sep12Service.java
- core/src/test/kotlin/org/stellar/anchor/sep12/Sep12ServiceTest.kt
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/e2etest/Sep6End2EndTest.kt
- gradle/libs.versions.toml
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/callbacks/customer/CustomerRoute.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/callbacks/customer/CustomerService.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/dao/TransactionKYCRepository.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/dao/TransactionKYCs.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/data/Data.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/di/ServiceContainer.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/processor/Sep6EventProcessor.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/model/TransactionKYC.kt
- platform/src/main/java/org/stellar/anchor/platform/component/sep/SepBeans.java
- platform/src/main/java/org/stellar/anchor/platform/controller/sep/Sep12Controller.java
- service-runner/src/main/resources/profiles/default/config.env
This adds support for the `transaction_id` field in SEP-12 GET/PUT endpoints. It also updates the SEP-6 test to use the new flow.
This is to support the latest protocol version of SEP-6.
N/A
N/A
> [ANCHOR-715] Update SEP-6 test with new KYC flow

- platform/src/main/java/org/stellar/anchor/platform/component/sep/SepBeans.java
Create ClientFinder bean when sep-10 is enabled
ClientFinder is required for SEP-10, but currently bean is not created in this case
N/A
N/A
N/A
> Fix SEP-10 clientFinder bug

- api-schema/src/main/java/org/stellar/anchor/api/rpc/method/NotifyTransactionOnHoldRequest.java
- api-schema/src/main/java/org/stellar/anchor/api/rpc/method/RpcMethod.java
- api-schema/src/main/java/org/stellar/anchor/api/sep/SepTransactionStatus.java
- platform/src/main/java/org/stellar/anchor/platform/component/platform/RpcActionBeans.java
- platform/src/main/java/org/stellar/anchor/platform/rpc/NotifyOffchainFundsAvailableHandler.java
- platform/src/main/java/org/stellar/anchor/platform/rpc/NotifyOffchainFundsReceivedHandler.java
- platform/src/main/java/org/stellar/anchor/platform/rpc/NotifyOnchainFundsReceivedHandler.java
- platform/src/main/java/org/stellar/anchor/platform/rpc/NotifyTransactionOnHoldHandler.java
- platform/src/test/kotlin/org/stellar/anchor/platform/rpc/NotifyTransactionOnHoldHandlerTest.kt
Added new RPC request (`notify_transaction_on_hold`) and handler for it
Add on_hold status support (introduced in https://github.com/stellar/stellar-protocol/pull/1479)
- Add test for new handler
TODO: add documentation for this request + update diagrams (https://stellarorg.atlassian.net/browse/ANCHOR-679 and https://stellarorg.atlassian.net/browse/ANCHOR-688)
N/A
> Add on_hold status support

- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/e2etest/Sep6End2EndTest.kt
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/Sep24Tests.kt
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/Sep31Tests.kt
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/Sep6Tests.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/callbacks/rate/RateService.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/processor/Sep6EventProcessor.kt
- service-runner/src/main/resources/config/assets.yaml
- service-runner/src/main/resources/config/stellar.host.docker.internal.toml
- service-runner/src/main/resources/config/stellar.localhost.toml
This adds the end-to-end for the SEP-6 exchange endpoints. It also cleans up the `stellar.toml` a bit.
These endpoints do not have any test coverage.
N/A
N/A
> [ANCHOR-713] Add exchange tests for SEP-6

- docs/README.md
This updates the JDK image version in the docker compose instructions. This also recommends using `docker compose` instead of `docker-compose` as the latter is being deprecated.
We are now building against JDK 17.
- Tested docker compose starts AP.
N/A
N/A
> Update JDK version in compose instructions

- core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java
- core/src/main/java/org/stellar/anchor/sep6/Sep6Service.java
- core/src/test/kotlin/org/stellar/anchor/sep24/Sep24ServiceTest.kt
- service-runner/src/main/resources/config/assets.yaml
This removes the deposit/withdraw config object checks on `iso4217` assets.
These configurations are currently required but are unused.
N/A
N/A
> [ANCHOR-730] Remove deposit/withdraw config on iso4217 assets

- core/src/main/java/org/stellar/anchor/sep38/Sep38Service.java
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/Sep38Tests.kt
This disables send limit checks when the SEP-38 context is not SEP-31.
This is to unblock the SEP-6 exchange flows.
N/A
N/A
> [ANCHOR-731] Only check send limits for SEP-31

- api-schema/src/main/java/org/stellar/anchor/api/platform/PlatformTransactionData.java
- api-schema/src/main/java/org/stellar/anchor/api/rpc/method/RequestCustomerInfoUpdateRequest.java
- api-schema/src/main/java/org/stellar/anchor/api/sep/sep6/Sep6TransactionResponse.java
- core/src/main/java/org/stellar/anchor/sep6/Sep6Transaction.java
- core/src/main/java/org/stellar/anchor/sep6/Sep6TransactionBuilder.java
- core/src/main/java/org/stellar/anchor/sep6/Sep6TransactionUtils.java
- core/src/main/java/org/stellar/anchor/util/TransactionHelper.java
- core/src/test/java/org/stellar/anchor/sep6/PojoSep6Transaction.java
- core/src/test/kotlin/org/stellar/anchor/sep6/Sep6TransactionUtilsTest.kt
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/PlatformApiTests.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/data/Data.kt
- platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep6Transaction.java
- platform/src/main/java/org/stellar/anchor/platform/rpc/RequestCustomerInfoUpdateHandler.java
- platform/src/main/java/org/stellar/anchor/platform/service/TransactionService.java
- platform/src/main/resources/db/migration/V18__sep6_remove_deprecated_kyc_fields.sql
- platform/src/test/kotlin/org/stellar/anchor/platform/rpc/RequestCustomerInfoUpdateHandlerTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/service/TransactionServiceTest.kt
This removes the deprecated `required_customer_info_updates` and `required_customer_info_message` fields.
These fields have been deprecated in favor of transactional SEP-12 APIs.
I will create PR to remove the fields from the docs.
N/A
> [ANCHOR-717] Remove deprecated SEP-6 KYC fields

- core/src/main/java/org/stellar/anchor/apiclient/BaseApiClient.java
- core/src/main/java/org/stellar/anchor/apiclient/CallbackApiClient.java
- core/src/main/java/org/stellar/anchor/apiclient/PlatformApiClient.java
Fixed bug described in #1406 
CallbackApiClient (derived from BaseApiClient) was using wrong method for JWT signature (it was hardcoded to be `authHelper.createPlatformServerAuthHeader`), which in turn raised an error because platform JWT secret wasn't defined in the scope of that particular AuthHelper   
N/A
N/A
> [ANCHOR-734] Fix wrong secret used to sign headers

- api-schema/src/main/java/org/stellar/anchor/api/exception/UnauthorizedException.java
- core/src/main/java/org/stellar/anchor/apiclient/BaseApiClient.java
- core/src/main/java/org/stellar/anchor/apiclient/CallbackApiClient.java
- core/src/main/java/org/stellar/anchor/apiclient/PlatformApiClient.java
- core/src/main/java/org/stellar/anchor/auth/AuthHelper.java
- core/src/main/java/org/stellar/anchor/auth/JwtService.java
- core/src/main/java/org/stellar/anchor/util/JwtUtil.java
- core/src/test/kotlin/org/stellar/anchor/auth/AuthHelperTest.kt
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/CallbackApiTests.kt
- extended-tests/src/test/kotlin/org/stellar/anchor/platform/extendedtest/auth/AbstractAuthIntegrationTest.kt
- extended-tests/src/test/kotlin/org/stellar/anchor/platform/extendedtest/auth/jwt/custody/AuthJwtCustodyTests.kt
- extended-tests/src/test/kotlin/org/stellar/anchor/platform/extendedtest/auth/jwt/platform/AuthJwtPlatformTests.kt
- platform/src/main/java/org/stellar/anchor/platform/apiclient/CustodyApiClient.java
- platform/src/main/java/org/stellar/anchor/platform/callback/PlatformIntegrationHelper.java
- platform/src/main/java/org/stellar/anchor/platform/component/share/CustodyApiBeans.java
- platform/src/main/java/org/stellar/anchor/platform/component/share/PlatformApiClientBeans.java
- platform/src/main/java/org/stellar/anchor/platform/config/CallbackApiConfig.java
- platform/src/main/java/org/stellar/anchor/platform/controller/AbstractControllerExceptionHandler.java
- platform/src/main/java/org/stellar/anchor/platform/custody/fireblocks/FireblocksApiClient.java
- platform/src/test/kotlin/org/stellar/anchor/platform/callback/PlatformIntegrationHelperTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/custody/CustodyApiClientTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/custody/fireblocks/FireblocksApiClientTest.kt
Refactoring of AuthHelper splitting it into different helper types (JWT/ApiKey/None)
Previous structure was bug-prone and not very flexible: you can generate wrong header type by accident. With this change there's only one method that will generate header for correct type and correct JWT type (in case of JWT) -- all of this is determined on object creation time 
- 
N/A
N/A
> [Anchor-734] AuthHelper refactoring

- api-schema/src/main/java/org/stellar/anchor/api/callback/SendEventRequestPayload.java
- api-schema/src/main/java/org/stellar/anchor/api/event/AnchorEvent.java
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/processor/AnchorEventProcessor.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/processor/NoOpEventProcessor.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/processor/Sep6EventProcessor.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/processor/SepAnchorEventProcessor.kt
This PR removes the `TRANSACTION_ERROR` event type.
The `TRANSACTION_STATUS_CHANGED` type already covers transaction errors.
https://github.com/stellar/stellar-docs/pull/819/
N/A
> [ANCHOR-441] Remove `TRANSACTION_ERROR` event type

- api-schema/src/main/java/org/stellar/anchor/api/sep/AssetInfo.java
- api-schema/src/main/java/org/stellar/anchor/api/sep/operation/Sep31Operation.java
- core/src/main/java/org/stellar/anchor/sep12/Sep12Service.java
- core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java
- core/src/main/java/org/stellar/anchor/sep38/Sep38Service.java
- core/src/main/java/org/stellar/anchor/util/AssetHelper.java
- core/src/test/kotlin/org/stellar/anchor/asset/DefaultAssetServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep31/Sep31ServiceTest.kt
- core/src/test/resources/test_assets.json
- core/src/test/resources/test_assets.json.quotes_not_supported
- core/src/test/resources/test_assets.yaml
- helm-charts/sep-service/values.yaml
- platform/src/main/resources/example.anchor-config.yaml
- platform/src/test/resources/test_assets.json
- platform/src/test/resources/test_assets.yaml
- platform/src/test/resources/test_assets_missing_distribution_account.json
- service-runner/src/main/resources/config/assets.yaml
- remove the `send` field in assets config 
- Merge all fields under `send` into `sep31`
There is no reason to have separate object for sep31 and send, as they describe the same service.
- `./gradlew test` All tests should pass
> [ANCHOR-451] Merge `send` into `sep31` in assets config

- core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java
- core/src/test/kotlin/org/stellar/anchor/sep24/Sep24ServiceTest.kt
- gradle/libs.versions.toml
- platform/src/main/java/org/stellar/anchor/platform/service/TransactionService.java
This PR unsets the `withdraw_anchor_account` on SEP-24 withdraw transaction creation. It is later when the transaction moves into `pending_user_transfer_start`.
The deposit address can be something other than the asset distribution account. It should not be set when the transaction is created.
N/A
N/A
> [ANCHOR-477] Remove `withdraw_anchor_account` on SEP-24 txn

- build.gradle.kts
- docs/README.md
- platform/src/main/java/org/stellar/anchor/platform/config/PropertySep10Config.java
- service-runner/src/main/resources/version-info.properties
Fixed #1438 
If there's a custodial wallet in clients with clientAllowList enabled, it will result to NPE because domains is null for custodial wallet
N/A
N/A
> 1438: Fix NPE

- core/src/main/java/org/stellar/anchor/sep38/Sep38Service.java
- core/src/test/kotlin/org/stellar/anchor/sep38/Sep38ServiceTest.kt
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/Sep38Tests.kt
This commit removes SEP-31 send limit checks in the SEP-38 POST /quote and GET /price APIs.
This is safe to remove since the send limits are checked at the SEP-31 transaction creation time. If the quote exceeds the send limit when created, SEP-31 will validate that the requested amount matches the quote's `sell_amount`.
N/A
N/A
> [ANCHOR-733] Remove SEP-31 send limit checks in SEP-38

- .github/workflows/sub_essential_tests.yml
- .github/workflows/sub_extended_tests.yml
- docs/01 - Contributing/A - Development Environment.md
- service-runner/build.gradle.kts
- service-runner/src/main/kotlin/org/stellar/anchor/platform/run_profiles/RunDockerDevStackNoWait.kt
Replaces usages of `docker-compose` with `docker compose`.
`docker-compose` is deprecated and the GH action workflows will not run without upgrading.
N/A
N/A
> Use docker compose v2

- platform/src/main/java/org/stellar/anchor/platform/rpc/RequestOnchainFundsHandler.java
- platform/src/test/kotlin/org/stellar/anchor/platform/rpc/RequestOnchainFundsHandlerTest.kt
This sets the `memo` value to the request `memo` value.
`memo.toString()` returns the hex value of the memo but the `memo` in the Payment object is in Base64 format, so the observer will never find the transaction in the database.
N/A
N/A
> Fix RequestOnchainFunds incorrect hash memo

- api-schema/src/main/java/org/stellar/anchor/api/sep/sep24/TransactionResponse.java
- api-schema/src/main/java/org/stellar/anchor/api/sep/sep31/Sep31GetTransactionResponse.java
- core/src/main/java/org/stellar/anchor/sep24/Sep24Helper.java
- core/src/main/java/org/stellar/anchor/sep31/Sep31Transaction.java
- core/src/main/java/org/stellar/anchor/sep6/Sep6TransactionUtils.java
- core/src/test/kotlin/org/stellar/anchor/sep24/Sep24ServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep24/Sep24ServiceTestHelper.kt
- core/src/test/kotlin/org/stellar/anchor/sep31/Sep31ServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep31/Sep31TransactionTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep6/Sep6TransactionUtilsTest.kt
This adds `quote_id` to the GET /transaction response.
This is currently missing.
N/A
N/A
> [ANCHOR-748] Add quote_id to GET /transaction responses

- platform/src/main/java/org/stellar/anchor/platform/rpc/RequestOnchainFundsHandler.java
- platform/src/test/kotlin/org/stellar/anchor/platform/rpc/RequestOnchainFundsHandlerTest.kt
`amount_out` is not set if a transaction has an associated indicative quote but has not yet received funds.
N/A
N/A
N/A
> [ANCHOR-752] Remove amount_out requirement in RequestOnchainFunds

- api-schema/src/main/java/org/stellar/anchor/api/sep/operation/Sep31Operation.java
- core/src/main/java/org/stellar/anchor/sep12/Sep12Service.java
- core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java
- core/src/test/kotlin/org/stellar/anchor/asset/DefaultAssetServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep12/Sep12ServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep31/Sep31ServiceTest.kt
- core/src/test/resources/test_assets.json
- core/src/test/resources/test_assets.yaml
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/Sep31Tests.kt
- helm-charts/sep-service/values.yaml
- platform/src/main/java/org/stellar/anchor/platform/component/sep/SepBeans.java
- platform/src/main/resources/example.anchor-config.yaml
- platform/src/test/kotlin/org/stellar/anchor/sep31/Sep31DepositInfoGeneratorTest.kt
- platform/src/test/resources/test_assets.json
- platform/src/test/resources/test_assets.yaml
- platform/src/test/resources/test_assets_missing_distribution_account.json
- service-runner/src/main/resources/config/assets.yaml
As title.
Discussed with Jake that  a customer could only have one id with the anchor, and the customer type is only used for identify KYC info purposes, so we don't actually need to traverse all the customer type in DELETE /customer request.
> [ANCHOR-732] Remove sep12 from asset config

- platform/src/main/java/org/stellar/anchor/platform/config/PropertyClientsConfig.java
- platform/src/main/resources/config/anchor-config-default-values.yaml
- platform/src/test/kotlin/org/stellar/anchor/platform/config/PropertyClientsConfigTest.kt
This adds validation for callback URLs for custodial clients.
This was missed in the previous commit.
N/A
N/A
> [ANCHOR-764] Add callback URL validation for custodial clients

- helm-charts/reference-server/templates/deployment.yaml
- helm-charts/sep-service/templates/eventprocessor-deployment.yaml
- helm-charts/sep-service/templates/observer-deployment.yaml
- helm-charts/sep-service/templates/platform-deployment.yaml
- helm-charts/sep-service/templates/sepserver-deployment.yaml
This is to resolve the following error we are seeing in the dev environment.
```
Events:
Type     Reason             Age                    From     Message
----     ------             ----                   ----     -------
Warning  ErrImageNeverPull  4m9s (x3074 over 11h)  kubelet  Container image "docker-registry.services.stellar-ops.com/dev/anchor-platform:e6ca4be8" is not present with pull policy of Never
```
It only needs to be set `Never` for local deployments to allow usage of locally built images.
N/A
N/A
> Set default `container.imagePullPolicy` to `IfNotPresent`

- core/src/main/java/org/stellar/anchor/sep6/Sep6Service.java
- platform/src/main/java/org/stellar/anchor/platform/rpc/RequestOffchainFundsHandler.java
- platform/src/test/kotlin/org/stellar/anchor/platform/rpc/RequestOffchainFundsHandlerTest.kt
`amount_out` is not set if a transaction has an associated indicative quote but has not yet received funds.
This was fixed for `RequestOnchainFunds` already.
Will update stellar-docs
N/A
> [ANCHOR-783] Remove amount_out requirement in RequestOffchainFunds

- .github/ISSUE_TEMPLATE/release-a-new-version.md
Adds a checkbox for cutting a doc release.
We now have versioned docs.
N/A
N/A
> Include doc release process in release template

- helm-charts/reference-server/templates/deployment.yaml
- helm-charts/sep-service/templates/eventprocessor-deployment.yaml
- helm-charts/sep-service/templates/observer-deployment.yaml
- helm-charts/sep-service/templates/platform-deployment.yaml
- helm-charts/sep-service/templates/sepserver-deployment.yaml
This reverts commit fff3240ee9348d82748602254cdb3282b439cb34.
The previous change did not fix the deployments, causing the pods to be evicted continuously.
N/A
N/A
> Revert "Set default `container.imagePullPolicy` to `IfNotPresent` (#1467)"

- core/src/main/java/org/stellar/anchor/client/ClientConfig.java
- core/src/main/java/org/stellar/anchor/client/CustodialClientConfig.java
- core/src/main/java/org/stellar/anchor/client/NonCustodialClientConfig.java
- core/src/test/kotlin/org/stellar/anchor/client/DefaultClientServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep24/Sep24ServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep31/Sep31ServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/util/ClientFinderTest.kt
- core/src/test/resources/test_clients.json
- core/src/test/resources/test_clients.yaml
- core/src/test/resources/test_clients_file_format_not_valid.yaml.bad
- platform/src/main/java/org/stellar/anchor/platform/config/PropertyClientsConfig.java
- platform/src/main/java/org/stellar/anchor/platform/event/ClientStatusCallbackHandler.java
- platform/src/test/kotlin/org/stellar/anchor/platform/config/ClientsConfigTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/configurator/ConfigManagerTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/event/ClientStatusCallbackHandlerTest.kt
- platform/src/test/resources/config/test_anchor_config.yaml
- platform/src/test/resources/config/test_anchor_config_missing_version.yaml
- platform/src/test/resources/test_clients.yaml
- service-runner/src/main/resources/config/clients.yaml
This commit removes the `callback_url` field from the client config.
It was deprecated in favor of SEP-specific URLs.
https://github.com/stellar/stellar-docs/pull/958
N/A
> [ANCHOR-755] Remove callback_url from client config

- api-schema/src/main/java/org/stellar/anchor/api/asset/Sep38Info.java
- api-schema/src/main/java/org/stellar/anchor/api/sep/sep38/InfoResponse.java
- core/src/test/kotlin/org/stellar/anchor/asset/DefaultAssetServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep38/Sep38ServiceTest.kt
- core/src/test/resources/test_assets.yaml
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/Sep6Tests.kt
- helm-charts/sep-service/values.yaml
- service-runner/src/main/resources/config/assets.yaml
Remove sep38 decimals from asset definition
This part of the asset config refactoring.
N/A
N/A
> [ANCHOR-794] Remove sep38 decimals from asset definition

- helm-charts/reference-server/templates/deployment.yaml
- helm-charts/sep-service/templates/eventprocessor-deployment.yaml
- helm-charts/sep-service/templates/observer-deployment.yaml
- helm-charts/sep-service/templates/platform-deployment.yaml
- helm-charts/sep-service/templates/sepserver-deployment.yaml
This sets the default pull policy to `Always`. This resolves the `ErrImagePullNever` pods we are seeing in our deployments. 
N/A
N/A
N/A
> [ANCHOR-792] Set default image pull policy to Always

- platform/src/main/resources/config/anchor-client-default-values.yaml
- platform/src/main/resources/config/anchor-config-default-values.yaml
Inline yaml support for Clients Config will be hold until further discussion with data points. The functionality will be kept in codebase but not advertised to user.
Update the config examples in `anchor-config-default-values.yaml` 
> Hold inline yaml support for Clients Config

- core/src/main/java/org/stellar/anchor/sep38/Sep38Service.java
- platform/src/main/java/org/stellar/anchor/platform/callback/RestRateIntegration.java
- platform/src/test/kotlin/org/stellar/anchor/platform/callback/RestRateIntegrationTest.kt
- Fix the rate response validation bug when there is no fee
- The `withinRoundingError` call was missing the `!` operator when there is no `fee` in the rate response.
Bub fix.
N/A
N/A
> [ANCHOR-810] Fix the rate response validation bug when there is no fee

- platform/src/main/java/org/stellar/anchor/platform/component/platform/PlatformServerBeans.java
- platform/src/main/java/org/stellar/anchor/platform/config/PlatformServerConfig.java
- platform/src/main/resources/config/anchor-config-default-values.yaml
- platform/src/main/resources/config/anchor-config-schema-v1.yaml
- service-runner/src/main/resources/profiles/auth-apikey-platform/config.env
- service-runner/src/main/resources/profiles/auth-jwt-platform/config.env
This PR simplifies the authentication configuration for the Platform API. Currently, this is configured in two places.
- `platform_server.auth`: This enables request authentication on the Platform server.
- `platform_api.auth`: This determines what is included in the HTTP header of the Platform API requests.
We are removing `platform_server.auth` in favor of using `platform_api.auth` on the server and request building sides.
These configurations are intertwined, making it confusing to configure auth. They will always need to be set to the same thing, and we should not duplicate it.
Stellar docs PR will be created
N/A
> [ANCHOR-799] Remove `platform_server.auth`

- api-schema/src/main/java/org/stellar/anchor/api/callback/GetRateRequest.java
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/CallbackApiTests.kt
The `id` field and `testRate_firm` was cleaned up in https://github.com/stellar/java-stellar-anchor-sdk/pull/1456 due to lack of usage
> [ANCHOR-797] Clean up `GET /rate` by ID

- platform/src/main/java/org/stellar/anchor/platform/callback/RestCustomerIntegration.java
- platform/src/main/java/org/stellar/anchor/platform/callback/RestFeeIntegration.java
- platform/src/main/java/org/stellar/anchor/platform/callback/RestRateIntegration.java
- platform/src/main/java/org/stellar/anchor/platform/callback/RestUniqueAddressIntegration.java
- platform/src/main/java/org/stellar/anchor/platform/event/ClientStatusCallbackHandler.java
- Fix OkHttp response leak
- Bug fixes
N/A
N/A
> [ANCHOR-822] Fix OkHttp response leak

- core/src/main/java/org/stellar/anchor/apiclient/BaseApiClient.java
- core/src/main/java/org/stellar/anchor/apiclient/CallbackApiClient.java
- core/src/test/kotlin/org/stellar/anchor/apiclient/CallbackApiClientTests.kt
- platform/src/main/java/org/stellar/anchor/platform/event/CallbackApiEventHandler.java
Fix the NPE when deliver events to callback API returns empty string
Bug fixes.
N/A
N/A
> [ANCHOR-827] Fix the NPE when deliver events to callback API returns empty string

- kotlin-reference-server/src/main/kotlin/org/stellar/reference/sep24/Sep24TestRoute.kt
- platform/src/main/java/org/stellar/anchor/platform/config/PropertyEventConfig.java
- platform/src/main/java/org/stellar/anchor/platform/config/PropertyQueueConfig.java
- platform/src/main/java/org/stellar/anchor/platform/event/KafkaSession.java
- platform/src/main/java/org/stellar/anchor/platform/utils/ResourceHelper.java
- platform/src/test/kotlin/org/stellar/anchor/platform/config/EventConfigTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/config/PropertyQueueConfigTest.kt
- Merge `PropertyEventConfig` and `PropertyQueueConfig` validations
- Bug: `PropertyQueueConfig` validation was not invoked.
- Improved the error message.
- Improved the `ssl_keystore_location` and `ssl_truststore_location` checks
- Validation bug fixes
- Validation error message improvements.
N/A
- Attach stellar-docs pull request, documenting new feature
- If it's an urgent feature request, please create a ticket and attach ticket number to this PR
N/A
> [ANCHOR-828] Improve PropertyQueueConfig validations

- api-schema/src/main/java/org/stellar/anchor/api/sep/sep12/Sep12CustomerRequestBase.java
- api-schema/src/main/java/org/stellar/anchor/api/sep/sep12/Sep12GetCustomerRequest.java
- api-schema/src/main/java/org/stellar/anchor/api/sep/sep12/Sep12PutCustomerRequest.java
- core/src/main/java/org/stellar/anchor/sep12/Sep12Service.java
- core/src/test/kotlin/org/stellar/anchor/sep12/Sep12ServiceTest.kt
-  Add transaction_id to callback customer API when request provides it
- When the business server only implements the `GET /custemer` with `transaction_id`, it is necessary for the SEP-12 to pass the `transaction_id`.
Added more tests to `Sep12ServiceTest.kt`
N/A
N/A
> [ANCHOR-834] Add transaction_id to callback customer API when request provides it

- platform/src/main/java/org/stellar/anchor/platform/callback/PlatformIntegrationHelper.java
- platform/src/main/java/org/stellar/anchor/platform/callback/RestRateIntegration.java
- platform/src/test/kotlin/org/stellar/anchor/platform/callback/RestRateIntegrationTest.kt
- Fix the the inaccurate validation error message.
- Populate the fee object with total=0 if the business server does not provide one. This is to avoid SEP-6 and SEP-31 validation errors when the business server does not provide a `rate.fee` object.
Bug fixes.
N/A
N/A
> [ANCHOR-833] Improve RestRateIntegration fee handling

- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/WebAuthContractTests.kt
- helm-charts/reference-server/templates/ingress.yaml
- helm-charts/reference-server/values.yaml
- lib-util/src/main/kotlin/org/stellar/anchor/client/Sep10CClient.kt
Adds an ingress resource for the reference server. The reference server needs to be publicly reachable for the SEP-24 flows.
> Add reference server ingress

- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/Sep38Tests.kt
- extended-tests/src/test/kotlin/org/stellar/anchor/platform/extendedtest/auth/jwt/platform/AuthJwtPlatformTests.kt
- platform/src/main/java/org/stellar/anchor/platform/callback/RestRateIntegration.java
- platform/src/test/kotlin/org/stellar/anchor/platform/callback/RestRateIntegrationTest.kt
- Add `rate.buy/sell_amount` must match `request.buy/sell_amount` validations
- Improve rounding error messages.
- Add amount matching tests to Sep38Tests (integration tests)
Validation improvements.
N/A
N/A
> [ANCHOR-842] Add `rate.buy/sell_amount` must match `request.buy/sell_amount` validations

- api-schema/src/main/java/org/stellar/anchor/api/platform/GetQuoteResponse.java
- api-schema/src/main/java/org/stellar/anchor/api/sep/sep38/Sep38QuoteResponse.java
- core/src/main/java/org/stellar/anchor/sep38/Sep38Service.java
- core/src/test/kotlin/org/stellar/anchor/sep38/Sep38ServiceTest.kt
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/PlatformApiTests.kt
- extended-tests/src/test/kotlin/org/stellar/anchor/platform/extendedtest/custody/CustodyApiTests.kt
- extended-tests/src/test/kotlin/org/stellar/anchor/platform/extendedtest/custody/PlatformApiCustodyTests.kt
Included in `Sep38QuoteResponse` which is returned by  POST /quote and GET /quote
Also in `GetQuoteResponse` which is used when publish QUOTE_CREATED event
https://github.com/stellar/stellar-protocol/pull/1556
> [ANCHOR-729]Include buy/sell delivery method in SEP-38 GET /quote response

- platform/src/main/java/org/stellar/anchor/platform/config/KafkaConfig.java
- platform/src/main/java/org/stellar/anchor/platform/config/MskConfig.java
- platform/src/main/java/org/stellar/anchor/platform/config/PropertyQueueConfig.java
- platform/src/main/java/org/stellar/anchor/platform/event/KafkaSession.java
- platform/src/main/java/org/stellar/anchor/platform/utils/TrustAllSslEngineFactory.java
- platform/src/main/resources/config/anchor-config-default-values.yaml
- platform/src/main/resources/config/anchor-config-schema-v1.yaml
- platform/src/test/kotlin/org/stellar/anchor/platform/config/EventConfigTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/event/KafkaSessionTest.kt
- service-runner/src/main/resources/version-info.properties
- Add configuration `event.queue.kafka.ssl_cert_verify` 
This flag is for dev and test environment where a valid CA may not be present. 
N/A
N/A
> [ANCHOR-836] Add configuration `event.queue.kafka.ssl_cert_verify` 

- platform/src/main/java/org/stellar/anchor/platform/config/PropertyClientsConfig.java
- platform/src/test/kotlin/org/stellar/anchor/platform/config/ClientsConfigTest.kt
Allow clients config to be left entire empty since this is not a required config
> [FIX] Allow the clients config value to be left unset

- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/AbstractIntegrationTests.kt
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/PlatformApiTests.kt
- extended-tests/src/test/kotlin/org/stellar/anchor/platform/extendedtest/custody/CustodyApiTests.kt
- extended-tests/src/test/kotlin/org/stellar/anchor/platform/extendedtest/custody/PlatformApiCustodyTests.kt
- Inject test payment values
- Testnet reset handling improvement
N/A
N/A
> [ANCHOR-831] Inject test payment values

- kotlin-reference-server/src/main/kotlin/org/stellar/reference/service/SepHelper.kt
The default unit is in (10^e-7). This needs to be raised so we don't send units less than a cent.
> [SEP-24] Raise deposit base units

- build.gradle.kts
- docs/README.md
- service-runner/src/main/resources/version-info.properties
- Bump version 2.11.0
- TRelease preparation
N/A
N/A
> Bump version 2.11.0

- platform/src/main/java/org/stellar/anchor/platform/event/CallbackApiEventHandler.java
- platform/src/main/java/org/stellar/anchor/platform/event/KafkaSession.java
- platform/src/test/kotlin/org/stellar/anchor/platform/event/KafkaSessionTest.kt
Do not search for the `keystore` and `truststore` files if `ssl_cert_verify` is to `false`. 
When ` ssl_cert_verify` is set to `false`, the `KafkaSession` still look for the file and cause IOException. 
Bug fix.
N/A
N/A
> [ANCHOR-858] Do not require keystore and truststore if ssl_cert_verify is false

- build.gradle.kts
- docs/README.md
- service-runner/src/main/resources/version-info.properties
- Bump version to `2.11.2`
- Pre-release
N/A
N/A
> Bump version to 2.11.2

- api-schema/src/main/java/org/stellar/anchor/api/asset/Sep31Info.java
- api-schema/src/main/java/org/stellar/anchor/api/sep/sep31/Sep31InfoResponse.java
- api-schema/src/main/java/org/stellar/anchor/api/sep/sep31/Sep31PostTransactionRequest.java
- core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java
- core/src/main/java/org/stellar/anchor/sep31/Sep31Transaction.java
- core/src/main/java/org/stellar/anchor/sep31/Sep31TransactionBuilder.java
- core/src/main/java/org/stellar/anchor/util/AssetValidator.java
- core/src/main/java/org/stellar/anchor/util/SepHelper.java
- core/src/main/java/org/stellar/anchor/util/TransactionMapper.java
- core/src/main/resources/config/anchor-asset-default-values.yaml
- core/src/test/java/org/stellar/anchor/sep31/PojoSep31Transaction.java
- core/src/test/kotlin/org/stellar/anchor/asset/DefaultAssetServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep31/Sep31ServiceTest.kt
- core/src/test/resources/test_assets.json
- core/src/test/resources/test_assets.json.quotes_not_supported
- core/src/test/resources/test_assets.yaml
- core/src/test/resources/test_assets_duplicate_receive_methods.yaml
- core/src/test/resources/test_assets_missing_receive_method.yaml
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/e2etest/Sep31End2EndTests.kt
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/PlatformApiTests.kt
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/Sep31Tests.kt
- extended-tests/src/test/kotlin/org/stellar/anchor/platform/extendedtest/custody/PlatformApiCustodyTests.kt
- helm-charts/sep-service/values.yaml
- platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep31Transaction.java
- platform/src/main/resources/db/migration/V20__sep31_add_funding_method.sql
- platform/src/main/resources/example.anchor-config.yaml
- platform/src/test/resources/test_assets.json
- platform/src/test/resources/test_assets.yaml
- platform/src/test/resources/test_assets_missing_distribution_account.json
- service-runner/src/main/resources/config/assets.yaml
- Add `funding_methods` to `/info` response. This field is mandatory for the anchor. 
- Add `funding_method` to `POST /transaction` param. This field is mandatory for wallet.
SEP-31 changes scoped in https://github.com/stellar/stellar-protocol/pull/1567
The SEP-6 change will be handled in a separate PR.
> [ANCHOR-809][SEP-31] Add funding_method to SEP-31

- core/build.gradle.kts
Use gradle.properties instead of env vars
Maven publication improvement
> Use gradle.properties instead of env vars

- .github/workflows/sub_essential_tests.yml
- platform/src/main/java/org/stellar/anchor/platform/configurator/DataConfigAdapter.java
- platform/src/main/resources/config/anchor-config-default-values.yaml
- platform/src/main/resources/config/anchor-config-schema-v1.yaml
- service-runner/src/main/resources/profiles/default/config.env
[ANCHOR-592] Add data.schema to configuration 
Per anchor's request.
Documented in `anchor-config-default-values.yaml`
N/A
[ANCHOR-592]: https://stellarorg.atlassian.net/browse/ANCHOR-592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ANCHOR-592] Add data.schema to configuration to `develop` branch

- platform/src/main/java/org/stellar/anchor/platform/configurator/DataConfigAdapter.java
- platform/src/main/resources/config/anchor-config-default-values.yaml
Right now `languages` in yaml doc is misleading.
This property is the list of supported languages. 
> [ANCHOR-707] Improve comments of `languages` in anchor config

- .github/workflows/sub_essential_tests.yml
- .github/workflows/sub_extended_tests.yml
- .github/workflows/sub_gradle_build.yml
- .github/workflows/sub_jacoco_report.yml
- extended-tests/src/test/kotlin/org/stellar/anchor/platform/extendedtest/custody/PlatformApiCustodyTests.kt
This fixes the extended-tests after the Testnet reset. It also fixes the broken paths in the CI workflows after the repo was renamed.
Testnet reset
N/A
N/A
> [ANCHOR-926] Ignore transfer_received_at field in API tests

- platform/src/main/resources/config/anchor-config-default-values.yaml
- service-runner/src/main/resources/profiles/default/config.env
- Set callback-api-request.enabled default to false
- The "What's Changed" from v2 to v3 will document this. 
- Improvements
The "What's Changed" from v2 to v3 will document this. 
This would be a breaking change. It should be part of the v3 release.
> [ANCHOR-431] Set callback-api-request.enabled default to false

- .github/workflows/sub_essential_tests.yml
- .github/workflows/sub_extended_tests.yml
- .github/workflows/sub_gradle_build.yml
- .github/workflows/sub_jacoco_report.yml
- build.gradle.kts
- docs/README.md
- extended-tests/src/test/kotlin/org/stellar/anchor/platform/extendedtest/custody/PlatformApiCustodyTests.kt
- platform/src/main/resources/config/anchor-config-default-values.yaml
- service-runner/src/main/resources/profiles/default/config.env
- service-runner/src/main/resources/version-info.properties
> [CHORE] Bump version 3.0.0

- helm-charts/README.md
- helm-charts/secret-store/templates/secretstore.yaml
- helm-charts/sep-service/values.yaml
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/data/Config.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/di/ConfigContainer.kt
This adds the instructions for setting up AP locally using minikube.
N/A
- Tested against demo wallet locally.
N/A
Event processing doesn't seem to be working and needs to be fixed.
> Add instructions for local kubernetes setup

- helm-charts/README.md
This pins the Postgres and Kafka Helm charts versions in the README.
Reproducible instructions
N/A
N/A
> [Fix] Pin chart versions in helm charts README

- .github/workflows/sub_essential_tests.yml
- .github/workflows/sub_extended_tests.yml
- .github/workflows/sub_gradle_build.yml
- .github/workflows/sub_jacoco_report.yml
This updates the `upload-artifact` and `download-artifact` versions to v4.
v3 is deprecated and blocking CI runs.
N/A
N/A
> Use upload-artifact@v4 action in GHA workflows

- platform/src/main/java/org/stellar/anchor/platform/observer/ObservedPayment.java
- platform/src/main/java/org/stellar/anchor/platform/observer/stellar/StellarPaymentObserver.java
- platform/src/main/java/org/stellar/anchor/platform/utils/PaymentsUtil.java
- platform/src/test/kotlin/org/stellar/anchor/platform/observer/stellar/StellarPaymentObserverTest.kt
This adds parsing of SAC transfers to the observer. Horizon's payment endpoint exposes these types of payments as an InvokeHostFunctionOp with a list of asset balance changes.
C-account payment observation
Currently none. Integration tests will be added when implementing SEP-6/24/31.
N/A
N/A
> [ANCHOR-762] Implement SAC transfer observation

- core/src/main/java/org/stellar/anchor/sep6/Sep6TransactionStore.java
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/e2etest/Sep6End2EndTest.kt
- platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep6TransactionRepo.java
- platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep6TransactionStore.java
- platform/src/main/java/org/stellar/anchor/platform/service/PaymentOperationToEventListener.java
- platform/src/test/kotlin/org/stellar/anchor/platform/service/PaymentOperationToEventListenerTest.kt
This implements SEP-6 withdraw + withdraw exchange flows for contract accounts. The main change is to allow contract accounts as source and destination accounts for SEP-6 withdraw requests. The bulk of this PR is adding test code.
Contract account support
N/A
SEP-45 does not support memos so we cannot create a new customer every time the test is run. Therefore, we cannot assert on the intermediate PENDING_CUSTOMER_INFO_UPDATE status since a previous run may have already created a customer with enough KYC.
> [ANCHOR-768]  Implement SEP-6 withdraw flows for contract accounts 

- helm-charts/sep24-reference-ui/templates/deployment.yaml
The env var has moved to value file, this sep24-reference-ui-config is no longer needed
- Some changes were override in last PR
- new ui container started successfully on local
> [PD] Fix sep24-reference-ui-config is missing error

- helm-charts/reference-server/templates/ingress.yaml
- helm-charts/reference-server/values.yaml
- helm-charts/sep24-reference-ui/templates/ingress.yaml
- helm-charts/sep24-reference-ui/values.yaml
Match the ingress host key between local and kube
Ingress host is defined with key `ingress.host` in local value file, and this is different from `ingress.rules.host` in Kube, resulting ingress host value might not be properly overwritten
- Tested with minikube evrything works locallly.
> [PD] Fix ingress host key mismatch between local and kube

- helm-charts/sep24-reference-ui/templates/ingress.yaml
configmap has been removed for sep24-reference-ui, thus removing corresponding annotation
`nginx.ingress.kubernetes.io/custom-headers: anchor-platform-dev/sep24-reference-ui-configmap`
> [PD] Remove configmap annotation

- platform/src/main/java/org/stellar/anchor/platform/component/sep/SepBeans.java
- platform/src/main/java/org/stellar/anchor/platform/config/PropertySecretConfig.java
- platform/src/main/java/org/stellar/anchor/platform/config/PropertySep45Config.java
- platform/src/main/resources/config/anchor-config-default-values.yaml
- platform/src/main/resources/config/anchor-config-schema-v1.yaml
- platform/src/test/kotlin/org/stellar/anchor/platform/config/SecretConfigTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/config/Sep45ConfigTest.kt
This PR adds SEP-45 configuration validation. I decided to do the secret validation in the secret config implementation. I think it's the best place to implement it. Dependent configs, like SEP-45, should just check that the relevant properties are set. We should refactor the rest of the configuration to follow the same pattern.
It's currently missing.
N/A
N/A
> [ANCHOR-955] Add SEP-45 config validation

- helm-charts/sep24-reference-ui/templates/deployment.yaml
- helm-charts/sep24-reference-ui/values.yaml
The following step of [[PD] Add allowed host env var](https://github.com/stellar/sep24-reference-ui/pull/14)
Next step would be update kube repo with `allowedHost=<ingressHost>`
Tested with minikube and env var was properly populated
> [PD] Add allowedHost to helm charts

- core/src/main/java/org/stellar/anchor/sep10/Sep10Service.java
- core/src/main/java/org/stellar/anchor/sep12/Sep12Service.java
- core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java
- core/src/test/kotlin/org/stellar/anchor/TestHelper.kt
- core/src/test/kotlin/org/stellar/anchor/auth/JwtServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/filter/WebAuthJwtFilterTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep24/Sep24ServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep31/Sep31ServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep38/Sep38ServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep6/ExchangeAmountsCalculatorTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep6/Sep6ServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/util/ClientFinderTest.kt
- platform/src/main/java/org/stellar/anchor/platform/controller/sep/Sep12Controller.java
- platform/src/main/java/org/stellar/anchor/platform/controller/sep/Sep24Controller.java
- platform/src/main/java/org/stellar/anchor/platform/controller/sep/Sep31Controller.java
- platform/src/main/java/org/stellar/anchor/platform/controller/sep/Sep38Controller.java
- platform/src/main/java/org/stellar/anchor/platform/controller/sep/Sep6Controller.java
- platform/src/main/java/org/stellar/anchor/platform/controller/sep/WebAuthJwtHelper.java
- platform/src/test/kotlin/org/stellar/anchor/platform/service/SimpleInteractiveUrlConstructorTest.kt
This renames all instances of `Sep10Jwt` to `WebAuthJwt`.
The class was renamed to be generic to SEP-10 and SEP-45 so the variable names should also change.
N/A
N/A
> Clean up all instances of `Sep10Jwt`

- core/src/main/java/org/stellar/anchor/sep12/Sep12Service.java
- core/src/test/kotlin/org/stellar/anchor/sep12/Sep12ServiceTest.kt
SEP-12 already supports contract accounts since it passes the `account` field from the `WebAuthJwt` directly into the customer callback without checking its type. This PR just adds some unit tests to explicitly test that passing a contract account to all endpoints does not throw exceptions. The SEP-6 end-to-end tests further test that the endpoint works as expected. 
Contract account support
N/A
N/A
> [ANCHOR-789] Update SEP-12 to explicitly support contract accounts

- kotlin-reference-server/src/main/kotlin/org/stellar/reference/sep24/Sep24TestRoute.kt
use `call.request.queryParameters` to properly fetch url query params following the `?`
When testing with Sep24TestRoute on kubernetes, reference server throws below error
```
16:39:37.446 INFO  - o.s.r.s.Sep24TestRoute - Called /sep24/interactive with parameters Parameters [transaction_id=[1ff8fcca-a5ca-4d2a-b883-723f8abe3b01]]
16:39:37.449 ERROR - o.s.r.ReferenceServer - Unexpected exception
org.stellar.reference.ClientException: Missing token parameter in the request
```
The potential cause could be proxy, encoding,  middlewares or as simple as this PR. 
- Printed out in local that params were correctly parsed.
> [PD] use call.request.queryParameters

- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/AbstractIntegrationTests.kt
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/e2etest/Sep24End2EndTests.kt
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/e2etest/Sep6End2EndTest.kt
- platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep24TransactionRepo.java
- platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep24TransactionStore.java
- platform/src/main/java/org/stellar/anchor/platform/service/PaymentOperationToEventListener.java
- platform/src/test/kotlin/org/stellar/anchor/platform/service/PaymentOperationToEventListenerTest.kt
This implements SEP-24 withdraw flows for contract accounts. The bulk of this PR is adding test code.
Contract account support
N/A
N/A
> [ANCHOR-770] Implement SEP-24 withdraw for contract accounts

- kotlin-reference-server/src/main/kotlin/org/stellar/reference/sep24/Sep24TestRoute.kt
Reference server is unavailable on k8s. Adding a root route for test and debug
> [PD] Add reference server root route

- helm-charts/README.md
- Update the helm readme.doc
- Doc improvement
N/A
N/A
> [CHORE] Update the helm readme.doc

- build.gradle.kts
- docs/README.md
- service-runner/src/main/resources/version-info.properties
For release 3.0.2
`stg` env is now available for test.
> [CHORE] Bump version to 3.0.2

- core/src/main/java/org/stellar/anchor/auth/JwtService.java
- core/src/main/java/org/stellar/anchor/auth/Sep10Jwt.java
- core/src/main/java/org/stellar/anchor/auth/Sep45Jwt.java
- core/src/main/java/org/stellar/anchor/auth/WebAuthJwt.java
- core/src/main/java/org/stellar/anchor/filter/WebAuthJwtFilter.java
- core/src/main/java/org/stellar/anchor/sep10/Sep10Service.java
- core/src/main/java/org/stellar/anchor/sep45/Sep45Service.java
- core/src/test/kotlin/org/stellar/anchor/TestHelper.kt
- core/src/test/kotlin/org/stellar/anchor/auth/JwtServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/auth/WebAuthJwtTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep10/Sep10ServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep12/Sep12ServiceTest.kt
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/e2etest/Sep24End2EndTests.kt
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/CallbackApiTests.kt
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/Sep24Tests.kt
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/Sep45Tests.kt
- extended-tests/src/test/kotlin/org/stellar/anchor/platform/extendedtest/auth/AbstractAuthIntegrationTest.kt
It's currently using the SEP-10 secret. This PR updates the encode/decode to use the SEP-45 secret instead.
Tech debt
N/A
N/A
> Use SEP-45 JWT secret for signing SEP-45 JWTs

- core/src/main/java/org/stellar/anchor/sep12/Sep12Service.java
Improve error msg to be more indicative.
When testing SEP-6 with demo wallet, the KYC step requires all dates to be in ISO8601 format. 
> [Fix] Improve date error msg

- core/src/main/java/org/stellar/anchor/config/Sep38Config.java
- core/src/main/java/org/stellar/anchor/sep38/Sep38Service.java
- core/src/test/kotlin/org/stellar/anchor/sep38/Sep38ServiceTest.kt
- platform/src/main/java/org/stellar/anchor/platform/component/sep/SepBeans.java
- platform/src/main/java/org/stellar/anchor/platform/config/PropertySep38Config.java
- platform/src/main/resources/config/anchor-config-default-values.yaml
- platform/src/main/resources/config/anchor-config-schema-v1.yaml
- platform/src/test/kotlin/org/stellar/anchor/platform/config/Sep38ConfigTest.kt
SEP-38 already supports contract accounts. This PR makes it explicit by adding tests.
Contract account support
N/A
N/A
> [ANCHOR-914] Implement SEP-38 contract account support

- platform/src/main/java/org/stellar/anchor/platform/configurator/SentryConfigAdapter.java
- Send a message to indicate sentry is started if `sentry.dsl` is defined.
This is to indicate the sentry is activated instead of waiting for an exception to happen.
N/A
N/A
> [CHORE] Send a message to indicate sentry is started

- kotlin-reference-server/src/main/kotlin/org/stellar/reference/event/processor/Sep6EventProcessor.kt
Refactor sep6EventProcessor to Separate `RequestOffchainFundsRequest` and `RequestOnchainFundsRequest` for `deposit`/`deposit-exchange` and `withdraw`/`withdraw-exchange` requests, allowing quote info to be included in txn.
This fix demo wallet send incorrect payment amount to user
- Tested with demo wallet
> [ANCHOR-1001] Improve reference server SEP-6 flow compatibility with quote

- helm-charts/sep-service/templates/eventprocessor-deployment.yaml
Fix missing SENTRY_AUTH_TOKEN in event processor
- Bug fix
N/A
N/A
> [ANCHOR-632] Fix missing SENTRY_AUTH_TOKEN in event processor

- platform/src/main/java/org/stellar/anchor/platform/configurator/SentryConfigAdapter.java
- Send sentry initialization message in debug level. (Log level not available)
- This is to indicate the sentry is activated instead of waiting for an exception to happen.
N/A
N/A
> Send sentry initialization message in debug level

- soroban/README.md
This adds the salt parameter to the contract deploy instructions so that the contract addresses stay the same between Testnet resets. The salt used is just the hash hex of "anchor-platform".
We don't want to update the code when there is a testnet reset.
N/A
N/A
> Fix contract address using a salt on deploy

- core/src/main/java/org/stellar/anchor/sep24/Sep24Helper.java
- core/src/test/kotlin/org/stellar/anchor/sep24/Sep24ServiceTest.kt
- core/src/test/kotlin/org/stellar/anchor/sep24/Sep24ServiceTestHelper.kt
The `setSharedTransactionResponseFields` only have partial of the shared fields included, resulting rest of the fields missing in get transaction response
> [ANCHOR-1018] Fix sep24 txn fields were not populated into response

- core/src/main/java/org/stellar/anchor/sep45/Sep45Service.java
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/Sep45Tests.kt
- soroban/README.md
- soroban/contracts/web-auth/src/lib.rs
This updates the argument names of the SEP-45 `web_auth_verify` function and adds `sep` and `version` to the contract meta.
It was renamed.
N/A
N/A
> [Chore] Update SEP-45 contract version

- .github/workflows/on_release_created_or_updated.yml
- build.gradle.kts
- docs/README.md
- service-runner/src/main/resources/version-info.properties
This bumps the version to `3.2.0-beta.1` and disables the Docker image publish with the latest tag.
Releasing a preview for testing the contract account features.
Stellar docs to be updated
N/A
> [Chore] Bump version to `3.2.0-beta.1`

- build.gradle.kts
- core/src/main/java/org/stellar/anchor/util/AssetValidator.java
- core/src/main/resources/config/anchor-asset-default-values.yaml
- docs/README.md
- service-runner/src/main/resources/version-info.properties
If the following attributes are not set in the `assets.yaml`, NPE is thrown:
- `sep6.deposit.max_amount`
- `sep6.withdraw.max_amount`
- `sep24.deposit.max_amount`
- `sep24.withdraw.max_amount`
- `sep31.receive.max_amount`
- Bug fix
N/A
N/A
> [ANCHOR-1049] Fix NPE when the `max_amount` is not set in assets.yaml

- kotlin-reference-server/src/main/kotlin/org/stellar/reference/callbacks/rate/RateService.kt
- kotlin-reference-server/src/main/kotlin/org/stellar/reference/service/SepHelper.kt
- service-runner/src/main/resources/config/assets.yaml
- service-runner/src/main/resources/config/stellar.localhost.toml
1. Supports SRT usage in demo wallet SEP-6 by adding the `rate`
2. Improving error msg.  `....resultCodes` includes sth more meaningful like `op_src_no_trust `, whereas the `....resultCodes?.transactionResultCode` just always return `tx_failed`
Tested with demo wallet with local setup, also tried SEP-6 and SEP-24 e2e tests with hardcoded SRT asset.
Once this PR being checked in, we can test against ap-dev instance
> [ANCHOR-1029] Support SRT in anchor platform

- core/src/main/java/org/stellar/anchor/ledger/Horizon.java
- core/src/main/java/org/stellar/anchor/ledger/LedgerClientHelper.java
- core/src/main/java/org/stellar/anchor/ledger/LedgerTransaction.java
- core/src/main/java/org/stellar/anchor/ledger/PaymentTransferEvent.java
- core/src/main/java/org/stellar/anchor/ledger/StellarRpc.java
- core/src/main/java/org/stellar/anchor/util/AssetHelper.java
- core/src/test/kotlin/org/stellar/anchor/ledger/HorizonTest.kt
- core/src/test/kotlin/org/stellar/anchor/ledger/LedgerClientHelperTest.kt
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/AbstractIntegrationTests.kt
- essential-tests/src/testFixtures/kotlin/org/stellar/anchor/platform/integrationtest/PaymentObserverTests.kt
- platform/src/main/java/org/stellar/anchor/platform/observer/stellar/DefaultPaymentListener.java
- platform/src/main/java/org/stellar/anchor/platform/observer/stellar/HorizonPaymentObserver.java
- platform/src/main/java/org/stellar/anchor/platform/observer/stellar/SacToAssetMapper.java
- platform/src/main/java/org/stellar/anchor/platform/observer/stellar/StellarRpcPaymentObserver.java
- platform/src/test/kotlin/org/stellar/anchor/platform/custody/fireblocks/FireblocksEventServiceTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/observer/stellar/DefaultPaymentListenerTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/rpc/NotifyOnchainFundsReceivedHandlerTest.kt
- platform/src/test/kotlin/org/stellar/anchor/platform/rpc/NotifyOnchainFundsSentHandlerTest.kt
- Handle contract payment events in the StellarRpcPaymentObserver and tests.
- Minor refactoring of LedgerClientHelp to reduce the size of the class and move them to calling classes if not commonly used.
- Add c-account support in the observer
N/A
N/A
> [ANCHOR-1054] Handle contract payment events in the StellarRpcPaymentObserver and tests.

- helm-charts/reference-server/templates/deployment.yaml
- helm-charts/reference-server/values.yaml
This adds the `rpcEndpoint` config which is now required as of merging `feature/c-accounts` into `develop`
The reference server is crashing in dev. The config is also missing from the local deployment.
N/A
N/A
> Fix reference server values file

- build.gradle.kts
- Add JDK 17.0.16 verification for Sectigo Root Certificate
- Prior to openjdk@17.0.16, the Sectigo Root Cert is missing. `17.0.16` is required for AP to work properly to fetch client domain Stellar file successfully.
> [CHORE] Add JDK 17.0.16 verification for Sectigo Root Certificate
